### PR TITLE
VstsAzureHelpers_: Write-Host output hashtable content and not object type

### PR DESCRIPTION
**Pull request by mortenlerudjordet**
**Task name**: Common/VstsAzureHelpers_

**Description**: 
Output showing content of hashtable and not object type.
Changed code in Tasks/Common/VstsAzureHelpers_/InitializeAzModuleFunctions.ps1 to: 
```
Write-Host "##[command]$command $($args | Out-String)
```
Also ran build on all dependent task and bumped version.
Version set to 238 and patch: 0 for all dependent tasks expect AzurePowershellV5 where patch: 2
```
$tasks = "AzureCloudPowerShellDeploymentV1,AzureCloudPowerShellDeploymentV2,AzureFileCopyV1,AzureFileCopyV2,AzureFileCopyV3,AzureFileCopyV4,AzureFileCopyV5,AzureFileCopyV6,AzurePowerShellV2,AzurePowerShellV3,AzurePowerShellV4,AzurePowerShellV5,SqlAzureDacpacDeploymentV1"
$buildTasks = $tasks.split(",")

foreach($task in $buildTasks) {
	node make.js build --task $task
}
```

**Documentation changes required:** (Y/N) No

**Added unit tests:** (Y/N) No

**Attached related issue:** (Y/N) #19696

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by mortenlerudjordet** [comment]
@v-mohithgc: See that build does not like patch: 1 on AzurePowershellV5. Have reverted to 0, and that should take care of the build pipeline error.
Please run again

**Comment by mortenlerudjordet** [comment]
@v-mohithgc: I have set patch: 2 for both AzurePowershellV5 and AzureFileCopyV6 as these have changed in resent commits.
Should get a clean run from the pipeline, until someone else checks in changes to one of the task dependencies.

Also did a force reset to get a clean history.

**Comment by mortenlerudjordet** [comment]
Updated AzurePowershellV5 to patch:6 with node make.js build --task AzurePowerShellV5

**Comment by mortenlerudjordet** [comment]
Bump azFileCopyV5 to patch 4 and build

**Comment by mortenlerudjordet** [comment]
@LeftTwixWand : Bumped patch for AzureFileCopyV2 (2) ,AzureFileCopyV6 (4),AzurePowerShellV4 (2) and ran build on them

**Comment by mortenlerudjordet** [comment]
@LeftTwixWand : Bumped AzureFileCopyV1,AzureFileCopyV3,AzureFileCopyV4 after updates

**Comment by mortenlerudjordet** [comment]
@LeftTwixWand : Bumped patch AzurePowerShellV3 after merge updates

**Comment by mortenlerudjordet** [comment]
@LeftTwixWand : As PR #19752 bumps all the same tasks as I need for the change in common. My thinking is that I should not need to do any more patch bumps to get a clean run of the pipeline after the merge of the other PR happens.

**Comment by LeftTwixWand** [comment]
Hey @mortenlerudjordet no I think we can wait for #19752 to be merged

**Comment by mortenlerudjordet** [comment]
@v-mohithgc or @LeftTwixWand : #19752 is now merged, please run pipeline.
Should now not need to bump task dependent on common to get this through.

**Review by LeftTwixWand — APPROVED** [review]

**Comment by mortenlerudjordet** [comment]
@LeftTwixWand : Not seen this pipeline error before, and doubt I can contribute to get it sorted ;)

> Access denied. PipelineTools Build Service (mseng) needs Edit build quality permissions for vstfs:///Build/Build/27738558 in team project PipelineTools to perform the action.

**Comment by mortenlerudjordet** [comment]
Merged in PR: #19762, closing this PR.

**Pull request closed without merging**
