### PR TITLE
Upgrade HelmInstallerV0 to NodeJS16

### PR DESCRIPTION
**Pull request by DmitriiBobreshev**
**Task name**: HelmInstallerV0 

**Description**: 
- bumped task version
- add node16 handler
- added execution permissions to handler

**Documentation changes required:** N

**Added unit tests:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by DmitriiBobreshev** [comment]
\azp run

**Review by v-nagarajku — APPROVED** [review]

**Pull request merged**
