### PR TITLE
Tasks Updates - G1 - Common (npm) - MSAL

### PR DESCRIPTION
**Pull request by ozanovus**
**Task name**: AzureKeyVaultV1, AzureKeyVaultV2, AzureResourceManagerTemplateDeploymentV3, AzureAppServiceManageV0

**Description**: Updated package dependencies for common npm package (MSAL upgrade)

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Review by starkmsu — APPROVED** [review]

**Review by z00sts — APPROVED** [review]

**Comment by ozanovus** [comment]
MacOS tests started to fail. I'll investigate.

**Review by rohit-batra — COMMENTED** [review]
LGTM (Not allowing to approve post merge i guess)

**Comment by v-mohithgc** [comment]
Hi @ozanovus @z00sts @starkmsu @rohit-batra, looks like this PR hasn't gone thru manual functionality testing.
For AzureKeyVault task there is an open [issue](https://github.com/microsoft/azure-pipelines-tasks/issues/17127) where "azure-pipelines-tasks-azure-arm-rest-v2" package is throwing out few annoying warnings.

I tested the changes made in this PR and I can see many warnings.
image

 Can you please revert the changes made to azure key vault task in this PR, before it's rolled out to production.

**Comment by ozanovus** [comment]
I've connected with @v-mohithgc , we're investigating the warnings.

**Pull request merged**
