### PR TITLE
[IISWebAppDeploymentOnMachineGroupV0] Migrate to Node 16 with updated `webdeployment-common` library

### PR DESCRIPTION
**Pull request by aleksandrlevochkin**
**Task name**: IISWebAppDeploymentOnMachineGroupV0

**Description**: 

- Generated task for Node16_225 build config
- Overrode package.json and package-lock.json for Node 16
- Bumped `azure-pipelines-tasks-webdeployment-common` library to v4.227.0 for Node 16 to resolve the error that occurred when the path to `msdeploy.exe` contained spaces (https://github.com/microsoft/azure-pipelines-tasks/issues/18811)

**Documentation changes required:** N

**Added unit tests:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by v-nagarajku — COMMENTED** [review]
@aleksandrlevochkin - I have tested the PR and it is working as expected. 
image

Test case - I created website from my local IIS server and I was able to deploy the web app from the task and task was succeeded.

**Comment by v-nagarajku** [comment]
@ozanaydinMSFT - I have tested this PR and could see task got succeeded and my sample web app was deployed to local IIS server. Can you please provide your feedback on this, before merging? Thanks
image

**Review by v-nagarajku — APPROVED** [review]
LGTM

**Review by vmapetr — APPROVED** [review]

**Review by Pranshu-Negi — APPROVED** [review]

**Pull request merged**
