### PR TITLE
Allow arguments for PowerShell V2 task also for inline option

### LINKED ISSUE #7029: PowerShell version 2 (preview) Task missing support for Arguments
The PowerShell version 2.* (preview) Task Inline Type appears to be missing support for command line Arguments to be specified as was/is available in version 1.*.

ps_inline-v1
ps_inline-v2

Crossposted here: https://developercommunity.visualstudio.com/content/problem/237299/powershell-version-2-preview-task-missing-support.html

### PR DESCRIPTION
**Pull request by bergmeister**
Fixes #7029 and #5914 by allowing the inline option of the `PowerShellV2` task to also use arguments because as far as I could see the inline option uses a temporary file under the hood anyway and it would just work (have not tested it though)

### CODE REVIEW

**Comment by iricigor** [comment]
Is there any plan to merge this PR?

**Comment by xrkolovos** [comment]
Any news on this one? Thank you

**Comment by xrkolovos** [comment]
:(

**Comment by anatolybolshakov** [comment]
Hi @bergmeister @iricigor @xrkolovos as per comment https://github.com/microsoft/azure-pipelines-tasks/issues/5914#issuecomment-358710561 - this disabled for inline scripts because of security concerns. Could you please check if macro syntax to inline the variables into script works for you?
Let me close this at the moment - please feel free to ask any questions about it.

**Pull request closed without merging**
