### PR TITLE
add tree parameters and typings

### LINKED ISSUE #8355: Jenkins has received an average of 0.3 REST API calls per minute over the past 15 minutes which do not specify the tree parameter.
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - TFS 15.117.27024.0

## Issue Description

Some Jenkins API calls are without a tree parameter. If you have some load on your TFS the Jenkins is called a lot of times.

> Jenkins has received an average of 0.3 REST API calls per minute over the past 15 minutes which do not specify the tree parameter. This can severely impact the performance of Jenkins. See this Knowledgebase article which covers best practices for using the API and how to block unrestricted API calls.

### Task logs

> 2018-09-14T07:23:15.0457468Z ##[debug]createRootJob(): https://jenkins/queue/item/15496/api/json
2018-09-14T07:23:15.1394954Z ##[debug]createRootJob().requestCallback()
2018-09-14T07:23:15.1394954Z ##[debug]parsedBody for: https://jenkins/queue/item/15496/api/json: 
2018-09-14T07:23:15.1394954Z ##[debug]getting job task URL:https://jenkins/job/PLATTFORM40/job/web/job/jenkinsfile/api/json
2018-09-14T07:23:15.1394954Z ##[debug](0:jenkinsfile:83) debug: created
2018-09-14T07:23:15.1394954Z ##[debug]getting job task URL:https://jenkins/job/PLATTFORM40/job/web/job/jenkinsfile/api/json
2018-09-14T07:23:15.1394954Z ##[debug]jobQueue.start()
2018-09-14T07:23:15.2488721Z ##[debug]parsedBody for: https://jenkins/job/PLATTFORM40/job/web/job/jenkinsfile/api/json: 
2018-09-14T07:23:15.2644979Z ##[debug](2:jenkinsfile:83) debug: state changed from: 0a

### PR DESCRIPTION
**Pull request by CSchulz**
fixes #8355

/cc @kelliejos

### CODE REVIEW

**Comment by CSchulz** [comment]
Are there any dedicated tests to adjust?

**Comment by kelliejos** [comment]
There are unit tests for this task. You can run them via the command line: `node make.js test --task JenkinsQueueJobV2 --suite L0`

**Comment by CSchulz** [comment]
Is there any reason why they are not running automatically?

**Comment by kelliejos** [comment]
Thank you for your contribution! Apologies for the delay in merging it.

**Pull request merged**
