### PR TITLE
fix(16789): allow whitespace in bicep deployment file paths

### PR DESCRIPTION
**Pull request by jupjohn**
**Task name**: AzureResourceManagerTemplateDeploymentV3

**Description**: Allow bicep template file paths to contain spaces

**Documentation changes required:** (N)

**Added unit tests:** (Y)

**Attached related issue:** (Y) #16789 (and would supersede #19382)

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] ~~Checked that applied changes work as expected~~ I haven't been able to confirm this due to many (many) publish & test environment issues. I'm relying on the pipeline to let me know if the tests run as I've spent too long just trying to get any of them to pass from mainline

### CODE REVIEW

**Comment by jupjohn** [comment]
@microsoft-github-policy-service agree

**Comment by thommaa** [comment]
@manolerazvan please proceed here to have the pipelines run.

**Comment by jupjohn** [comment]
@manolerazvan I appreciate that this is probably low-priority for you, but when you've got some time could you review this PR please? We've run into this issue inside of my organisation a few times since and are keen to get this merged.

**Comment by jupjohn** [comment]
Closing as superseded by #20426

**Pull request closed without merging**
