### PR TITLE
Allow passing environment variables in AzureContainerAppsV0 task

### PR DESCRIPTION
**Pull request by Basssiiie**
**Task name**: AzureContainerAppsV0

**Description**: add the possibility to pass environment variables to the deployed container app, as supported by the CLI.

**Documentation changes required:** Y, any documentation outside this repository listing the available arguments for this task should be updated.

**Added unit tests:** N, there were no tests for similar arguments either so was not sure how to unit test it. If it is still preferred, please let me know with some pointers on how the test is preferred.

**Attached related issue:** Y, #17493, https://github.com/Azure/container-apps-deploy-pipelines-task/issues/4

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by Basssiiie** [comment]
@microsoft-github-policy-service agree

**Comment by cormacpayne** [comment]
@Basssiiie Thanks for making this change! This looks good to me, and I'll make sure to port it over to our [RC task](https://github.com/Azure/container-apps-deploy-pipelines-task) and [GitHub Action](https://github.com/azure/container-apps-deploy-action) so folks are able to have compatible functionality there.

**Comment by Basssiiie** [comment]
Thanks! 😃

**Comment by cormacpayne** [comment]
@Basssiiie it appears the pipelines are failing due to the `package-lock.json` generated while building the task is different from what we currently have checked in with the task -- I'm assuming the pipelines try to create a fresh lock file to make sure dependencies are up-to-date?

If you're able to, would you mind regenerating the `package-lock.json` for the task by doing the following:
- Delete the `package-lock.json` folder in the `Tasks/AzureContainerAppsV0` folder
  - If it exists, go ahead and delete the `node_modules` folder here as well
- From the root of the `azure-pipelines-tasks` repo, run the following:
  - `node make.js build --task AzureContainerAppsV0`

This should update a few dependencies in our lock file and _hopefully_ the pipelines will pass so we can get this PR merged. Let me know if you have any issues with this and need me to take care of it. Thanks!

**Comment by Basssiiie** [comment]
@cormacpayne `package-lock.json` has been updated.

**Comment by cormacpayne** [comment]
@Basssiiie Hmm for some reason, the pipelines aren't picking up the changes, no matter how many times I rebase against `master`.

I have a PR that I'm going to open in our [RC task repository](https://github.com/azure/container-apps-deploy-pipelines-task) that will include this change (along with a few other things), so when I bring those changes back into this stable task repository, I'll include these changes (if the PR hasn't been merged) and make sure that you get the development credit there if that's OK with you.

**Comment by Basssiiie** [comment]
@cormacpayne ah too bad it's not working out. But yes it's okay with me to merge it via the RC task. :) 

A side note is that I originally made the PR here [per recommendation by the readme.md on the RC task's repo](https://github.com/Azure/container-apps-deploy-pipelines-task#contributing). 

> [...] however, we advise that any changes made to the `AzureContainerAppsRC` task be made instead to the [`AzureContainerApps` task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureContainerAppsV0)

Maybe it's an idea to update that if this flow is having issues?

**Comment by cormacpayne** [comment]
@Basssiiie That's a good callout -- I'm hoping this is just a one-off issue for users looking to make changes to the task in this repository, but if it occurs again with another user, I'll update the documentation accordingly and port any changes made by customers in the RC task over to this task when it's released out-of-the-box with Azure Pipelines.

**Comment by cormacpayne** [comment]
I'm going to close this pull request since these changes were integrated into the `AzureContainerApps@1` task as a part of [this pull request](https://github.com/microsoft/azure-pipelines-tasks/pull/18055). Please feel free to let me know if you have any additional questions or comments!

**Pull request closed without merging**
