### PR TITLE
Allow overriding existing files in ExtractFiles task.

### PR DESCRIPTION
**Pull request by stephenmichaelf**
This change adds an optional input to override existing files when using the ExtractFiles task. The input will default to true as that is likely what the user wants. This will change the default behavior of the task.

[Related PR 1](https://github.com/microsoft/azure-pipelines-tasks/pull/6760)
[Related PR 2](https://github.com/microsoft/azure-pipelines-tasks/pull/11594)
[Related Issue 1](https://github.com/microsoft/azure-pipelines-tasks/issues/11082)
[Related Issue 2](https://github.com/microsoft/azure-pipelines-tasks/issues/11593)

### CODE REVIEW

**Comment by damccorm** [comment]
https://github.com/microsoft/azure-pipelines-tasks/issues/7243 is also related

**Comment by damccorm** [comment]
Tests are also still failing here

**Comment by PaulGauthier** [comment]
@stephenmichaelf Has this been abandoned? We really would like to see this functionality get merged. It is causing us to have to work around the task instead of use it. Thanks for your help.

**Comment by farlop** [comment]
Any idea of the progress of this PR?

**Pull request closed without merging**
