### PR TITLE
revoke code fix done for cosmetic API calls

### PR DESCRIPTION
**Pull request by v-nagarajku**
**Task name**: AzureRmWebAppDeploymentV4

**Description**: Revoke code fix changes done for cosmetic API calls handling

**Documentation changes required:** N

**Added unit tests:** (Y/N) N

**Attached related issue:** N
**Checklist**:
- [X ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ X] Checked that applied changes work as expected

### CODE REVIEW

**Comment by ozanovus** [comment]
This PR is related to old PR #16868 .

**Comment by ozanovus** [comment]
@v-nagarajku there was also a change in "`azurermwebappdeployment.ts`" file. Did you check it?

**Comment by v-nagarajku** [comment]
> @v-nagarajku there was also a change in "`azurermwebappdeployment.ts`" file. Did you check it?

No this change is not by me.

**Review by ozanovus — APPROVED** [review]
1. This change is not reverted but @v-nagarajku  said that it was required.

https://github.com/microsoft/azure-pipelines-tasks/pull/16868/files#diff-43df8eccd1d002e8a9aa7e15c4de987b6729a5889bd07f1d5c57f4c311cb657e

2. Old issue which is solved with PR https://github.com/microsoft/azure-pipelines-tasks/pull/16868 might be reappeared ; but to prevent blocking , @v-nagarajku reverting this change.

**Pull request merged**
