### PR TITLE
Updated PTRV2 task to version 2.210.0 

### PR DESCRIPTION
**Pull request by dogirala**
**Task name**: PublishTestResultsV2

**Description**: 

Updated PTRV2 task version from 2.203.0 version 2.210.0
Build: https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=17913981&view=results

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by triptijain2112** [comment]
@rasunkar Please approve and merge this PR, I have reviewed it and looks good to me!
My write access got revoked because of some password change policy

**Review by rasunkar — APPROVED** [review]

**Pull request merged**
