### PR TITLE
AzurePowershellV5: Suppress output from Az-functions

### PR DESCRIPTION
**Pull request by mortenlerudjordet**
**Task name**: AzurePowershellV5, Common/VstsAzureHelpers_

**Description**: 
- Suppress output from Connect-AzAccount & Set-AzContext
- Fix output display for hashtable used in write-host (helper function)

**Documentation changes required:** (Y/N) No

**Added unit tests:** (Y/N) No

**Attached related issue:** (Y/N) #19672 

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by MrNewgarden — APPROVED** [review]

**Comment by LeftTwixWand** [comment]
Hello @mortenlerudjordet, thank you so much for this contribution.
The PR looks good, but before it can be merged, please bump the task version to `5.237.8` the patch version `7` is reserved.

Also, you need to do the next steps:
Install node.js v10.
Clone the repository and call the next commands from your CLI:
```
npm i
node make.js build --task AzurePowerShellV5
```

You would see a bunch of generated files in the `git status`.
Please, add them to this PR - they are required.

**Comment by mortenlerudjordet** [comment]
@v-mohithgc or @LeftTwixWand, please run the pipeline again with the new changes added to the PR.

**Comment by mortenlerudjordet** [comment]
@LeftTwixWand ; I have merged in the changes done on master,
Do I need to bump the patch number to 9 before this can be merged in as 8 now is taken?

**Comment by mortenlerudjordet** [comment]
@vincentdass : as code owner for Common/VstsAzureHelpers_ can you review the change I have proposed?

**Comment by v-mohithgc** [comment]
Hi @mortenlerudjordet , the PR checks are expected to fail as the task version isnt bumped.
please increase the minor version of this task to 238 and patch to 0, in task.json file and then run the build command (node make.js build --task AzurePowerShellV5) and then commit the changes.

**Comment by mortenlerudjordet** [comment]
@v-mohithgc : Will I have to bump version on all these other tasks also?

Tried to run build on all in the error msg from the pipeline, but not all task in the list gets files under _generated after build complete.
Only see files generated for:
AzureFileCopyV2
AzureFileCopyV3
AzureFileCopyV4
AzureFileCopyV5
AzureFileCopyV6
AzurePowerShellV4

For the other tasks seems like the reason from the build logs is this:
`Unable to find package.json file for AzureCloudPowerShellDeploymentV2 in _generated folder or Tasks folder, using default node 10.`

See pipelines are failing on:
```
The following tasks should have their versions bumped due to changes in common: AzureCloudPowerShellDeploymentV1,AzureCloudPowerShellDeploymentV2,AzureFileCopyV1,AzureFileCopyV2,AzureFileCopyV3,AzureFileCopyV4,AzureFileCopyV5,AzureFileCopyV6,AzurePowerShellV2,AzurePowerShellV3,AzurePowerShellV4,SqlAzureDacpacDeploymentV1
```

**Comment by mortenlerudjordet** [comment]
I will remove the change to Common/VstsAzureHelpers_ and create a new PR without to make it simpler to approve

**Pull request closed without merging**
