### PR TITLE
Updated VsTestV2 task to version 2.202.0

### PR DESCRIPTION
**Pull request by triptijain2112**
Updated TestAgent version from 2.198.0 to 2.202.0
Build: https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=16970602&view=results

### CODE REVIEW

**Review by abhadauria1 — APPROVED** [review]
LGTM

**Review by rasunkar — APPROVED** [review]
Approved

**Review by rasunkar — APPROVED** [review]

**Review by anshii03 — APPROVED** [review]

**Review by nadesu — APPROVED** [review]

**Comment by tovVAar** [comment]
Hello @triptijain2112 , this change has affected to some internal VS pipelines, is there a ms alias we could email about this?

**Comment by tovVAar** [comment]
We are having issues on the VsTest task, with exceptions like thee following one:

File name: 'Microsoft.Azure.Storage.Common, Version=11.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<_executeWithRetry>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.<UploadInternalAsync>d__19.MoveNext()

@rasunkar your email got censored, could you just post the ldap/alias without the _@ domain . com_ ?

**Pull request merged**
