### PR TITLE
Add ability to validate Azure Powershell task's script file's signature

### PR DESCRIPTION
**Pull request by nich-arq**
**Task name**: Azure Powershell v3, v4 and v5

**Description**: Add checkbox to validate authenticode signature if a path to a file is specified in the task. Fail if signature is not valid.

**Documentation changes required:**  Yes (add info regarding the new UI element "validateScriptSignature")

**Added unit tests:** No

**Attached related issue:** N/A

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Review by PavloAndriiesh — APPROVED** [review]

**Comment by nich-arq** [comment]
@rvairavelu can you help approve the version number change? Merge is blocked because of it.

**Review by rvairavelu — APPROVED** [review]

**Pull request merged**
