### PR TITLE
Users/jysin/manual val preview release

### PR DESCRIPTION
**Pull request by Josh-01**
**Task name**: ManualvalidationV0

**Description**: Bumped up minor version 

**Documentation changes required:** (Y/N) Y

**Added unit tests:** (Y/N) N
**Attached related issue:** (Y/N) N
**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by radujipa** [comment]
@Josh-01 @rohit-batra Thank you for the preview release of this task. It looks really interesting for my current use case. 

I've noticed that when using `ManualIntervention` from a YAML pipeline (server job), the following error is shown:
```
Task execution section of task definition for ID: bcb64569-d51a-4af0-9c01-ea5d05b3b622 is either missing or not valid.
```
But this works as intended from a Classic Release pipeline.

Similarly, when using `ManualValidation` from a Classic Release pipeline the following error is given:
```
Task execution section of task definition for ID: 2003ad3a-104a-451a-9238-60474ab294e6 is either missing or not valid.
```
But this runs from a YAML pipeline.

(Hopefully I'm not doing something silly in either cases, e.g. `emailRecipients` or `notifyUsers` values)

A few quick questions on this:
1. Is this the intended behaviour? `ManualIntervention` in Release and `ManualValidation` in YAML?
2. If so, does this task require additional configuration to trigger the approval UI dialogs or is it a known issue given the task simply succeeds without any messages?

**Comment by rohit-batra** [comment]
> @Josh-01 @rohit-batra Thank you for the preview release of this task. It looks really interesting for my current use case.
> 
> I've noticed that when using `ManualIntervention` from a YAML pipeline (server job), the following error is shown:
> 
> ```
> Task execution section of task definition for ID: bcb64569-d51a-4af0-9c01-ea5d05b3b622 is either missing or not valid.
> ```
> 
> But this works as intended from a Classic Release pipeline.
> 
> Similarly, when using `ManualValidation` from a Classic Release pipeline the following error is given:
> 
> ```
> Task execution section of task definition for ID: 2003ad3a-104a-451a-9238-60474ab294e6 is either missing or not valid.
> ```
> 
> But this runs from a YAML pipeline.
> 
> (Hopefully I'm not doing something silly in either cases, e.g. `emailRecipients` or `notifyUsers` values)
> 
> A few quick questions on this:
> 
> 1. Is this the intended behaviour? `ManualIntervention` in Release and `ManualValidation` in YAML?
> 2. If so, does this task require additional configuration to trigger the approval UI dialogs or is it a known issue given the task simply succeeds without any messages?

Thanks @radujipa  for Trying things out. 
Regarding 1. Yes Manual intervention is for Classic releases and ManualValidation is for YAML. 
for 2. I am not sure if backend is deployed yet and it is behind FF. @Josh-01 can you please confirm once and address what Radu is saying 

cc @raiyanalam  PM owner  for any more clarification. 
cc @ammohant , our Lead , JFYI

**Comment by radujipa** [comment]
@rohit-batra Really appreciate the speedy follow up here.

Also, super excited for the new task - a solid addition for sure! Will keep experimenting with it to see if I can get the UI to trigger, but if you've got more info on this would really appreciate the input.

**Comment by Josh-01** [comment]
Hi @radujipa,
Reg. 2 - the task is now in preview mode and the backend is behind a feature flag which we would be enabling only for specific accounts - hence it is not working correctly for you yet.
Kindly connect with our PM @raiyanalam to understand if the feature can be enabled for your account. 
Thanks

**Comment by radujipa** [comment]
Hi @Josh-01, thank you for the clarification there, really appreciate it. I'll follow up with your PM offline :)

**Comment by mbellas-tkxs** [comment]
Hey, looking forward to this. Is there an ETA on when it will be out of preview?

**Comment by raiyanalam** [comment]
Hi @mbellas-tkxs : The tentative plan is to roll this out early October. 

FYI: @ammohant

**Comment by mbellas-tkxs** [comment]
Hey, just checking in. I don't see it in https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-176-update so I'm assuming it got bumped to late October? Is it possible to get the feature flag enabled for my account before then?

**Comment by rohit-batra** [comment]
cc @Josh-01 , @raiyanalam to help @mbellas-tkxs here

**Comment by radujipa** [comment]
Hello everyone. Wondering what is the current timeline to having this task available for everyone?

**Comment by raiyanalam** [comment]
@radujipa, @mbellas-tkxs ,
   Apologies for the delay. This go out of my radar. Can you give your ADO organization name (eg. dev.azure.com/<org_name>) so that we can enable for your account

**Comment by mbellas-tkxs** [comment]
Great, thanks. My org is dev.azure.com/tkxs

**Comment by raiyanalam** [comment]
@radujipa, @mbellas-tkxs ,
   Also please email me at moala [at] microsoft [dot] com. I can send in some quick steps for getting started.

**Pull request merged**
