### PR TITLE
contribute.md: add info on node and unzip prereqs

### PR DESCRIPTION
**Pull request by fowl2**
some things I noticed trying to make my first PR :)

### CODE REVIEW

**Comment by fowl2** [comment]
@EzzhevNikita you've approved PRs in these docs before, hope I'm not out of line asking if you could take a look at this :)

**Comment by EzzhevNikita** [comment]
@fowl2 Thanks for your contribution, we will take a look at your PR.

**Comment by fowl2** [comment]
:(

**Pull request closed without merging**
