### PR TITLE
Changed "WEBSITE_RUN_FROM_PACKAGE true" to "WEBSITE_RUN_FROM_PACKAGE 1"

### PR DESCRIPTION
**Pull request by CodingIsBliss**
**Task name**: Deploy task

**Description**: As per the documentation for the setting WEBSITE_RUN_FROM_PACKAGE from https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package  the value needs to be 1 to be enabled. the value 'true' does not work.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by FinVamp1** [comment]
As discussed offline.

I have apps that have been deployed with WEBSITE_RUN_FOM_PACKAGE = true and it still does work.

I do agree with you that we should have this been consistent with the documentation.

If you didn’t mind however I would like to include this change in the V2 version of the task which I am hoping to merge soon.

[azure-pipelines-tasks/Tasks/AzureFunctionAppV2 at users/finvamp1/FunctionsAppv2 · microsoft/azure-pipelines-tasks (github.com)](https://github.com/microsoft/azure-pipelines-tasks/tree/users/finvamp1/FunctionsAppv2/Tasks/AzureFunctionAppV2)

**Comment by CodingIsBliss** [comment]
> As discussed offline.
> 
> I have apps that have been deployed with WEBSITE_RUN_FOM_PACKAGE = true and it still does work.
> 
> I do agree with you that we should have this been consistent with the documentation.
> 
> If you didn’t mind however I would like to include this change in the V2 version of the task which I am hoping to merge soon.
> 
> [azure-pipelines-tasks/Tasks/AzureFunctionAppV2 at users/finvamp1/FunctionsAppv2 · microsoft/azure-pipelines-tasks (github.com)](https://github.com/microsoft/azure-pipelines-tasks/tree/users/finvamp1/FunctionsAppv2/Tasks/AzureFunctionAppV2)

Hi @FinVamp1 ,

The behavior of how the app is being run is quite different when the value of WEBSITE_RUN_FOM_PACKAGE is '1' vs when it is not. Nevertheless, the app will run!

When it is not '1' zipdeploy will basically extract the zip file into the wwwroot folder. When the value is '1' the zipfile is not extracted into the wwwroot folder but rather mounted to wwwroot folder at runtime and the wwwroot will be readonly.

I would highly you suggest keeping this value as 1.

Thanks,
Sarath

**Comment by tomaeda** [comment]
Hello, @CodingIsBliss and @FinVamp1 
Changing WEBSITE_RUN_FROM_PACKAGE to true causes an error and some users have their deployment blocked.
I think this PR may be able to resolve the issue, please can you see #16005 and #15983 ?

**Review by FinVamp1 — APPROVED** [review]
Looks good to me

**Comment by awarberg** [comment]
We are experiencing issues with Elastic Premium Plan after this switch from expanded/wwwroot zip deploy to run from package. SyncTriggers sometimes fails to run and we now need to 1) notice that this happened (in the Activity Log of each Function App) and 2) manually run SyncTriggers per affected Function App. 

The wwwroot zip deploy automatically sync's trigger information and we suspect this is why we didn't notice this problem until now. 

Is it possible to override the deployment strategy for Elastic Premium Plan so that it uses the wwwroot zip deploy strategy for before this change?

**Pull request merged**
