### PR TITLE
Replaced request with typed-rest-client package

### PR DESCRIPTION
**Pull request by AndreyIvanov42**
**Task name**: DownloadGitHubNpmPackageV1

**Description**: Replaced request with typed-rest-client package. Request is deprecated and contains a critical vulnerability.

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by AndreyIvanov42** [comment]
Hi @v-nmursapall,
Could you review and test these changes, please?

**Comment by v-nmursapall** [comment]
@AndreyIvanov42  - The changes look ok, I will test them and get back to you. But i do not have write access to this repository, so it will have to be approved by Harshini K S.

**Review by harshiniks — APPROVED** [review]
Approving on behalf of @v-nmursapall

**Review by anatolybolshakov — APPROVED** [review]

**Review by mmrazik — APPROVED** [review]

**Review by mpodriezov — APPROVED** [review]

**Comment by AndreyIvanov42** [comment]
@v-nmursapall Have you been able to test the changes?

**Pull request merged**
