### PR TITLE
Vulnerability fix for DuffleInstallerV0

### PR DESCRIPTION
**Pull request by v-schhabra**
**Task name**: DuffleInstallerV0

**Description**: 

**Documentation changes required:** (Y/N) 

**Added unit tests:** (Y/N) 

**Attached related issue:** (Y/N) https://dev.azure.com/mseng/PipelineTools/_componentGovernance/184/alert/79428?typeId=12858
**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected
- [x] node make.js build --task DuffleInstallerV0
- [x] node make.js test --task DuffleInstallerV0

### CODE REVIEW

**Review by v-mohithgc — APPROVED** [review]
LGTM

**Review by rvairavelu — APPROVED** [review]
approved

**Comment by rohit-batra** [comment]
I am assuming added dependencies in package lock file have been verified, right ? if not please do it once ,

**Comment by v-schhabra** [comment]
Yes, @rohit-batra dependencies in package lock file are verified.

**Pull request merged**
