### PR TITLE
[GradleV2] Change `java` demand to `JAVA_HOME`

### PR DESCRIPTION
**Pull request by DaniilShmelev**
**Task name**: Gradle

**Description**: This task does not require `java` demand to be satisfied: just having `JAVA_HOME` env variable would suffice.

**Documentation changes required:** (Y/N) No

**Added unit tests:** (Y/N) No

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by DenisRumyantsev — APPROVED** [review]
Tested it manually, all works as expected, thanks!

**Review by EzzhevNikita — COMMENTED** [review]
As I see there is a flow when this task could install JDK and set up _JAVA_HOME_ variable by itself. In theory, it means that there is a situation when the agent won't have _JAVA_HOME_ before task execution and this change could break such customers.

**Comment by DaniilShmelev** [comment]
@EzzhevNikita this is true, but if we remove all demands then gradle jobs may start running on machines with no java installed, which could be even more breaking.
My hope here is that if `java` demand is satisfied it means `JAVA_HOME` is also set. The only case when the issue you described could happen is if the user installed java and then manually unset `JAVA_HOME`.
Not sure what to do here, need to discuss this internally.

**Comment by DaniilShmelev** [comment]
Decided to go with the major task version bump instead

**Pull request closed without merging**
