### PR TITLE
Resurrect deprecated SourceFolder parameter

### PR DESCRIPTION
**Pull request by m-akinc**
**Task name**: PublishSymbolsV2

**Description**: The PublishSymbols task assumes that the source files referenced by the pdb are rooted under Build.SourcesDirectory. It does not index source files unless they are under that directory. If a user synced and built from a different path, they will not be able to use this task to index their source. This change addresses that issue by introducing a new optional parameter to the task that defines the source directory. If unspecified, it defaults to using Build.SourcesDirectory (the current behavior). When I began the process of introducing the parameter, I found logic related to an old, deprecated parameter named SourceFolder. This seems to be exactly what I want to introduce, so I reused that name and removed the logic that warned of the parameter being deprecated.

**Documentation changes required:** (Y/N) Yes. Label and help strings for the new task parameter are needed.

**Added unit tests:** (Y/N) No new unit tests were created.

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by m-akinc** [comment]
@ericsciple I'm wanting to reintroduce a task parameter that you seem to have deprecated way back in 2015:
https://github.com/microsoft/azure-pipelines-tasks/pull/441
Any chance you can tell me why it was deprecated, and/or whether there's a problem with bringing it back?

**Comment by m-akinc** [comment]
Also, I'm not sure how I can verify that this works the way I expect. Is there a reasonable way?

**Comment by m-akinc** [comment]
> @ericsciple I'm wanting to reintroduce a task parameter that you seem to have deprecated way back in 2015:
> #441
> Any chance you can tell me why it was deprecated, and/or whether there's a problem with bringing it back?

@ericsciple bump... I really don't want this PR to languish and die.

**Comment by m-akinc** [comment]
@fadnavistanmay I'd really like to get this in before the next scheduled deployment, if possible. Can you take a look?

**Comment by MarkIannucci** [comment]
@m-akinc , I noticed that the [contributing](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md) file in this repo suggests adding a label to your PR which matches the category in the `task.json` file:

https://github.com/microsoft/azure-pipelines-tasks/blob/4e6e65efdaf560fcb0c3d3e3db425e4bcb3e22be/Tasks/PublishSymbolsV2/task.json#L8

Perhaps that may help move this along?  I tried to label your PR, but unfortunately I cannot.  I mention this as a member of the community who was excited to see #12334 get completed after languishing for 7 months.

**Comment by m-akinc** [comment]
> @m-akinc , I noticed that the [contributing](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md) file in this repo suggests adding a label to your PR which matches the category in the `task.json` file:
> 
> https://github.com/microsoft/azure-pipelines-tasks/blob/4e6e65efdaf560fcb0c3d3e3db425e4bcb3e22be/Tasks/PublishSymbolsV2/task.json#L8
> 
> Perhaps that may help move this along? I tried to label your PR, but unfortunately I cannot. I mention this as a member of the community who was excited to see #12334 get completed after languishing for 7 months.

I saw that as well, but somehow, I cannot see any way to add a label. I'm not sure if those UI elements are removed due to not having permission to add a label, or maybe I'm just blind/crazy.

**Comment by johnterickson** [comment]
Have you looked at https://github.com/dotnet/sourcelink/blob/master/README.md? You can do the source indexing as part of where ever the build takes place and then set this task to symbol publish, but not source index.

**Comment by johnterickson** [comment]
@m-akinc I appreciate your efforts here in this PR, but this functionality was intentionally deprecated because it caused functional and compatibility issues.

That said, I do think you should be unblocked by SourceLink (see my above comment). That's the more "modern" approach.

I know it can be frustrating to have a PR rejected - trust me I've been there!

**Comment by m-akinc** [comment]
It looks like SourceLink provides limited support (e.g. no embedding repo information) for native C++ projects. I don't think it's going to satisfy our use case.

**Pull request closed without merging**
