### PR TITLE
Fix #15250: Use whole numbers for TrafficSplit weight

### LINKED ISSUE #15250: KubernetesManifest canary deployment generates invalid TrafficSplit resource
## Required Information

*Type*: Bug

**Enter Task Name**: `KubernetesManifest@0`

## Environment

- Server - Azure Pipelines
- Agent - Both hosted and private

## Issue Description

When the `KubernetesManifest@0` task is used to do a canary deployment, it makes use of SMI (service mesh interface) for doing the `TrafficSplit` to manage which traffic goes to the stable vs. canary version of the service. As part of that, it [automatically goes to get the SMI custom resource version](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/KubernetesManifestV0/src/utils/utilities.ts#L150) currently deployed so it can generate its manifest.

[The manifest it generates uses `XXXXm` format weights](https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/KubernetesManifestV0/src/utils/SMICanaryDeploymentHelper.ts#L213). That is, you might get a manifest like this:

```yaml
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: my-service-azure-pipelines-rollout
  namespace: my-ns
spec:
  backends:
  - service: my-service-stable
    weight: 1000m
  - service: my-service-baseline
    weight: 0m
  - service: my-service-canary
    weight: 0m
  service: my-service
```

Unfortunately, while the `XXXXm` format [is noted in the very first version of the `TrafficSplit` spec](https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-split/v1alpha1/traffic-split.md), as of [version 2 of the spec](https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-split/v1alpha2/traffic-split.md) it was removed. The official "SMI SDK for Go" has a detailed custom resource definition [and it validates the weight as a number](https://github.com/servicemeshinterface/smi-sdk-go/blob/a143f8bc96eccdf5fc8a66d0c1622591104c77e0/crds/split.yaml#L148). Further, the [current SMI adapter for Istio uses that SDK](https://github.com/servicemeshinterface/smi-adapter-istio/blob/540c15f49cd800ef32f49751aa89b4464a321203/pkg/controller/trafficsplit/trafficsplit_controller.go#L8) so it's entirely failing to read and validate `TrafficSplit` resources generated during canary.

**The simplest solution is to stop post-fixing `m` on the weights.** The weights being whole/relative numbers or percentages is compatible with all versions of the spec. A correct `TrafficSplit` should look like this:

```yaml
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: my-service-azure-pipelines-rollout
  namespace: my-ns
spec:
  backends:
  - service: my-service-stable
    weight: 1000
  - service: my-service-baseline
    weight: 0
  - service: my-service-canary
    weight: 0
  service: my-service
```

### Task logs

The task does not generate logs indicating any issue. It's the handling of the SMI, particularly in Istio, that causes the issue.

### Error logs

The SMI Adapter for Istio generates logs like this to reflect that issue:

```text
E0902 14:45:23.035319       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha2.TrafficSplit: v1alpha2.TrafficSplitList.Items: []v1alpha2.TrafficSplit: v1alpha2.TrafficSplit.Spec: v1alpha2.TrafficSplitSpec.Backends: []v1alpha2.TrafficSplitBackend: v1alpha2.TrafficSplitBackend.Weight: readUint64: unexpected character: �, error found in #10 byte of ...|"weight":"1000m"},{"|..., bigger context ...|":[{"service":"accounts-service-stable","weight":"1000m"},{"service":"accounts-service-baseline","we|...
E0902 14:45:24.038301       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha2.TrafficSplit: v1alpha2.TrafficSplitList.Items: []v1alpha2.TrafficSplit: v1alpha2.TrafficSplit.Spec: v1alpha2.TrafficSplitSpec.Backends: []v1alpha2.TrafficSplitBackend: v1alpha2.TrafficSplitBackend.Weight: readUint64: unexpected character: �, error found in #10 byte of ...|"weight":"1000m"},{"|..., bigger context ...|":[{"service":"products-service-stable","weight":"1000m"},{"service":"products-service-baseline","we|...
E0902 14:45:25.042071       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha2.TrafficSplit: v1alpha2.TrafficSplitList.Items: []v1alpha2.TrafficSplit: v1alpha2.TrafficSplit.Spec: v1alpha2.TrafficSplitSpec.Backends: []v1alpha2.TrafficSplitBackend: v1alpha2.TrafficSplitBackend.Weight: readUint64: unexpected character: �, error found in #10 byte of ...|"weight":"1000m"},{"|..., bigger context ...|":[{"service":"accounts-service-stable","weight":"1000m"},{"service":"accounts-service-baseline","we|...
```

### PR DESCRIPTION
**Pull request by tillig**
**Task name**: KubernetesManifestV0

**Description**: v1alpha1 of the SMI spec allows both whole numbers (1000) and XXXm format numbers. All versions after v1alpha1 only support whole numbers for the weight. This change makes the generated object compatible with all versions of the spec.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** #15250

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Comment by tillig** [comment]
I'm unable to assign a label [as requested by the Contributing doc](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md#pr-submission) because I don't have sufficient permissions. It also appears GitHub has automatically chosen a reviewer, so I'm not tagging anyone new.

**Comment by tillig** [comment]
It'd be cool to hear back from someone about this before I go through and resolve the conflicts, otherwise I'll just keep resolving over and over with no value. Thanks!

**Comment by MassimoScattarella** [comment]
Hi, I confirm the problem, in the changelog files I would also have changed from `"weight": "%s"` to `"weight": %d` what do you say?
In the meantime waiting for the push is there a way to fix the problem locally?
Thanks

**Comment by tillig** [comment]
No way I'm aware of to work around it. I ended up forking the `KubernetesManifestV0` task and fixing it in my own copy privately deployed to my build agents. I also ended up [building my own Kubernetes Operator](https://github.com/buehler/dotnet-operator-sdk) for Istio SMI because the [current one is super stale](https://github.com/servicemeshinterface/smi-adapter-istio) and the [new one is not making very much progress](https://github.com/servicemeshinterface/istio-smi-controller). Unfortunately, my custom controller is not open source and I'm not allowed to share it.

**Pull request closed without merging**
