### PR TITLE
Added changes from another PR - UsePythonVersionV0

### PR DESCRIPTION
**Pull request by anatolybolshakov**
**Task name**: UsePythonVersionV0

**Description**: added changes from [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16031), fixed minor issue with warning for exact version specified (showing warning for versions like 3.2.0 since it also has patch version specified, which is not recommended).

**Documentation changes required:** Y

**Added unit tests:** added tests

**Attached related issue:** https://github.com/microsoft/azure-pipelines-tasks/issues/13319

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected - tested with downloading from registry

### CODE REVIEW

**Comment by anatolybolshakov** [comment]
@mmrazik could you please take a look?

**Review by mmrazik — APPROVED** [review]

**Review by SvetlanaMaliugina — APPROVED** [review]
Checked these changes in following cases of ```versionSpec``` input:
- use 3.x
- use 3.7
- use pypy3
- use 2.7.18

All finished successfully.
Looks good for me.

**Pull request merged**
