### PR TITLE
Fix warning issue for AzureFunctionAppV2

### PR DESCRIPTION
**Pull request by v-mohithgc**
**Task name**: AzureFunctionAppV2

**Description**: Fixed warning issues

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by v-mohithgc** [comment]
Before:
image

image


After: 

image


image

**Review by manolerazvan — APPROVED** [review]

**Review by rvairavelu — APPROVED** [review]

**Review by FinVamp1 — APPROVED** [review]
Looks good thank you.,

**Pull request merged**
