### PR TITLE
Update PublishSymbolsV2 task to allow customizing the symbol request name

### PR DESCRIPTION
**Pull request by scottxsu**
**Task name**: PublishSymbolsV2

**Description**: The SymbolsArtifactName parameter can now be used to change the name of the symbol request when uploading to an Azure Artifacts symbol server (SymbolServerType = TeamServices).

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:**

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected. I published the task as a test extension into my own Azure DevOps organization and used it to publish symbols. I tested out leaving the default SymbolsArtifactName value alone, making it an empty parameter, and putting in a non-default value. Only putting in a non-default value caused the symbol request name to be changed from its default.

### CODE REVIEW

**Review by carl-tanner — APPROVED** [review]

**Comment by mcooley** [comment]
@scottxsu @carl-tanner FYI, this change temporarily broke our pipelines. Several pipelines in our organization were using the same SymbolsArtifactName in their pipelines, and so after this change was deployed symbol requests started colliding between pipelines.

I would suggest that the documentation for this task should be updated to emphasize that if you use a custom value for SymbolsArtifactName, it needs to be unique across an organization.

**Pull request merged**
