### PR TITLE
allow passwords starting with a hyphen

### PR DESCRIPTION
**Pull request by mrdavidkendall**

### CODE REVIEW

**Comment by mrdavidkendall** [comment]
https://github.com/Azure/azure-cli/issues/12105

**Comment by issacnitin** [comment]
@mrdavidkendall Thanks a lot for the PR! Looks good to me. Please update your branch, update patch versions in task.json and task.loc.json.

Also it'd be good if you can update the same for AzureCLIV1 😄 

@bishal-pdMSFT Any other suggestions?

**Comment by mrdavidkendall** [comment]
@issacnitin I brought my branch up to date, made corresponding changes to AzureCLIV1 and updated the patch versions per your request.  Thank you for the review.

**Comment by issacnitin** [comment]
@mrdavidkendall Good work! Thanks a lot. @bishal-pdMSFT Please review

**Pull request merged**
