### PR TITLE
Fixing the casing issue with WebAppKind for deployment to app service windows container via YAML devops workflow

### PR DESCRIPTION
**Pull request by SatishRanjan**
… windows container via YAML devops workflow

**Task name**: AzureRmWebAppDeploymentV4

**Description**: Fixing the casing issue with WebAppKind for deployment to app service windows container via YAML devops workflow

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) Tracked via internal Microsoft issue

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by SatishRanjan** [comment]
Hi @silviuandrica - created the PR to fix the casing issue for webAppKind. Looks like I don't have permission on this repo to add the reviewer. Would appreciate if you can take a look and review. This PR fixes the casing issue so that we get unblocked on our side.

**Review by jvano — APPROVED** [review]
Looks good! :shipit:

**Comment by SatishRanjan** [comment]
@geekzter - Hi Eric, could you please approve and merge this PR so that we get unblocked to deploy to windows container?

**Review by kirill-ivlev — APPROVED** [review]

**Comment by SatishRanjan** [comment]
Thanks @kirill-ivlev for approving the changes. I don't have write access to the repo, could you please merge these changes?

**Comment by SatishRanjan** [comment]
Hi @mmrazik - could you please get this PR merged, it's a fix to an earlier PR approved by you. Appreciate your help!

https://github.com/microsoft/azure-pipelines-tasks/pull/16367

**Comment by SatishRanjan** [comment]
> Hi @SatishRanjan could you please bump task minor version to the current sprint (232)?

Thanks @kirill-ivlev, yes updated the version to 232. Looking forward to getting this merged.

**Review by kirill-ivlev — APPROVED** [review]

**Comment by DmitriiBobreshev** [comment]
Hi @SatishRanjan, could you please build the task with ```node make.js build --task AzureRmWebAppDeploymentV4``` command to regenerate node16 version, as an output you should see that files inside [_generated/AzureRmWebAppDeploymentV4](https://github.com/microsoft/azure-pipelines-tasks/blob/master/_generated/AzureRmWebAppDeploymentV4/task.json) and [_generated/AzureRmWebAppDeploymentV4_Node16](https://github.com/microsoft/azure-pipelines-tasks/blob/master/_generated/AzureRmWebAppDeploymentV4_Node16/task.json) are changed as well?

**Review by kirill-ivlev — APPROVED** [review]

**Review by DmitriiBobreshev — APPROVED** [review]

**Review by DergachevE — APPROVED** [review]

**Pull request merged**
