### PR TITLE
Updated TestAgent version from 2.205.0 to 2.210.0

### PR DESCRIPTION
**Pull request by vinayakmsft**
**Task name**: Vstest task V2 

**Description**: Had to update the minor version of the VstestV2 task in the task.json and task.loc.json . Also, had to update the  build number in https://testexecution.blob.core.windows.net/testexecution/ {build number}/TestAgent.zip . This is required for the fix of a bug that would go the AzureDevops2022 Rc2 release.
**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1924995

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by triptijain2112** [comment]
Changes look fine, @vinayakmsft please update PR title, follow the wiki to get PR title and description details- https://mseng.visualstudio.com/AzureDevOps/_wiki/wikis/AzureDevOps.wiki/28331/VsTest-V2-or-PTR-V2-Task-update-Process

**Comment by vinayakmsft** [comment]
> Changes look fine, @vinayakmsft please update PR title, follow the wiki to get PR title and description details- https://mseng.visualstudio.com/AzureDevOps/_wiki/wikis/AzureDevOps.wiki/28331/VsTest-V2-or-PTR-V2-Task-update-Process

Updated

**Review by abhadauria1 — APPROVED** [review]

**Review by triptijain2112 — APPROVED** [review]

**Comment by yirkha** [comment]
Hi @vinayakmsft & @triptijain2112, seems like this change has broken our pipeline.
DtaExecutionHost puts test parameters into the list of test names to rerun now and it VSTest does not like it.
See https://dev.azure.com/skype/SCC/_workitems/edit/3003155
Any suggestions, like use VSTest@3 instead of VSTest@2, or update VS on the build node, or similar?

**Comment by vinayakmsft** [comment]
@yirkha Please try updating the agent for Vstest.

**Comment by vinayakmsft** [comment]
I have verified in my ADO account that Vstest 2.210.0 is working fine and is not breaking the pipeline. Please update your agent

**Comment by yirkha** [comment]
@vinayakmsft Thank you for your reply. Sorry for not describing the problem in more detail, here is a proper bug report: #16990

**Pull request merged**
