### PR TITLE
Upgrade InstallAppleCertificateV2 to NodeJS 16

### PR DESCRIPTION
**Pull request by DmitriiBobreshev**
**Task name**: InstallAppleCertificateV2

**Description**: 
- Bumped @types/node & azure-pipelines-task-lib
- Added node16 execution handler

**Documentation changes required:** N

**Added unit tests:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by Roman-Shchukin — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Review by vmapetr — APPROVED** [review]

**Review by wojgasior — APPROVED** [review]

**Comment by 1Siger1** [comment]
@DmitriiBobreshev from this Monday the InstallAppleCertificateV2 with version 2.212.0 is available on build agents and as result we started getting failed builds with this result:
image
Do you have any solution for that?

**Comment by DmitriiBobreshev** [comment]
@1Siger1, that's probably because now tasks are using node16 handler, if you have agent version 2.213 and upper you can use 
[AGENT_USE_NODE10](https://github.com/microsoft/azure-pipelines-agent/blob/releases/2.213.2/src/Agent.Sdk/Knob/AgentKnobs.cs#L134) [knob](https://github.com/microsoft/azure-pipelines-agent/blob/releases/2.213.2/src/Agent.Worker/Handlers/NodeHandler.cs#L193) like we're now using it for [rhe6 build](https://github.com/microsoft/azure-pipelines-agent/blob/master/.azure-pipelines/build-job.yml#L87), or you can try to add [continueOnError](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-control-options) option in task definition in yaml

**Comment by 1Siger1** [comment]
@DmitriiBobreshev I will try the option for agents with version 2.213. I think that currently we have this version. The second option can't be used as the error is not in the task itself. It is failing your post-job on which I do not have control. This task I special one. The task is placed in specific place in pipeline, but it also automatically, on start (pre) and one end (post), adds additional steps to which I can't add any parameters or change them in any way. Maybe you know how to change this behavior? Is there a way to not add this two, pre and post, steps?

**Comment by DmitriiBobreshev** [comment]
@1Siger1 [continueOnError](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-control-options) option working on pre and post job execution as well 
image
So you can add the option, in this case, it will generate some warning that the post-job got an error, but the pipeline successfully finished. 
Also as I see the problem happens in azure-pipelines-tasks-ios-signing-common package, which was bumped in [version 2.214](https://github.com/microsoft/azure-pipelines-tasks/commit/0307e307d2332377a35582ace6004ddf38cd54a3#diff-a699103e49af683d028003e88b91c98f6037bbfed281e5d35eff6353624ac1c6L23), so I think the problem should disappear after rolling out.

**Pull request merged**
