### PR TITLE
[ANTV1] Migrated to NodeJS 10

### PR DESCRIPTION
**Pull request by sdobrodeev**
**Task name**: ANTV1

**Description**: Migrated ANTV1 to Node 10 execution handler.

**Documentation changes required:** No

**Added unit tests:** Yes (migrated legacy tests)

**Attached related issue:** No

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by anatolybolshakov — APPROVED** [review]

**Review by DaniilShmelev — APPROVED** [review]

**Review by EzzhevNikita — CHANGES_REQUESTED** [review]
Could you please also remove Legacy tests for this task?

**Review by EzzhevNikita — APPROVED** [review]

**Comment by anatolybolshakov** [comment]
> Could you please also remove Legacy tests for this task?

Btw, since there's no tests for ant task at the moment - could we migrate legacy tests instead of just removing it? Please feel free to sync with @max-zaytsev who already did it in https://github.com/microsoft/azure-pipelines-tasks/pull/14116

**Comment by egor-bryzgalov** [comment]
@anatolybolshakov Unit tests have been migrated.

**Comment by anatolybolshakov** [comment]
> @anatolybolshakov Unit tests have been migrated.

Thanks! Could you please move it to separate PR - to make it easier to review?

**Comment by egor-bryzgalov** [comment]
@anatolybolshakov I've done it. Could you please take a look?

**Review by anatolybolshakov — APPROVED** [review]

**Review by EzzhevNikita — APPROVED** [review]

**Review by DaniilShmelev — APPROVED** [review]

**Pull request merged**
