### PR TITLE
Added append flag to allow publish files to existing symbol requests.

### PR DESCRIPTION
**Pull request by tracytangcuiyi**
**Task name**: PublishSymbolsV2

**Description**: Added append flag on symbol publish command to allow publishing files to existing symbol requests on retry

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** N
**Attached related issue:** Y. https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1931632

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

**Test**: Changed Symbol publish logic to test this feature. See the following abandoned PR for the record. https://dev.azure.com/mseng/AzureDevOps/_git/AzureDevOps/pullrequest/661000

### CODE REVIEW

**Review by fadnavistanmay — APPROVED** [review]

**Comment by fadnavistanmay** [comment]
\azp run

**Review by milee48 — APPROVED** [review]
[text.txt](https://github.com/microsoft/azure-pipelines-tasks/files/8516779/text.txt)

**Review by milee48 — COMMENTED** [review]
Tasks/PublishSymbolsV2/SymbolClientFunctions. Tasks/PublishSymbolsV2/SymbolClientFunctions.ps1

**Review by b-barthel — COMMENTED** [review]
shouldn't this change be made in symbol itself?  I'd expect if I ask for a global retry symbol would handle this behind the scenes.

**Pull request closed without merging**
