### PR TITLE
migrate NuGetInstallerV0 to Node10

### PR DESCRIPTION
**Pull request by AndreyIvanov42**
**Task name**: NuGetInstallerV0

**Description**: Migrated task to Node10

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by AndreyIvanov42** [comment]
@geekzter

**Review by anatolybolshakov — APPROVED** [review]

**Review by EzzhevNikita — APPROVED** [review]

**Comment by anatolybolshakov** [comment]
@AndreyIvanov42 could you please describe tested scenarios in more details - to make it easier for further testing for owning team?

**Comment by AndreyIvanov42** [comment]
A check with a simple test with a dummy project.

**Comment by AndreyIvanov42** [comment]
@phil-hodgson @aasim @satbai Could you please review and approve the PR if all is fine?

**Comment by mpodriezov** [comment]
Moving to https://github.com/microsoft/azure-pipelines-tasks/pull/16495

**Pull request closed without merging**
