### PR TITLE
Upgrade azure-arm-rest package in Azurefilecopyv6

### PR DESCRIPTION
**Pull request by Deekshitha981**
**Task name**: Azurefilecopyv6

**Description**: Upgrade azure-arm-rest package

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by manolerazvan — APPROVED** [review]

**Comment by Steve-clouds** [comment]
Hi folks @Deekshitha981 @manolerazvan , As a long-time user of this task (v5 especially), I'm bit concerned about this PR change, considering this task is extremely critical for us, especially with a series of high-priority releases coming up. (**haven't seen any integration tests for this task, even months after the release of the new version**)
Given the recent breakdown of this task and the growing backlog of unresolved issues within this repository, our confidence in moving forward is slightly shaken. The quality of recent commits, combined with pilling up of issues, is not aligned with the level of service we used to get from Microsoft over the years.
I sincerely hope Microsoft is planning to invest more on these area to avoid further outages.

**Pull request merged**
