### PR TITLE
Hotfix NpmAuhenticateV0 post-job issue

### PR DESCRIPTION
**Pull request by Roman-Shchukin**
**Task name**:  NpmAuhenticateV0

**Description**: 
The problem occurs when performing a Post-job if some previous task removed working directory of NpmAuthenticate task. The problem appeared after migrating to Node16. On Node10 it was a warning, on Node16 it became an exception.

**Changes**:
- Added the check for existing NpmAuthenticateTaskInput.WorkingFile
- Added the check for existing NPM_AUTHENTICATE_TEMP_DIRECTORY

**Documentation changes required:** N

**Added unit tests:** N

**Related issue**: https://github.com/microsoft/build-task-team/issues/4054

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by DmitriiBobreshev — APPROVED** [review]

**Review by PavloAndriiesh — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Comment by JohnSchmeichel** [comment]
@Roman-Shchukin we've had 3 regressions in this task hit production, can you please describe what testing has been done on these changes? FYI on end-to-end testing procedure: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/runningtests.md#end-to-end-testing

**Comment by JohnSchmeichel** [comment]
> @Roman-Shchukin we've had 3 regressions in this task hit production, can you please describe what testing has been done on these changes? FYI on end-to-end testing procedure: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/runningtests.md#end-to-end-testing



> @Roman-Shchukin we've had 3 regressions in this task hit production, can you please describe what testing has been done on these changes? FYI on end-to-end testing procedure: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/runningtests.md#end-to-end-testing

Actually looks like a version of this has already been merged, is this PR still needed?

**Comment by Roman-Shchukin** [comment]
@JohnSchmeichel This hotfix has already rolled out on Ring 0 and Ring 1 via merging changes in the release branch (https://github.com/microsoft/azure-pipelines-tasks/pull/17583). It was exception case since we've had regression.

It was tested in my test organization as follows:
```
jobs:
  - job: ubuntu_test_1
    pool:
        vmImage: ubuntu-latest
    steps:
    - task: npmAuthenticate@0
      inputs:
        workingFile: obj/.npmrc
    - script: |
        rm -r /home/vsts/work/1/s/obj

  - job: ubuntu_test_2
    pool:
        vmImage: ubuntu-latest
    steps:
    - task: npmAuthenticate@0
      inputs:
        workingFile: obj/.npmrc
      condition: eq('false', 'true')

  - job: ubuntu_test_3
    pool:
        vmImage: ubuntu-latest
    steps:
    - task: npmAuthenticate@0
      inputs:
        workingFile: obj/.npmrc 
```
It covers general working and last two error case.

**Review by JohnSchmeichel — APPROVED** [review]

**Pull request merged**
