### PR TITLE
use new artifacts-common library

### PR DESCRIPTION
**Pull request by shadargee1982**
**Task name**: NuGetAuthenticateV0

**Description**: This PR updates the version of azure-pipelines-tasks-artifacts-common.  The updated common library has fixes to handle retry logic for common network errors.

**Documentation changes required:** N

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** https://portal.microsofticm.com/imp/v3/incidents/details/214499609/home

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by damccorm** [comment]
@microsoft/akvelon-build-task-team or @alex-peck any idea why this build is failing? As far as I can tell all the upgrade steps were followed

**Comment by alex-peck** [comment]
@damccorm The TS version needs to be set in devDependencies.

**Comment by damccorm** [comment]
Good catch - thanks

**Comment by shadargee1982** [comment]
> @damccorm The TS version needs to be set in devDependencies.

That fixed it.  Thanks.

**Review by aasim — APPROVED** [review]

**Comment by ritchxu** [comment]
@shadargee1982 @damccorm @aasim I'm getting with version 0.179.0, would this PR be related?
```
##[error]File not found: 'D:\a\_tasks\NuGetAuthenticate_f5fd8599-ccfa-4d6e-b965-4d14bed7097b\0.179.0\bash.js'
```

**Pull request merged**
