### PR TITLE
JenkinsDownloadArtifacts migrate to Node10

### PR DESCRIPTION
**Pull request by AndreyIvanov42**
**Task name**:  JenkinsDownloadArtifactsV1

**Description**: Task migrate to node 10

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by AndreyIvanov42** [comment]
tested only by unit test

**Review by anatolybolshakov — APPROVED** [review]

**Comment by AndreyIvanov42** [comment]
@geekzter

**Review by EzzhevNikita — APPROVED** [review]

**Comment by AndreyIvanov42** [comment]
@harshiniks would it be possible for you to test and review these changes - to make sure that it's all fine?

**Comment by harshiniks** [comment]
> @harshiniks would it be possible for you to test and review these changes - to make sure that it's all fine?

@v-nmursapall is handling this now. Can you please reach out to her?

**Comment by v-nmursapall** [comment]
The code changes look fine to me.

**Review by harshiniks — APPROVED** [review]

**Pull request merged**
