### PR TITLE
[XcodeV5] Add Xcode ver. 13 support

### PR DESCRIPTION
**Pull request by KonstantinTyukalov**
**Task name**: XcodeV5

**Description**: 
- Add Xcode 13 to list of supported versions
- Update task version
- Update release notes description

**Documentation changes required:** (Y/N) Yes

**Added unit tests:** (Y/N) No

**Attached related issue:**  #15535 

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by alexander-smolyakov** [comment]
Tested related changes manually all works as expected. Link to the test build: [Run 20211214.4](https://v-alsmo.visualstudio.com/Test%20Playground/_build/results?buildId=1505&view=results)

**Review by alexander-smolyakov — APPROVED** [review]
LGTM, thanks!

**Review by max-zaytsev — APPROVED** [review]

**Review by DenisRumyantsev — APPROVED** [review]

**Comment by bsbechtel** [comment]
Hi, I was curious if this PR adds support for Xcode 13.2.1, which uses the most recent version of the log4j library: https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2_1-release-notes

I am seeing errors in my own pipeline when I try to specify Xcode version 13.2.1, but it may be a separate issue. Thanks

**Comment by alexander-smolyakov** [comment]
Hi @bsbechtel, this PR provided an ability to pick up the Xcode 13.0 only. As I can see the Xcode 13.2.1 is [already presented](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode) in the `macOS-11` image. To use this version of the Xcode, you have to switch to the `macOS-11` image, set the `xcodeVersion` in the Xcode task as `specifyPath`, and set `xcodeDeveloperDir` as `'/Applications/Xcode_13.2.1.app'` as a result, the Xcode task will pick up Xcode 13.2.1 to build the app.

Here is a YAML snippet for reference:
```YAML
- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: 'iphoneos'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_13.2.1.app'
    packageApp: false
```

**Comment by bsbechtel** [comment]
@alexander-smolyakov thank you for the clarification. Interestingly enough, I ran the pipeline last night using `macOS-latest` and `xcodeVersion: 13`, and it used 13.2.1. My understanding is that the `macOS-latest` image is still pointing to `macOS-10.15`. For our needs, I'm not complaining, but it was unexpected. Appreciate your quick response.

**Comment by alexander-smolyakov** [comment]
@bsbechtel it seems the migration process for the `macOS-latest` label is still in progress, you can track it in the following issue:
- actions/virtual-environments/issues/4060

**Pull request merged**
