### PR TITLE
Maven tasks

### PR DESCRIPTION
**Pull request by ramiMSFT**
Ref: https://github.com/MicrosoftDocs/azure-devops-yaml-schema-pr/pull/309

### CODE REVIEW

**Review by kirill-ivlev — APPROVED** [review]

**Comment by kirill-ivlev** [comment]
@ramiMSFT LGTM thanks, could you please bump task version: https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/taskversionbumping.md

**Comment by ramiMSFT** [comment]
Thank you @kirill-ivlev! 

#sign-off

**Review by KonstantinTyukalov — APPROVED** [review]

**Comment by KonstantinTyukalov** [comment]
@ramiMSFT looks something with tasks builds.

please, re-build and check you changes locally:
https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=19689091&view=logs&j=55b94f1c-9d32-5114-bc90-83768ebbe0df&t=8334df59-c1ae-533d-4d46-13427016ffd1&l=44
```text
> git diff --name-only /home/vsts/work/1/s/Tasks/MavenV4
Tasks/MavenV4/Strings/resources.resjson/en-US/resources.resjson

Uncommitted changes found:

 - Tasks/MavenV4/Strings/resources.resjson/en-US/resources.resjson


Please build your tasks locally and commit specified changes:

 - Tasks/MavenV2/Strings/resources.resjson/en-US/resources.resjson
 - Tasks/MavenV3/Strings/resources.resjson/en-US/resources.resjson
 - Tasks/MavenV4/Strings/resources.resjson/en-US/resources.resjson
 ```

**Comment by ramiMSFT** [comment]
Thank you for checking this @KonstantinTyukalov! I'm finally able to build this locally successfully. 

#sign-off

**Review by kirill-ivlev — APPROVED** [review]

**Pull request merged**
