### PR TITLE
Enable detection of preview tags in BuildNumber

### PR DESCRIPTION
**Pull request by jessehouwing**
Fixes https://github.com/Microsoft/vsts-tasks/issues/6136

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/vsts-tasks/6137)

### CODE REVIEW

**Comment by angusbreno** [comment]
Looking for it. Thanks @jessehouwing !

**Comment by angusbreno** [comment]
It has a release date? @keithrob @StandBackBurrito 😋

**Comment by damccorm** [comment]
Do we still need this? If so, looks like it should probably be moved where this currently lives - https://github.com/Microsoft/azure-pipelines-tasks/blob/9dccae562beeb9619c5d7e84ac11b4f78d6b2e9c/Tasks/NuGetCommandV2/nugetpack.ts#L94

**Comment by stephenmichaelf** [comment]
Closing due to age, please reopen if needed.

**Pull request closed without merging**
