### PR TITLE
Add Microsoft Go support

### PR DESCRIPTION
**Pull request by v-mohithgc**
**Task name**: GoToolV0

**Description**: Clone of https://github.com/microsoft/azure-pipelines-tasks/pull/18681: Add a goSource parameter to allow use of the Microsoft Go tool and default Go tools

image

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by rvairavelu — APPROVED** [review]

**Review by manolerazvan — APPROVED** [review]

**Review by LeftTwixWand — APPROVED** [review]
Looks good👍

**Comment by shueybubbles** [comment]
thx a ton for working through this!
This should help a bunch of teams

**Review by shueybubbles — APPROVED** [review]
:shipit:

**Review by ozanaydinMSFT — APPROVED** [review]

**Review by dagood — COMMENTED** [review]
Sorry I'm late to the party--I have concerns about making this a simple dropdown. For context, in https://github.com/microsoft/azure-pipelines-tasks/issues/16045 I mentioned:

> We don't want to change the _default_ base URL: Azure Pipelines users outside Microsoft should continue to get the official Go binaries. (Our build of Go is only intended for use within Microsoft to meet supply chain and FIPS requirements. For more info, the Microsoft build of Go is maintained at https://github.com/microsoft/go.)

Based on the screenshot and PR it doesn't look like there's any way for a user who sees this option to get more context about what the `MS Go Tools` option does. Without context, I worry that this will show up to anyone using AzDO (whether internal or not) and people will choose this just because it says "MS", not knowing what it's for and not needing it. This might result in spurious issues being filed (on this repo and ours) because e.g. this option doesn't support the same set of platforms as official Go.

If any of that is wrong or not a concern for a reason I haven't thought about, please let me know. 🙂

I prefer a raw URL input because then the user needs to already know what our toolset is for and very intentionally use it. This also avoid preferential treatment towards our fork of Go--with a URL, anyone could set up their own fork of Go and use that with this task.

The microsoft/go project might change to actually wanting to "advertise" our fork with dropdowns like this in the future, but so far that doesn't fit our goals.

**Comment by dagood** [comment]
I submitted a revert PR here: https://github.com/microsoft/azure-pipelines-tasks/pull/19012. Sorry I didn't get a chance to review this before it was merged, or when the dropdown was originally discussed.

**Pull request merged**
