### PR TITLE
Upgrade GitHubReleaseV1 to NodeJS16

### PR DESCRIPTION
**Pull request by Pranshu-Negi**
**Task name**: GitHubReleaseV1

**Description**: 
- bumped task version
- add node16 handler

**Documentation changes required:** N

**Added unit tests:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by v-schhabra — COMMENTED** [review]
Approved and tested

**Review by v-nagarajku — APPROVED** [review]
Looks good to me

**Review by rvairavelu — APPROVED** [review]

**Pull request merged**
