### PR TITLE
Adding http proxy environment variables to Azure CLI V2

### PR DESCRIPTION
**Pull request by ycamargo**
**Task name**: Azure CLI V2

**Description**: Adding http proxy environment variables (http_proxy and https_proxy) to azureclitask.ts when proxy configuration is present.

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) [Azure CLI Extension V2 is not respecting the .proxy file...](https://github.com/microsoft/azure-pipelines-tasks/issues/17752)

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Comment by ycamargo** [comment]
@microsoft-github-policy-service agree

**Comment by ycamargo** [comment]
@rvairavelu / @manolerazvan could one of you please review and approve this PR?

**Comment by v-mohithgc** [comment]
Hi @ycamargo , firstly thanks for contributing here.
Looks like there is a build failure because of the changes done in this PR.
Please fix and follow the below steps:

If you have cloned this repo locally, navigate to the root directory (ie C:...\azure-pipelines-tasks>)

Execute this build command " node make.js build --task AzureCLIV2 " //ensure to use node 8/10, else the command fails.
Once the build is completed/successful, commit the changes to this branch.
Thanks

**Comment by v-mohithgc** [comment]
Build failure detail:


2023-07-28T05:21:34.6058540Z Building: AzureCLIV2
2023-07-28T05:21:34.6058947Z ------------------------------------------------------------
2023-07-28T05:21:34.6110704Z 
2023-07-28T05:21:34.6111747Z > cd Tasks/AzureCLIV2
2023-07-28T05:21:34.6112155Z Detected Typescript version: 4.0.2
2023-07-28T05:21:34.6112335Z 
2023-07-28T05:21:34.6112571Z > npm install
2023-07-28T05:21:38.4194999Z 
2023-07-28T05:21:38.4196828Z > cd Tests
2023-07-28T05:21:38.4199852Z 
2023-07-28T05:21:38.4200503Z > npm install
2023-07-28T05:21:39.3611668Z 
2023-07-28T05:21:39.3613715Z > cd ..
2023-07-28T05:21:39.3617987Z 
2023-07-28T05:21:39.3619402Z > node /home/vsts/work/1/s/Tasks/AzureCLIV2/node_modules/typescript/bin/tsc --outDir "/home/vsts/work/1/s/_build/Tasks/AzureCLIV2" --rootDir "/home/vsts/work/1/s/Tasks/AzureCLIV2"
2023-07-28T05:21:47.8136119Z ,azureclitask.ts(19,28): error TS2339: Property 'getProxyConfiguration' does not exist on type 'typeof import("/home/vsts/work/1/s/Tasks/AzureCLIV2/node_modules/azure-pipelines-task-lib/task")'.
2023-07-28T05:21:47.8137772Z ,
2023-07-28T05:21:47.8276890Z ##[error]Bash exited with code '1'.
2023-07-28T05:21:47.8343199Z ##[section]Finishing: Build Tasks

**Comment by ycamargo** [comment]
> Hi @ycamargo , firstly thanks for contributing here. Looks like there is a build failure because of the changes done in this PR. Please fix and follow the below steps:
> 
> If you have cloned this repo locally, navigate to the root directory (ie C:...\azure-pipelines-tasks>)
> 
> Execute this build command " node make.js build --task AzureCLIV2 " //ensure to use node 8/10, else the command fails. Once the build is completed/successful, commit the changes to this branch. Thanks

Hi @v-mohithgc,
I found the issue. There is a problem on the documentation of the Proxy module that drove me to write this wrongfully.
I have even opened a new [issue](https://github.com/microsoft/azure-pipelines-task-lib/issues/958) on the azure-pipelines-task-lib repo to fix the documentation.

I've fixed it and built locally without any issues (see evidence below).

```bat
C:\git\github\azure-pipelines-tasks>node make.js build --task AzureCLIV2

> prepending PATH C:\git\github\azure-pipelines-tasks\node_modules\.bin
tsc tool:
Version 4.0.2
C:\GIT\GITHUB\AZURE-PIPELINES-TASKS\NODE_MODULES\.BIN\TSC.CMD
npm tool:
6.14.12
C:\PROGRAM FILES\NODEJS\NPM.CMD

------------------------------------------------------------
Building: AzureCLIV2
------------------------------------------------------------

> cd Tasks\AzureCLIV2
Detected Typescript version: 4.0.2

> npm install

> cd Tests

> npm install

> cd ..

> node C:\git\github\azure-pipelines-tasks\Tasks\AzureCLIV2\node_modules\typescript\bin\tsc --outDir "C:\git\github\azure-pipelines-tasks\_build\Tasks\AzureCLIV2" --rootDir "C:\git\github\azure-pipelines-tasks\Tasks\AzureCLIV2"

> cd ..\..

> copying task resources
copying *.ps1
copying *.psd1
copying *.psm1
copying *.sh
copying *.txt
copying icon.png
copying icon.svg
copying module.json
copying node_modules
copying package.json
copying Strings
copying task.json
copying task.loc.json
copying Tests

Build successful
```

**Comment by ycamargo** [comment]
Hi @v-mohithgc,
I saw that the local build changes the Tasks/AzureCLIV2/task.loc.json and this changes should be commited.
I did it already.

I think you need to start the CI tasks again. I tried, but I don't have permissions.

**Comment by v-mohithgc** [comment]
Task fails with this below error:
image

**Comment by ycamargo** [comment]
Hi @v-mohithgc, issue fixed. It was an improper null handling when there is no proxy configured on the envrionment.

**Comment by ycamargo** [comment]
Hi @v-mohithgc, I did take a look on this last error on ci-tests-tasks-v2 and it seems unrelated to the changes I've made. 
It looks like there is an issue with a secret used for the WIF tests.

**Comment by ycamargo** [comment]
Hi @v-mohithgc / @ozanaydinMSFT should I merge the master changes now?

**Review by v-mohithgc — APPROVED** [review]

**Review by rvairavelu — APPROVED** [review]

**Review by PhilipsonJoseph — APPROVED** [review]

**Pull request merged**
