### PR TITLE
Update PublishPipelineArtifact tasks to support passing custom properties

### PR DESCRIPTION
**Pull request by nayanshah**
**Task name**: PublishPipelineArtifactV0, PublishPipelineArtifactV1

**Description**: Updating PublishPipelineArtifact tasks to allow specifying custom properties that can be associated with the artifact. This change is dependent on a change to the pipelines agent - https://github.com/microsoft/azure-pipelines-agent/commit/8ea28ebb7e1be0bf3da354a042201a71b9902ee7

**Documentation changes required:** N

**Added unit tests:** N/a

**Attached related issue:** N/a

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by nayanshah** [comment]
@anatolybolshakov I've set minimum agent version as 2.199 since I don't see a release branch for that in azure-pipelines-agent repo. Is that fine?

**Comment by anatolybolshakov** [comment]
@nayanshah yes, looks good 👍

**Review by b-barthel — APPROVED** [review]

**Pull request merged**
