### PR TITLE
Hotfix to set restrict flag to false to mitigate downloadpackage extr…

### PR DESCRIPTION
**Pull request by zhenghao104**
…act failure

**Task name**: DownloadPackageV0/V1

**Description**: <Describe your changes here>

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by magleaso** [comment]
Do we understand the security scenario this break was intended to address so we know it's safe to default to un-restricted mode?

**Comment by zhenghao104** [comment]
> Do we understand the security scenario this break was intended to address so we know it's safe to default to un-restricted mode?

Still investigating on the security scenario. There was a sev2 last night, Edgar pushed out a hotfix to revert decompress zip version back to 0.3.0

**Comment by magleaso** [comment]
> > Do we understand the security scenario this break was intended to address so we know it's safe to default to un-restricted mode?
> 
> Still investigating on the security scenario. There was a sev2 last night, Edgar pushed out a hotfix to revert decompress zip version back to 0.3.0

The original justification from the decompress-zip PR was "This has significant security implications when decompressing files from untrusted users." I don't think that's a concern for us. We can assume the person who controls the build definition has permission to place files anywhere on the agent

**Review by magleaso — APPROVED** [review]

**Comment by zhenghao104** [comment]
> > > Do we understand the security scenario this break was intended to address so we know it's safe to default to un-restricted mode?
> > 
> > 
> > Still investigating on the security scenario. There was a sev2 last night, Edgar pushed out a hotfix to revert decompress zip version back to 0.3.0
> 
> The original justification from the decompress-zip PR was "This has significant security implications when decompressing files from untrusted users." I don't think that's a concern for us. We can assume the person who controls the build definition has permission to place files anywhere on the agent

Right, I am trying to repro a scenario where the check will fails.

**Comment by magleaso** [comment]
I'm not convinced that's necessary. If it takes much time to repro it, I would just release this instead. We can be confident that if the agent allows files to be written to a path, it's acceptable for the build owner to do that.

**Pull request closed without merging**
