### PR TITLE
Fixed two issues in docs/pinToTaskVersion/pinToTaskVersion.md

### PR DESCRIPTION
**Pull request by FranzKohl**
Fixed incorrect path value assignment to $taskDir (as build results are located in _build\Tasks\<task-name>, not Tasks\<task-name>), which causes an unusable task to be installed in the TFS app-tier, as the .js-files are missing and thus also missing when being downloaded by an agent.

Added missing backslash after dot in call to New-TaskInstallScript.ps1.

### CODE REVIEW

**Comment by FranzKohl** [comment]
I wonder that nobody has taken care of this PR for almost 10 months. 

@damccorm, is this in your area of responsibility? I ask because you were the last person who checked in changes to pinToTaskVersion.md (in Sep 2019). What is the next correct step for me (if any) to get this PR solved?

**Comment by anatolybolshakov** [comment]
Hi @FranzKohl let me take a look

**Review by anatolybolshakov — APPROVED** [review]
LGTM, thanks for amendment here!

**Review by EzzhevNikita — APPROVED** [review]

**Review by egor-bryzgalov — APPROVED** [review]

**Review by DaniilShmelev — APPROVED** [review]

**Pull request merged**
