### PR TITLE
AzurePowershellV5: Az-function output suppression

### PR DESCRIPTION
**Pull request by mortenlerudjordet**
**Task name**: AzurePowershellV5

**Description**: Suppress Az-functions output in line with rest of task code

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** Y : #19672

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by mortenlerudjordet** [comment]
@LeftTwixWand and @v-mohithgc: I removed the changes to helper function to make approval process easier.
Opened this new PR with only the changes made to AzurePowershellV5-task.

Hopefully this will make for a streamlined approval engagement.

**Comment by mortenlerudjordet** [comment]
@MrNewgarden: Please approve this also, it's the same as #19674 but removed the changes to VstsAzureHelpers_ as this triggered changing version on many other tasks.

**Review by MrNewgarden — APPROVED** [review]

**Comment by MrNewgarden** [comment]
@manolerazvan  please approve the code

**Comment by MrNewgarden** [comment]
@v-mohithgc please approve if you are an approver

**Review by LeftTwixWand — APPROVED** [review]

**Comment by LeftTwixWand** [comment]
Hey @mortenlerudjordet thank you for reaching me out.
And thank you so much for this contribution❤️

**Comment by LeftTwixWand** [comment]
I've added a commit with version bump

**Comment by LeftTwixWand** [comment]
Hey @mortenlerudjordet I completely agree, that versioning might be a bit confusing.
The `minor` version is usually our sprint number from this resource: [whatsprintis.it](https://whatsprintis.it)
And `patch` is incremental.

But now we're moving from NodeJS 10 to NodeJS 20.
And generating pretty much the same code but for different version of Node.
That's why there is a versioning inconsistency.
It might be really tricky if you're doing it for the first time.😅

Anyway, thank you for the contribution.
Tomorrow we would start a new tasks' deployment, and it might take up to 5 days to reach everyone.

**Pull request merged**
