### PR TITLE
[UseDotNetV2] Support global.json files with comments

### LINKED ISSUE #18631: [BUG]: UseDotNet@2 reports global.json is invalid if it contains comments although specification supports it
### Task name

UseDotNet

### Task version

2

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

_No response_

### Operation system

Windows Server 2019

### Task log

```shell
Starting: UseDotNet@2 (windows_build_container)
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.222.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
##[error]The global.json at path: 'C:\__w\1\s\global.json' has the wrong format. For information about global.json, visit here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json. Error while trying to read: SyntaxError: Unexpected token / in JSON at position 5
Finishing: UseDotNet@2 (windows_build_container)
```

### Relevant log output

```shell
Starting: UseDotNet@2 (windows_build_container)
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.222.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
##[error]The global.json at path: 'C:\__w\1\s\global.json' has the wrong format. For information about global.json, visit here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json. Error while trying to read: SyntaxError: Unexpected token / in JSON at position 5
Finishing: UseDotNet@2 (windows_build_container)
```

### Aditional info

```shell
UseDotNet@2 task reports global.json is invalid if it contains comments although specification supports it. 

The specification declares comments as valid, see here https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#comments-in-globaljson even though it goes against JSON specs. 

Comments in global.json

Comments in global.json files are supported using JavaScript or C# style comments. For example:
JSON


{
   // This is a comment.
  "sdk": {
    "version": "7.0.100" /* This is comment 2*/
  /* This is a
  multiline comment.*/
  }
}
```

I believe the use of strict json.parse in task code is what's causing the error.
```

### PR DESCRIPTION
**Pull request by dfederm**
**Task name**: UseDotNetV2

**Description**: The task can parse a global.json in the repo. It currently does not support json with comments, so this change uses the json5 package to parse it in a way that supports comments.

**Documentation changes required:** N

**Added unit tests:** Y

**Attached related issue:** Y. Fixes #18631

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by dfederm** [comment]
FYI @DmitriiBobreshev, who last touched this task.

**Comment by dfederm** [comment]
Ping @rvairavelu, @manolerazvan, @DmitriiBobreshev. This PR has been sitting for a couple weeks now. I had to resolve a fairly large conflict so am hoping to avoid this going fwd.

**Comment by v-mohithgc** [comment]
Hi @dfederm thanks for creating this PR! We are working on more prioritized issues at the moment but will get back to this one soon.
I have created an internal work item for this, soon an engineer will be assigned to test these changes before being merged.

Thanks, I will keep you posted.

**Review by DmitriiBobreshev — APPROVED** [review]

**Comment by dfederm** [comment]
Superseded by #19226

**Pull request closed without merging**
