### PR TITLE
Fix Python Twine Upload Authenticate Task

### PR DESCRIPTION
**Pull request by bothzoli**
**Task name**: TwineAuthenticate@V1

**Description**:
The Python Twine Upload Authenticate task will fail on feeds that contain a dot in their
name. The dot in the feed name will be escaped in the generated `.pypirc`
file in the corresponding section headers (e.g. `[Feed\.Name]`).
See also attached issue for more details.

The issue is due to how the `ini` npm package encode works. Thus
providing a custom `toString` implementation that convert repositories
to their `.pypirc` representation fixes the issue.

A new unit test was added to verify the correctness for a feed name that contains a dot.

The `ini` npm package is no longer used, therefore it's removed from the dependencies.

**Documentation changes required:** (N)

**Added unit tests:** (Y)

**Attached related issue:** (Y)
#14220

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by jmyersmsft — CHANGES_REQUESTED** [review]
Please bump the version in task.json as mentioned in the PR description template. Otherwise, LGTM

**Comment by bothzoli** [comment]
> Please bump the version in task.json as mentioned in the PR description template. Otherwise, LGTM

thanks @jmyersmsft
version bumped ;)

**Review by jmyersmsft — APPROVED** [review]

**Comment by bothzoli** [comment]
any progress on this?
the corresponding issue is about to be closed for being stale.

**Comment by jmyersmsft** [comment]
Sorry for the delay, I must have gotten distracted while waiting for the check builds last time.

**Comment by bothzoli** [comment]
LOL, no worries, thanks a lot 😊

**Pull request merged**
