### PR TITLE
Update webdeployment-common package [Part 2]

### PR DESCRIPTION
**Pull request by aleksandrlevochkin**
**Task names**: 

- AzureRmWebAppDeploymentV3
- AzureRmWebAppDeploymentV4
- AzureWebAppContainerV1
- AzureWebAppV1

**Description**: Updated webdeployment-common package to include this change: https://github.com/microsoft/azure-pipelines-tasks-common-packages/pull/334

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** [AB#2187393](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2187393)

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by vmapetr — APPROVED** [review]

**Review by DergachevE — APPROVED** [review]

**Comment by juss-wes** [comment]
We're starting to see widespread issues with the AzureWebAppContainer@1 task, starting with version 1.242.0 (which appears to be created as of this PR).  The error states:

> ##[error]Error: Failed to fetch App Service '[service name]' details. Error: Could not fetch access token for Azure. Status code: network_error, status message: Network request failed"

Version 1.241.0 works fine.  I'm still verifying if we can statically use v1.243.x in Azure DevOps Services, which hopefully may resolve the problem.

**Comment by v-schhabra** [comment]
Hi @juss-wes 
Thanks for reporting the issue.
Could you please share us the failed pipeline logs by enabling system.debug to "true"?

**Comment by juss-wes** [comment]
Here are 2 executions - one that worked (with the old version) and the other that failed (with the new).  I've obfuscated specific internal information with [DESCRIPTION] in many locations within the files, but should give you the insight you need still.
[v1.241.0.txt](https://github.com/user-attachments/files/16352430/v1.241.0.txt)
[v1.242.0.txt](https://github.com/user-attachments/files/16352431/v1.242.0.txt)

**Comment by yuhungchun** [comment]
Is there way to force to use the earlier version with AzureRmWebAppDeploymentV4 via YAML? Co-polit suggested to use version, however that didn't work.

**Comment by aleksandrlevochkin** [comment]
Hi @yuhungchun, I think you can specify the full task version, for example like this: ```- task: AzureRmWebAppDeployment@4.240.2```

**Comment by v-schhabra** [comment]
Hi @yuhungchun 
You can specify the last working version like this in your yaml pipeline:

- task: AzureRmWebAppDeployment@4.234.2

**Comment by RyDoug** [comment]
@v-schhabra can you share the PR with that fix here?

**Comment by v-schhabra** [comment]
Hi @RyDoug 
https://github.com/microsoft/azure-pipelines-tasks/pull/20170

**Pull request merged**
