### PR TITLE
Bumping task versions for AzureFunctionOnKubernetesV0, ContainerStructureTestV0, DockerV2, DuffleInstallerV0, GitHubReleaseV1, HelmDeployV0, KubernetesManifestV0, KubernetesV0, KubernetesV1, PublishPipelineMetadataV0

### PR DESCRIPTION
**Pull request by amaswauw**
**Task name**:  AzureFunctionOnKubernetesV0, ContainerStructureTestV0, DockerV2, DuffleInstallerV0, GitHubReleaseV1, HelmDeployV0, KubernetesManifestV0, KubernetesV0, KubernetesV1, PublishPipelineMetadataV0

**Description**: Bumping task version of the pipelines tasks listed above. 
These packages need to be updated for a docker-common-v2 task that I am working on, and in an attempt to make the PRs smaller and slightly more manageable, I have decided to make this PR. As per these [instructions](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md), I have bumped the tasks from 201-210 as the current sprint number is 210.

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) Y. https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1973804

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by dhashrath** [comment]
Can you please update description what prompted this version bump ?
Can you confirm why you are bumping this from 201 to 210. Is it because of sprint number ?
Can you include what testing you have done ? Have you tested any one of the tasks which access this new version of npm package that access MSI code path you have changed with this new version of npm package ?

**Comment by amaswauw** [comment]
This task follows a previous branch which made a function within the azure-arm-rest-v2 method public and accessible to the docker-common-v2 task that I am working on the related issue. To test that I have not broken anything, I tested with the KeyVault task and a managed identity login with accessing the key vault, and with the changes that I have proposed in the previous PR, and with manual testing (I ran the PR with a managed identity login and made sure that everything worked successfully and the secrets were retrieved successfully) I encountered no errors with this change.

**Review by dhashrath — APPROVED** [review]

**Comment by dhashrath** [comment]
Please link to previous PR which does package upgrade.

**Comment by amaswauw** [comment]
Package upgrade PR link: https://github.com/microsoft/azure-pipelines-tasks/pull/16818

**Review by mmrazik — APPROVED** [review]

**Pull request merged**
