### PR TITLE
Fix InstallAppleCertificate on macOS 13.0 by providing the -sha1 parameter to OpenSSL

### PR DESCRIPTION
**Pull request by OrthFelix**
MacOS 13.0 comes with a newer version of OpenSSL, that defaults to SHA256 for the output instead of SHA1. Passing -sha1 as an argument restores the old behavior that was expected by getP12Properties()

This doesnt change a task instead it changes the ios-signing-common library

**Documentation changes required:** N
**Added unit tests:** N
**Attached related issue:** [[InstallAppleCertificate] Unable to find the certificate SHA1 hash and common name (CN). Verify that the certificate is a valid P12. (Regression, MacOS 13.0)](https://github.com/microsoft/azure-pipelines-tasks/issues/17084)
**Checklist**:
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by inforithmics** [comment]
Applied the Fix
And the Tfs tasks works now

**Comment by abdulla-allaith** [comment]
Can someone please merge this if it's working and tested?
It's highly critical and breaking all iOS pipelines.

**Comment by OrthFelix** [comment]
@microsoft-github-policy-service agree [company="Quality Bytes GmbH"]

**Comment by OrthFelix** [comment]
@microsoft-github-policy-service agree company="Quality Bytes GmbH"

**Comment by AndyGettingAn** [comment]
Pls can someone merge this

**Review by LiliaSabitova — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Comment by AndyGettingAn** [comment]
Thank you for merging. How long does is usually take until this is applied to the Azure Tasks?

**Comment by SuperCaliMan** [comment]
Hi! how we can use this update on azure?

**Comment by abdulla-allaith** [comment]
Hi,
Any idea when will the fix reflect on production pipelines?

**Comment by nzcodarnoc** [comment]
I've just updated my self hosted agent to version 2.214.1 and it fails because of this bug. Any word on time to get this fix into the agent runners?

**Comment by ismayilov-ismayil** [comment]
Hi @nzcodarnoc , could you please give more information about error? It seems you already have updated version -sha1 parameter.

**Comment by axiomc** [comment]
We are facing the same problem causing failure in all of our pipelines.

`Azure Devops (On-premise): AzureDevOpsServer_20230217.5`
`Agent.Version : 2.217.2`






```Starting: Install Certificate
==============================================================================
Task         : Install Apple certificate
Description  : Install an Apple certificate required to build on a macOS agent machine
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/install-apple-certificate
==============================================================================
/usr/bin/openssl pkcs12 -in /Users/******/Downloads/Agent/_work/_temp/beanbar_certificate.p12 -nokeys -passin pass:axiom | /usr/bin/openssl x509 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
MAC verified OK
SHA256 Fingerprint=D3:56:3C:42:E2:78:67:B0:F2:AC:76:03:2E:8F:56:E2:75:60:73:1D:8A:11:0D:40:29:1F:24:13:72:5D:05:1E
subject= UID=382******; CN=iPhone Developer: Ste******  ou (2WG2******); OU=5CF8RPL35M; O=Axio******td.; C=CY
notBefore=Mar 14 07:41:24 2023 GMT
notAfter=Mar 13 07:41:23 2024 GMT
##[error]Error: Unable to find the certificate SHA1 hash and common name (CN). Verify that the certificate is a valid P12.
Finishing: Install Certificate
```

**Comment by nzcodarnoc** [comment]
> Hi @nzcodarnoc , could you please give more information about error? It seems you already have updated version -sha1 parameter.

Sorry for the delay in replying, I had another try today and it failed again. 

What kind of diagnostic info do you want?

**Pull request merged**
