### PR TITLE
Update tasks depending on republished common npm packages

### PR DESCRIPTION
**Pull request by DenisRumyantsev**
**Description**: next common npm packages have been republished.

Old packages:
* [azure-pipelines-tasks-msbuildhelpers](https://www.npmjs.com/package/azure-pipelines-tasks-msbuildhelpers)
* [azure-pipelines-tasks-packaging-common](https://www.npmjs.com/package/azure-pipelines-tasks-packaging-common)
* [azure-pipelines-tasks-webdeployment-common](https://www.npmjs.com/package/azure-pipelines-tasks-webdeployment-common)
* [azure-pipelines-tasks-azurermdeploycommon](https://www.npmjs.com/package/azure-pipelines-tasks-azurermdeploycommon)

Republished packages:
* [azure-pipelines-tasks-msbuildhelpers-v3](https://www.npmjs.com/package/azure-pipelines-tasks-msbuildhelpers-v3)
* [azure-pipelines-tasks-packaging-common-v3](https://www.npmjs.com/package/azure-pipelines-tasks-packaging-common-v3)
* [azure-pipelines-tasks-azurermdeploycommon-v3](https://www.npmjs.com/package/azure-pipelines-tasks-azurermdeploycommon-v3)
* [azure-pipelines-tasks-webdeployment-common-v4](https://www.npmjs.com/package/azure-pipelines-tasks-webdeployment-common-v4)

We have to update all tasks depending on these packages. Here is the list of them.
___
#### msbuildhelpers-v3
* XamariniOSV2
___
#### packaging-common-v3
* DotNetCoreCLIV2
* DownloadPackageV0
* DownloadPackageV1
* MavenV2
* MavenV3
* NpmV0
* NpmV1
* UseDotNetV2
* UseNodeV1
___
#### azurermdeploycommon-v3
* AzureAppServiceSettingsV1
* AzureFunctionAppContainerV1
* AzureFunctionAppV1
* AzureWebAppContainerV1
* AzureWebAppV1
___
#### webdeployment-common-v4
* AzureMysqlDeploymentV1
* AzureRmWebAppDeploymentV4
* FileTransformV1
* FileTransformV2
* IISWebAppDeploymentOnMachineGroupV0
* MysqlDeploymentOnMachineGroupV1
___

[Attached related issue](https://github.com/microsoft/build-task-team/issues/2155)

### CODE REVIEW

**Comment by DenisRumyantsev** [comment]
For these tasks (with updated republished common npm packages) unit-tests are failed locally:
* AzureMysqlDeploymentV1
* AzureRmWebAppDeploymentV4
* IISWebAppDeploymentOnMachineGroupV0
* MysqlDeploymentOnMachineGroupV1

For some tasks (with updated republished common npm packages) the CI is failed.
Examples of such tasks: DotNetCoreCLIV2 and MavenV2, maybe some other tasks.

**Comment by DenisRumyantsev** [comment]
For these tasks (with updated republished common npm packages) the CI is failed, so they have been restored:
* DotNetCoreCLIV2
* MavenV2
* MavenV3
* NpmV1

**Comment by DenisRumyantsev** [comment]
MavenV2, MavenV3, and XamariniOSV2 tasks have been moved to [the separate pull request](https://github.com/microsoft/azure-pipelines-tasks/pull/15829).

**Comment by DenisRumyantsev** [comment]
Hi @rvairavelu, @rohit-batra, could you please review this PR and test the `DotNetCoreCLIV2` and `UseDotNetV2` tasks (since they are in your ownership) to make sure they are working properly after the applied changes?

**Comment by DenisRumyantsev** [comment]
Hi @phil-hodgson, @aasim, @satbai, could you please review this PR and test these tasks (since they are in your ownership):
* `DownloadPackageV0`
* `DownloadPackageV1`
* `NpmV0`
* `NpmV1`

to make sure they are working properly after the applied changes?

**Comment by DenisRumyantsev** [comment]
Hi @vsebesta, @rvairavelu, @microsoft/pipeline-environment-team.
Could you please review this PR and test these tasks (since they are in your ownership):
* `AzureAppServiceSettingsV1`
* `AzureFunctionAppContainerV1`
* `AzureFunctionAppV1`
* `AzureWebAppContainerV1`
* `AzureWebAppV1`
* `AzureMysqlDeploymentV1`
* `AzureRmWebAppDeploymentV4`
* `FileTransformV1`
* `FileTransformV2`
* `IISWebAppDeploymentOnMachineGroupV0`
* `MysqlDeploymentOnMachineGroupV1`

to make sure they are working properly after the applied changes?

**Comment by PhilipsonJoseph** [comment]
@DenisRumyantsev  We have validated the below task

- AzureAppServiceSettingsV1
- AzureFunctionAppContainerV1
- AzureFunctionAppV1
- AzureWebAppContainerV1
- AzureWebAppV1
- AzureMysqlDeploymentV1
- AzureRmWebAppDeploymentV4
- FileTransformV1
- FileTransformV2
- IISWebAppDeploymentOnMachineGroupV0
- MysqlDeploymentOnMachineGroupV1
- UseDotNetV2

They are working fine. But we can see some other tasks which are not owned by Us. May i know how could we proceed with PR Approval as it involve multiple team tasks?

**Pull request closed without merging**
