### PR TITLE
Add JDK 18/19 to JDK version pick list - Maven2/Maven3/Maven4 Task

### PR DESCRIPTION
**Pull request by Heatmanofurioso**
**Task name**: Maven2/Maven3/Maven4

**Description**: Add support to JDK 18 and JDK 19 to all Maven Tasks

**Documentation changes required:** Y

**Added unit tests:** N

**Attached related issue:** Y https://github.com/microsoft/azure-pipelines-tasks/issues/16877

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by Heatmanofurioso** [comment]
> @microsoft-github-policy-service agree [company="{your company}"]

@microsoft-github-policy-service agree [company="EY"]

**Comment by Heatmanofurioso** [comment]
> @microsoft-github-policy-service agree company="your company"

@microsoft-github-policy-service agree

**Comment by Heatmanofurioso** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by Heatmanofurioso** [comment]
@v-mohithgc @rohit-batra Not sure if I'm supposed to ping anyone, since the contributor details don't indicate what to do if I don't get a response after X days, but is it possible to have a look into this PR?

It'd be useful for various people using Java-based images

**Comment by BrianRacca** [comment]
It would be great to have this done, needing this on my project!

**Comment by Heatmanofurioso** [comment]
Hi @vmapetr 
Is it possible to give a look into this PR, as it's integration should be seamless?

**Comment by Heatmanofurioso** [comment]
Any possible feedback on this?

It has been open for many months without any comments or feedback

**Pull request closed without merging**
