### PR TITLE
Fix typo in error message for 'Script Location' task AzureCLIV2

### PR DESCRIPTION
**Pull request by yilas**
Added missing space in the error message for 'Script Location' input, changing  "Value can either be'inlineScript' or 'scriptPath'" to "Value can either be 'inlineScript' or 'scriptPath'" for improved readability.

**Task name**: AzureCLIV2

**Description**: It seems that there is a missing space between "be" and "'inlineScript'," which would improve readability (see the issue https://github.com/microsoft/azure-pipelines-tasks/issues/20616)

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** N

**Attached related issue:** [Y](https://github.com/microsoft/azure-pipelines-tasks/issues/20616)

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Comment by yilas** [comment]
@microsoft-github-policy-service agree

**Comment by v-schhabra** [comment]
@yilas Please check these instructions and update the patch to 0 in task.json file.
https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/taskversionbumping.md

**Comment by yilas** [comment]
> @yilas Please check these instructions and update the patch to 0 in task.json file. https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/taskversionbumping.md

Done... Apologies for not having made this change previously.

**Review by v-schhabra — APPROVED** [review]
@yilas I observed that some generated files are not updated. Ig you havent run the build and some other commands.
These are the list of commands which you need to run after making the code changes.

Step 1: run "npm i" 
Step 2: Build: node make.js build --task AzureFileCopyV4  
                      node make.js test --task AzurePowerShellV4 
Step 3: Install tfx: // one time 
            npm install -g tfx-cli  
Step 4: Login: tfx login 
Service URL : https://v-jkaggrri.visualstudio.com/DefaultCollection  // Replace with your org URL
PAT : with full scope 
Step 5: Upload: tfx build tasks upload --task-path C:\AzurePipelineTask\azure-pipelines-tasks\_build\Tasks\AzureFileCopyV4  
Step 6: Delete: // optional 
tfx build tasks delete --task-id 1b2aec60-dc49-11e6-9b76-63056e018cac

**Comment by yilas** [comment]
> @yilas I observed that some generated files are not updated. Ig you havent run the build and some other commands. These are the list of commands which you need to run after making the code changes.
> 
> Step 1: run "npm i" Step 2: Build: node make.js build --task AzureFileCopyV4 //Replace the taskname here node make.js test --task AzurePowerShellV4 Step 3: Install tfx: // one time npm install -g tfx-cli Step 4: Login: tfx login Service URL : https://v-jkaggrri.visualstudio.com/DefaultCollection // Replace with your org URL PAT : with full scope Step 5: Upload: tfx build tasks upload --task-path C:\AzurePipelineTask\azure-pipelines-tasks_build\Tasks\AzureFileCopyV4 Step 6: Delete: // optional tfx build tasks delete --task-id 1b2aec60-dc49-11e6-9b76-63056e018cac



Done... Hope everything is OK 👌🏻

**Comment by v-schhabra** [comment]
Hi @yilas 
Could you please delete package.json file as that is not needed here.

**Comment by yilas** [comment]
> Hi @yilas Could you please delete packagelock.json file as that is not needed here.

`package-lock.json` removed

**Comment by v-schhabra** [comment]
Could you try to run build command again becoz I could see package-lock.json file

**Comment by yilas** [comment]
> Could you try to run build command again becoz I could see package-lock.json file

That’s strange because I ran the build command again (from [this repository](https://github.com/yilas/azure-pipelines-tasks/tree/patch-1)), and the file doesn’t seem to be present anymore.

```bash
@yilas ➜ /workspaces/azure-pipelines-tasks (patch-1) $ git status
Refresh index: 100% (20537/20537), done.
On branch patch-1
Your branch is up to date with 'origin/patch-1'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        package-lock.json

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by v-schhabra** [comment]
I have created a new PR by incorporating the changes. https://github.com/microsoft/azure-pipelines-tasks/pull/20637/files
Will close this PR.

**Pull request closed without merging**
