### PR TITLE
Remove packaging-common, AzureRmDeploy-common, webdeployment-common-v2  (Tasks/Common)

### PR DESCRIPTION
**Pull request by max-zaytsev**
**Task name**: Delete folders as they are no longer in use.

**Description**: 
Removed packages: 
- packaging-common, 
- AzureRmDeploy-common, 
- webdeployment-common-v2

`packaging-common` was replaced by `azure-pipelines-tasks-packaging-common` (For example: [PR](https://github.com/microsoft/azure-pipelines-tasks/commit/cd869c578e94eddc656b2ab16f829d691ef57ac3#diff-d4eec1c3bea74966e848feb355ff09cf194736b3f5377fe3916482993fb3db66))
`webdeployment-common-v2` was replaced by `azure-pipelines-tasks-webdeployment-common` (For example: [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/14163/files#diff-a6166aec640b0dbcc5d53cbcd30faa404bcee40d7204f04d698b551e7adb22a6))
`AzureRmDeploy-common` was replaced by `azure-pipelines-tasks-azurermdeploycommon` (For example: [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/14200/files#diff-b17d6b5b5f4c53bddaa17178db491f556e22716438642680fdc4910aef47407c))

### CODE REVIEW

**Review by DmitriiBobreshev — APPROVED** [review]

**Review by KonstantinTyukalov — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Review by jmyersmsft — CHANGES_REQUESTED** [review]
I still see a few references to packaging-common in master:

```
Tasks\NpmV0\Tests\NpmMockHelper.ts:132:        this.tmr.registerMock('packaging-common/locationUtilities', {
Tasks\NuGetToolInstallerV0\make.json:5:                "node_modules/packaging-common/node_modules/azure-pipelines-task-lib"
Tasks\NuGetToolInstallerV1\make.json:5:                "node_modules/azure-pipelines-packaging-common/node_modules/azure-pipelines-task-lib",
Tasks\TwineAuthenticateV0\make.json:11:                "node_modules/packaging-common/node_modules/azure-pipelines-task-lib",
```

**Review by jmyersmsft — APPROVED** [review]

**Comment by max-zaytsev** [comment]
> I still see a few references to packaging-common in master:
> 
> ```
> Tasks\NpmV0\Tests\NpmMockHelper.ts:132:        this.tmr.registerMock('packaging-common/locationUtilities', {
> Tasks\NuGetToolInstallerV0\make.json:5:                "node_modules/packaging-common/node_modules/azure-pipelines-task-lib"
> Tasks\NuGetToolInstallerV1\make.json:5:                "node_modules/azure-pipelines-packaging-common/node_modules/azure-pipelines-task-lib",
> Tasks\TwineAuthenticateV0\make.json:11:                "node_modules/packaging-common/node_modules/azure-pipelines-task-lib",
> ```

`packaging-common` is not installed in any of these tasks.
I'll fix these lines in a separate PR since it requires updating the versions of the tasks.

**Review by Pranshu-Negi — APPROVED** [review]

**Pull request merged**
