### PR TITLE
Add support for VS2022 to SqlAzureDacpacDeployment

### PR DESCRIPTION
**Pull request by Kittoes0124**
**Task name**: SqlAzureDacpacDeployment

**Description**: Add support for VS2022 by bumping version support from 17 to 18 in VSWhere check.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** Y - https://github.com/microsoft/azure-pipelines-tasks/issues/15998

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Review by mmrazik — APPROVED** [review]

**Comment by mmrazik** [comment]
@Kittoes0124 can you, please, rebase your branch? I'd like to merge but it says it is out of date with base branch and I can't merge without that (and can't rebase myself as this is in your fork). Thanks!

**Comment by Kittoes0124** [comment]
> @Kittoes0124 can you, please, rebase your branch? I'd like to merge but it says it is out of date with base branch and I can't merge without that (and can't rebase myself as this is in your fork). Thanks!

It has been synced with main.

**Comment by v-nagarajku** [comment]
Hi @Kittoes0124 user has reported https://github.com/microsoft/azure-pipelines-tasks/issues/16890 after version being changed from 1.202 to 1.209. I could see this is the latest version. Can you please help on this issue and do the needful. Thanks
cc: @mmrazik

**Pull request merged**
