### PR TITLE
Vulnerability fix for AzureKeyVaultV1

### PR DESCRIPTION
**Pull request by Pranshu-Negi**
**Task name**: AzureKeyVaultV1

**Description**: <Describe your changes here>

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) https://dev.azure.com/mseng/PipelineTools/_componentGovernance/184/alert/79428?typeId=12858

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected
- [x] node make.js build --task AzureKeyVaultV1
- [x] node make.js test --task AzureKeyVaultV1

### CODE REVIEW

**Comment by Pranshu-Negi** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Review by v-mohithgc — APPROVED** [review]
Tested and validated.

**Pull request merged**
