### PR TITLE
Added new helm push command (helm v3.7.0) 

### PR DESCRIPTION
**Pull request by urbanfi**
**Task name**: HelmDeployV0

**Description**:
 The 3.7.0 version of the helm tool introduced a new push command and debricated save chart. 
 The push command was added to the task aswell as the combined option packagepush. 
 The packagepush option will package a helm chart, login to a registry and push the chart to it using the OCI-feature.
 I also added a new check for these commands to ensure that helm version 3.7 or higher is used.

**Documentation changes required:** (Y) 
a new command was introduced as well as new parameters in the task

**Added unit tests:** (Y) <Please mark if unit tests were added or updated according changes>
Included unit test for push and packagepush option

**Attached related issue:** (Y) 
[tasks need update for helm breaking changes #15288](https://github.com/microsoft/azure-pipelines-tasks/issues/15288) 

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

Urban Ficht <urban.ficht@daimler.com> on behalf of Daimler TSS GmbH

[PROVIDER_INFORMATION](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

### CODE REVIEW

**Comment by BoSoeborgPetersen** [comment]
Now that the OCI feature is GA for Helm in version 3.8, it would be really great if this could be finished

**Comment by Eugst** [comment]
@rohit-batra @urbanfi 
could it be finished, please? really stuck on searching how to push Helm package to ACR without creating credentials and run login via azure-pipeline.

**Comment by ThumbGen** [comment]
Any progress on this? It seems just review is missing, the work is done already. Many thanks in advance!

**Comment by waldemarschmalz** [comment]
Any news on this? Will it be merged any time soon or is it solved with a different merge already?

**Comment by urbanfi** [comment]
> Any news on this? Will it be merged any time soon or is it solved with a different merge already?

unfortunately i have not received any feedback from Microsoft @rohit-batra

**Comment by ThumbGen** [comment]
It must be so demotivating for PR authors to not receive attention in almost one year, for such useful PRs :(

**Pull request closed without merging**
