### PR TITLE
Bugfix/fail publish code coverage results empty code coverage

### PR DESCRIPTION
**Pull request by FlorianAlbert**
**Task name**: PublishCodeCoverageResults@2

**Description**: The publishing of the code coverage results now only get executed when there are summary files found.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** Y #19270

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by FlorianAlbert** [comment]
@microsoft-github-policy-service agree

**Comment by GavinToddlds** [comment]
Thank you for creating this. Getting this merged in for me would help a lot

**Comment by FlorianAlbert** [comment]
Just waiting for someone to review it 😉

**Comment by ganeshpms** [comment]
much needed. waiting to be released.

**Review by vinayakmsft — APPROVED** [review]
Looks good

**Review by rasunkar — APPROVED** [review]

**Comment by GavinToddlds** [comment]
Now that we have approvals what is needed to get the tests ran to merge this in?

**Comment by FlorianAlbert** [comment]
@vinayakmsft Is this now obsolete due to #19568?

**Comment by FlorianAlbert** [comment]
Closing this due to #19568

**Pull request closed without merging**
