### PR TITLE
Update helpMarkDown for AndroidSigningV3 apksignerArguments

### PR DESCRIPTION
**Pull request by sphanley**
In the 3.\* version of the Android Signing task, the default value for `apksignerArguments` has changed from `-verbose -sigalg MD5withRSA -digestalg SHA1` (which was the default in 2.\*) to `--verbose`, but the tooltip still reflects the defaults from 2.\*. This PR updates the `helpMarkDown` to reflect the correct defaults for 3.\*.

### CODE REVIEW

**Comment by sphanley** [comment]
Hi @leantk! Pinging you since you're listed as the assigned reviewer - any chance of seeing this reviewed/merged? I submitted it during last year's Hacktoberfest, and I was reminded of it by the fact that I'm getting emails promoting Hacktoberfest 2020. Would be really nice to see it through before the year's passed! :)

**Comment by egor-bryzgalov** [comment]
Hi, @sphanley! Could you please change the task's version in accordance with [this guide](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/taskversionbumping.md)?

**Comment by anatolybolshakov** [comment]
Hi @sphanley thanks for a contribution! I reworked these changes a little bit and created separate PR https://github.com/microsoft/azure-pipelines-tasks/pull/13554

**Comment by anatolybolshakov** [comment]
Hi @sphanley we merged related changes in https://github.com/microsoft/azure-pipelines-tasks/pull/13554, thanks again for contribution and heads up! These changes will be available with next release

**Pull request closed without merging**
