### PR TITLE
[XamarinAndroidV1] Add MSBuild 16.0 option for msbuildVersion input

### PR DESCRIPTION
**Pull request by max-zaytsev**
**Task name**: XamarinAndroidV1

**Description**: Added MSBuild 16.0 option for msbuildVersion input

**Documentation changes required:** N
**Added unit tests:** N

**Attached related issue:** https://github.com/microsoft/azure-pipelines-tasks/issues/10839

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by anatolybolshakov** [comment]
Please update docs also https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-android?view=azure-devops

**Review by EzzhevNikita — COMMENTED** [review]
Please bump task version, 188 sprint started today

**Review by andy-mishechkin — APPROVED** [review]

**Comment by max-zaytsev** [comment]
>Please update docs also https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-android?view=azure-devops

https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/3201

**Comment by max-zaytsev** [comment]
>Please bump task version, 188 sprint started today

Thx! Done

**Review by EzzhevNikita — APPROVED** [review]

**Pull request merged**
