### PR TITLE
Upgrade PublishCodeCoverageResultsV2 to NodeJS10 and NodeJS16

### PR DESCRIPTION
**Pull request by Roman-Shchukin**
**Task name**: PublishCodeCoverageResultsV2

**Description**: Task updated to Node10 and Node16

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** https://github.com/microsoft/build-task-team/issues/3792

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by vinayakmsft** [comment]
Can you please update the branch:
image

**Comment by Roman-Shchukin** [comment]
@vinayakmsft Done.

**Review by adityashahms — APPROVED** [review]
Performed basic sanity testing. Working as expected

**Review by triptijain2112 — APPROVED** [review]
Approving the changes on behalf of Aditya!

**Review by ismayilov-ismayil — APPROVED** [review]

**Review by vmapetr — APPROVED** [review]

**Pull request merged**
