### PR TITLE
Upgraded dependency of the InstallAppleCertificate task

### PR DESCRIPTION
**Pull request by ismayilov-ismayil**
**Task name**:  Upgrade InstallAppleCertificateV2 task dependency and version

**Description**: Due to common language upgrade, the dependency should upgrade in the task as well

**Documentation changes required:** N
**Added unit tests:** N
**Attached related issue:** [https://github.com/microsoft/azure-pipelines-tasks/issues/17084](https://github.com/microsoft/azure-pipelines-tasks/issues/17084)

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by ismayilov-ismayil** [comment]
Hi @mstrent, we are working on it, thanks for your patience

**Comment by mstrent** [comment]
@ismayilov-ismayil Thanks! Curious, after this PR is merged, how long will it take for us to have a usable release?

**Comment by dhawaldawar** [comment]
@ismayilov-ismayil We are also in the same situation, our team is blocked due to this issue. Could you please share what is the ETA?

**Review by max-zaytsev — APPROVED** [review]

**Review by KonstantinTyukalov — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Comment by ismayilov-ismayil** [comment]
@mstrent @dhawaldawar 
We are working on it, and we will try to deliver this fix in short time. Thanks for your patience

**Pull request merged**
