### PR TITLE
updating  the azure-pipelines-tasks-azure-arm-rest-v2 to 2.198.2 

### PR DESCRIPTION
**Pull request by v-hinti**
**Task name**: AzureResourceManagerTemplateDeploymentV3

**Description**:   We identified the issue is with Common modules. We fixed and merged the Common modules and same fixies will applicable to AzureResourceManagerTemplateDeploymentV3.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by rajnish-byte — APPROVED** [review]

**Comment by v-hinti** [comment]
`/azp run`

**Pull request merged**
