### PR TITLE
NodeTool installer to consider proxy and cert

### PR DESCRIPTION
**Pull request by mmajcica**
NodeTool doesn't consider eventual proxy settings when fetching the list of the available versions. When the RestClient instance is create in order to fetch the following url "https://nodejs.org/dist/index.json", in case the proxy is set on the agent, it will ignore it and the task will fail.
This fix takes care of both the proxy and cert as often the cert chain can contain a self-signed cert.

### CODE REVIEW

**Comment by mmajcica** [comment]
@hross Tests are failing because of the fact that task-lib/mock-task doesn't export getHttpProxyConfiguration and getHttpCertConfiguration functions.
In order to do so I need to update the vsts-task-lib to azure-pipelines-task-lib latest version. Is that something you have considered?

**Comment by damccorm** [comment]
I'd be in favor of updating the version, it shouldn't break anything as far as I can tell.

**Comment by mmajcica** [comment]
> I'd be in favor of updating the version, it shouldn't break anything as far as I can tell.

I tried but unfortunately it breaks the current tests (which aren't many, three in total).
I'll check to see if I can fix them.

**Comment by leantk** [comment]
This PR is stale because it has been open for a year with no activity. Remove the stale label or comment on the PR otherwise this will be closed in 5 days

**Pull request closed without merging**
