### PR TITLE
Fixes azure-arm-rest-v2 to support workload identity federation

### PR DESCRIPTION
**Pull request by kboom**
**Task name**: Shared library, azure-arm-rest-v2

**Description**: Fixes the behavior for signing through workload identity federation ARM service connections.

**Documentation changes required:** (Y/**N**) 

**Added unit tests:** (Y/**N**) 

**Attached related issue:** (Y/**N**)

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by starkmsu — APPROVED** [review]

**Comment by kboom** [comment]
@microsoft-github-policy-service agree [company="{your company}"]

**Comment by kboom** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by kboom** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by kboom** [comment]
Reopening from original repository.

**Pull request closed without merging**
