### PR TITLE
Updated AzureStaticWebAppV0 to add compatibility for api token as task input

### PR DESCRIPTION
**Pull request by brhopcra**
Task name: AzureStaticWebAppV0

Description: Added compatibility for api token as task input.

Documentation changes required: N

Added unit tests: N

Attached related issue: Y 

Checklist:
[✓] Task version was bumped - please check instruction how to do it
[✓] Checked that applied changes work as expected

### CODE REVIEW

**Review by miwebst — APPROVED** [review]

**Review by anthonychu — APPROVED** [review]
LGTM! thanks

**Review by shigupt202 — APPROVED** [review]

**Comment by steve-yeager-littlebytegames** [comment]
I just ran into this blocking issue. Any ETA on when this change will be available? Thanks for this btw 😊

**Comment by anthonychu** [comment]
@shigupt202 Are you able to provide an ETA on the release. Is there a place we can see release and deployment schedules for these tasks?

**Comment by shigupt202** [comment]
@anthonychu The 187 deployment has already been started. It's done on Ring 0, and by mid next week it'll be done on other rings as well. There was a deployment blocker bug in another task which caused some delay in the deployment. (There's no publicly available dashboards to monitor the deployment schedules)

**Comment by steve-yeager-littlebytegames** [comment]
Any update on this release?

**Comment by shigupt202** [comment]
This should have been deployed in most of the rings by now. Can you please share your org name, so that I can check if it's present on your org?

**Comment by steve-yeager-littlebytegames** [comment]
Thanks! It's littlebytegames.

**Comment by shigupt202** [comment]
It should have been deployed now. Can you please check and confirm?

**Comment by steve-yeager-littlebytegames** [comment]
I see it thank you 😁

**Pull request merged**
