### PR TITLE
Update gulp to gulp 4.0.0

### PR DESCRIPTION
**Pull request by austin-jensen**
Updating gulp from 3.9.0 to 4.0.0, which deprecated gulp-util in favor of using the separate modules themselves

### CODE REVIEW

**Comment by moswald** [comment]
At the very least, I think you'll need to bump the patch version number for the GulpV1 task.

**Comment by moswald** [comment]
It came out of #7839 and #3890.

Gulp 4 is almost a year old now, and gulp-util is deprecated because of it. It's causing difficulties for some.

**Comment by moswald** [comment]
@bryanmacfarlane I think we can hold off on this change until mid-December if there's some larger work going on. @azureDaveOps might have a different opinion, though. I think he wants it done for RC2.

One user reported needing to update the global gulp version for each build task (I don't know why they said "each build task", it seems like it only needs to be done at the start of the build?). Probably the biggest issue is that since our Gulp Task didn't support overriding the gulp.js location (now fixed, but not released), users were stuck using our provided version. There are some vulnerabilities in gulp 3.x dependencies, plus with it being a year old it enforces outdated usage that can be cleaned up with 4.

**Comment by bryanmacfarlane** [comment]
@moswald - this gulpfile has nothing to do with builds and tasks at runtime.  This was a gulpfile for building the tasks (our eng system).   I also think it's largely a dead file not touched in 2 years and we use make.js.  I think we left it for a transitionary period but I think the right fix is to delete it.  The reason I was asking is I was trying to understand how and where it could possibly be relevant :)

**Comment by moswald** [comment]
@bryanmacfarlane lol, gotcha. @austin-jensen, we should talk next week when you're back.

**Comment by damccorm** [comment]
Closing since gulpfile no longer exists as of #9605 and we also now don't have the dependencies that are being bumped

**Pull request closed without merging**
