### PR TITLE
Drop TypeScript `2.3.4`

### PR DESCRIPTION
**Pull request by JamieMagee**
**Task name**: N/A

**Description**: Remove uses of TypeScript `2.3.4` in favour of `4.0.2`

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** #18119 

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by qianz2 — APPROVED** [review]

**Comment by JamieMagee** [comment]
@qianz2 Thanks for the approval. I don't have permissions to merge in this repo, so please merge if you think it's okay.

**Pull request merged**
