### PR TITLE
[ExtractFilesV1] Migration of ExtractFilesV1 to Node10

### PR DESCRIPTION
**Pull request by EzzhevNikita**
**Task name**: ExtractFilesV1

**Description**: Updated dependencies; Updated execution handler; Replaced deprecated methods _MochaDone => Mocha.Done_ and _tl.osType() => tl.getPlatform()_ ; Removed legacy tests;

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) Y

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

[**Node 6 backup branch**](https://github.com/microsoft/azure-pipelines-tasks/tree/node6hotfixes/ExtractFilesV1)

### CODE REVIEW

**Review by DaniilShmelev — APPROVED** [review]

**Review by sdobrodeev — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Comment by alex-peck** [comment]
Can you also delete the entries in the Tests-Legacy folder related to ExtractFiles?

**Comment by EzzhevNikita** [comment]
> Can you also delete the entries in the Tests-Legacy folder related to ExtractFiles?

Yes, sure, removed

**Review by alex-peck — APPROVED** [review]

**Comment by jmalak** [comment]
Terrible set of changes more broken thing then fixed.
Now Azure pipelines are broken on Linux if ExtractFiles task is used due to changed default behaviour.
Do you think about backward compatibility any way?
What about version number if such incompability with previous version?

**Comment by EzzhevNikita** [comment]
Hi @jmalak, could you please add some more information regarding your problem? Which exact issue this changes is causing for you? Could you please provide logs for broken broken pipeline?

**Comment by jmalak** [comment]
Problem is very simple.
You changed default behaviour of this task.
On Linux it was overwrite files by default before (expected behaviour), but now it fails because new default is not overwrite existing file.
Previous solution used same default behaviour, but last isn't.

**Comment by EzzhevNikita** [comment]
Yeah, I got it now. Recently we have introduced new [feature flag](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ExtractFilesV1/task.json#L55) for files overwriting in this task, by default task is not overwriting files in destination directory. But you can pass _overwriteExistingFiles_ option with _true_ value in task settings to allow files overwriting. Regarding out-of-dated documentation, sorry for inconvenient here, we have prepared update for it already and information about new feature will be added soon to the docs.

**Comment by jmalak** [comment]
Sorry, it is poor practice. You should create ExtractFiles@2 (V2 version) in such case.

**Pull request merged**
