### PR TITLE
Ensure UseNode Task satisfies npm requirement

### PR DESCRIPTION
**Pull request by Amoenus**
Fix for **UseNodeV1 does not satisfy npm demand like NodeToolV0 did** #11012

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/azure-pipelines-tasks/11030)

### CODE REVIEW

**Comment by damccorm** [comment]
Nit - build task so that task.loc.json gets updated as well. Otherwise, looks good, thanks for catching this!

**Comment by Amoenus** [comment]
@damccorm bumped task.loc.json version as well

**Comment by damccorm** [comment]
Yeah, you should take 1.156.2. That will ensure it gets published - we only publish tasks that have new version numbers

**Comment by Amoenus** [comment]
@damccorm done :)

**Pull request merged**
