### PR TITLE
Fix `Initialize-AzSubscription` function

### PR DESCRIPTION
**Pull request by DenisRumyantsev**
***Tasks list:***
* AzureCloudPowerShellDeploymentV1
* AzureCloudPowerShellDeploymentV2
* AzureFileCopyV2
* AzureFileCopyV3
* AzureFileCopyV4
* AzureFileCopyV5
* AzurePowerShellV2
* AzurePowerShellV3
* AzurePowerShellV4
* AzurePowerShellV5
* SqlAzureDacpacDeploymentV1

***Description:*** Added clearing default subscription for login in the `Initialize-AzSubscription` function, used in the `Initialize-AzModule` function, used in the `AzureFileCopy` task, in order to always use the subscription specified in the related `azureSubscription` (`connectedServiceName`) task input.

***Documentation changes required:*** No

***Added unit tests:*** No

***Checklist:***
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by v-nagarajku** [comment]
@DenisRumyantsev  can you please bump the version to 223, as the current sprint is 223 week 2

**Comment by DenisRumyantsev** [comment]
> @DenisRumyantsev can you please bump the version to 223, as the current sprint is 223 week 2

@v-nagarajku done

**Review by v-nagarajku — APPROVED** [review]
Checks are failing and manually running the pipeline in AzDevOps pipelines.

**Comment by DenisRumyantsev** [comment]
These failed checks can be successfully manually rerun with the `skipBumpingVersionsDueToChangesInCommon` pipeline variable enabled, so automatic failed checks are not an issue.

**Review by ozanaydinMSFT — CHANGES_REQUESTED** [review]
~We might need one more bump for AzureFileCopyV4 and V5 ; please wait before the merge.~

Could you please update AzureFileCopyV4 and AzureFileCopyV5 according to latest master branch?

**Review by ozanaydinMSFT — APPROVED** [review]

**Pull request merged**
