### PR TITLE
Migrate ContainerStructureTest task to Node10

### PR DESCRIPTION
**Pull request by mr-dokara**
**Task name**: ContainerStructureTestV0

**Description**: Migrated ContainerStructureTest task to Node10

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by golubev-ivan** [comment]
Tested manually, this task works fine.

**Review by anatolybolshakov — APPROVED** [review]

**Comment by golubev-ivan** [comment]
Hi @navin22, @mmrazik, Could you please take a look at this PR?

**Review by EzzhevNikita — APPROVED** [review]

**Review by navin22 — APPROVED** [review]
LGTM !

**Pull request merged**
