### PR TITLE
2142647 Update AKS API used to get cluster credentials in AKS tasks

### PR DESCRIPTION
**Pull request by PhilipsonJoseph**
**Task name**: AzureFunctionOnKubernetesV1
HelmDeployV0
HelmDeployV1
KubernetesManifestV1
KubernetesV1

**Description**:  New API for fetching credentials are added based on the FF

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) Y

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

#https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/2142647

### CODE REVIEW

**Comment by PhilipsonJoseph** [comment]
azp /run

**Review by onetocny — APPROVED** [review]

**Review by manolerazvan — APPROVED** [review]

**Review by geekzter — DISMISSED** [review]
@PhilipsonJoseph can we add a link to https://aka.ms/azdo-rm-aks-access in case we get an ARM permission issue (403)? I want to prevent customers that created custom RBAC roles from creating support cases. e.g. `Cannot fetch the credentials for the cluster %s. Reason %s. Make sure the service connection is assigned an appropriate Azure RBAC role: https://aka.ms/azdo-aks-rm-access.`

There are specific roles for user vs admin credentials, and a role that has everything. We can explain that in the doc.

**Comment by PhilipsonJoseph** [comment]
> https://aka.ms/azdo-rm-aks-access

Hi @geekzter  added URL to the Common lib with PR https://github.com/microsoft/azure-pipelines-tasks-common-packages/pull/410 and updated to tasks

**Pull request merged**
