### PR TITLE
Update preinstallprovprofile.ts

### LINKED ISSUE #13045: [InstallAppleProvisioningProfileV1] Not compatible with macOS (OSX) app signing anymore (". provisionprofile")
Captura de Tela 2020-06-02 às 01 55 57
Captura de Tela 2020-06-02 às 02 23 39

The extension validation added on this issue: https://github.com/microsoft/azure-pipelines-tasks/pull/12917 removed the capability of signing a MacOS app (Developer ID Application).

MacOS Provisioning Profile extension is ˜.provisionprofile˜. 
The ".mobileprovision" is used just for mobile apps... 
I cant find another way to sign my macOS app right now using Azure Devops.

.mobileprovision - iOS provisioning profile
.provisionprofile - OSX provisioning profile

### PR DESCRIPTION
**Pull request by jmartarelli**
To keep macOS (OSX) App compatibility (Developer ID Application)

https://developer.apple.com/developer-id/
https://fileinfo.com/extension/provisionprofile

.mobileprovision - iOS provisioning profile
.provisionprofile - OSX provisioning profile

Fixes #13045

### CODE REVIEW

**Comment by leantk** [comment]
@anatolybolshakov can we get somebody to take a look at this please? It LGTM except for the version bump that is missing

**Comment by leantk** [comment]
@jmartarelli thanks so much for the contribution! 🎉 

Could you make 2 minor adjustments please? The version of the task needs updated so that the changes get picked up. If you go to the `task.json` and `task.loc.json` files for this task, you will see a major/minor/patch version. Can you change the patch version to 0 and the minor version to 171 please (this matches our sprint cadence). You can see an example of this here (but only needed for this task and not others): https://github.com/microsoft/azure-pipelines-tasks/commit/fe7dd460af9f30ec8f9c521119e7eae445b38183#diff-c73ecd0ae1d53f810bd8fad2a95b0b84

**Comment by jmartarelli** [comment]
> @jmartarelli thanks so much for the contribution! 🎉
> 
> Could you make 2 minor adjustments please? The version of the task needs updated so that the changes get picked up. If you go to the `task.json` and `task.loc.json` files for this task, you will see a major/minor/patch version. Can you change the patch version to 0 and the minor version to 171 please (this matches our sprint cadence). You can see an example of this here (but only needed for this task and not others): [fe7dd46#diff-c73ecd0ae1d53f810bd8fad2a95b0b84](https://github.com/microsoft/azure-pipelines-tasks/commit/fe7dd460af9f30ec8f9c521119e7eae445b38183#diff-c73ecd0ae1d53f810bd8fad2a95b0b84)

Yes, sure. I will make the adjustments you mentioned!

**Comment by leantk** [comment]
Thanks again @jmartarelli!

**Comment by jmartarelli** [comment]
> Thanks again @jmartarelli!

@leantk , should we fix the Test classes as well?
- Tasks/InstallAppleProvisioningProfileV1/Tests/L0.ts 
- Tasks/InstallAppleProvisioningProfileV1/Tests/L0SecureFile.ts 

There are ".mobileprovision" extension verification on these classes above...

**Comment by leantk** [comment]
@jmartarelli good call. If you have a moment to do that then great but otherwise I'll put it on our backlog to add them

**Comment by brewmanandi** [comment]
We are running into this. Any way to circumvent ATM?

**Comment by nor0x** [comment]
any updates on this? our pipeline still fails for macOS builds

**Comment by jmartarelli** [comment]
There is a workaround for this: Instead of getting the certificate (".provisionprofile") uploaded into azure, put it somewhere inside your source branch and configure the task to look into your source repository... (There is a combo box for this option selection)...

**Comment by nor0x** [comment]
thank you @jmartarelli works fine for me!

**Comment by firaxis** [comment]
Hi!
When updated task will be rolled out ?

**Comment by anatolybolshakov** [comment]
Hi @firaxis, it will be rolled out during next 2-3 weeks

**Comment by firaxis** [comment]
It's pity that you can't roll out a hotfix..
Fortunately, uploading a fixed task is quite simple, thanks :)

@anatolybolshakov Could you please tell, after next release, do I need to do anything to keep task updating further ?

**Comment by anatolybolshakov** [comment]
@firaxis no, you don't need to do anything - it will be just updated automatically

**Pull request merged**
