### PR TITLE
VstestV2 task changes to support VS2022 

### PR DESCRIPTION
**Pull request by v-vnomula**
**Task name**: VsTestV2
**Description**: Task changes to support VS2022 preview

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) https://github.com/actions/virtual-environments/issues/4123

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by ShreyasRmsft — APPROVED** [review]

**Comment by MasterKolka** [comment]
@v-vnomula When it is going to be available?

**Comment by mikeKuester** [comment]
@v-vnomula I would like to answer the same question ...
I'm not able to use .NET 6 with the actual version in Azure Pipeline: https://github.com/microsoft/azure-pipelines-tasks/issues/15499

**Comment by aarondandy** [comment]
I too am blocked on a VS 2022 upgrade because of this issue.

**Comment by aarondandy** [comment]
Maybe the vs2022 image general availability tomorrow will cause more people to notice this wasn't deployed yet 🤞: https://github.com/actions/virtual-environments/issues/4488

**Comment by MasterKolka** [comment]
@aarondandy images don't contain devops tasks implementation. They have their own repository and marketplace - https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?toc=%2Fazure%2Fdevops%2Fpipelines%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fpipelines%2Fbreadcrumb%2Ftoc.json&view=azure-devops#step-5-publish-your-extension

**Comment by aarondandy** [comment]
@MasterKolka right, but as that image reaches general availability there may be more people running into this issue which could cause this to receive more attention. At least, that is my hope!

**Comment by qwertylolman** [comment]
When this fix will be available? Got this issue today.

**Pull request merged**
