### PR TITLE
Update taskparameters.ts

### PR DESCRIPTION
**Pull request by michelcedric**
**Task name**: AzureWebAppContainerV1

**Description**:  support \n caracter for multiline
As some other Task  (example : AzureFunctionAppV1) use appsettings parameter :  Add multiline support.
I suggest to use \n as space (mandatory). It's better for readibility. A space is not visible and easy to forget it. 
It's also more consistent with other tasks.

**Documentation changes required:** (N) => not required but maybe interesting to add information about this possibility 

**Added unit tests:** (N)

**Attached related issue:** (N)

**Checklist**:
- [ OK] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ OK] Checked that applied changes work as expected

Result
```
steps:
- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy: test'
  inputs:
    azureSubscription: resourcegroup
    appName: test
    appSettings:  
      -input1 val1 \n
      -input2  val2 \n
```

### CODE REVIEW

**Comment by michelcedric** [comment]
@v-mohithgc new one with updated version, and merged master.
Could you adapt this one or validated ?

**Comment by v-mohithgc** [comment]
> @v-mohithgc new one with updated version, and merged master. Could you adapt this one or validated ?

Thanks, I will test it and revert back.

**Comment by v-mohithgc** [comment]
@michelcedric , looks the changes weren't build properly so checks are failing here, I will fix that now.
meanwhile, if possible, can you brief about the proposed fix here? like how to reproduce this issue (required for testing) and how these changes will fix that.

Thanks

**Comment by v-mohithgc** [comment]
I have rebuild this task, will use this PR https://github.com/microsoft/azure-pipelines-tasks/pull/19094

**Comment by michelcedric** [comment]
Manually integrated in https://github.com/microsoft/azure-pipelines-tasks/pull/19128
Thank you ;)

**Pull request closed without merging**
