### PR TITLE
Arm64 changes for universal package version 236

### PR DESCRIPTION
**Pull request by viralpandya**
**Task name**: UniversalPackage

**Description**: Changes related to arm64

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) Issue is in sprint board

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by fadnavistanmay — APPROVED** [review]

**Review by jmyersmsft — APPROVED** [review]

**Review by LeftTwixWand — APPROVED** [review]

**Review by DenisRumyantsev — CHANGES_REQUESTED** [review]
`package.json` and `package-lock.json` have not been updated for `Node20` build config

**Review by DenisRumyantsev — APPROVED** [review]
Approved, thank you!

**Pull request merged**
