### PR TITLE
[KubernetesManifestV0] Adding missing dependency

### PR DESCRIPTION
**Pull request by ds-ms**
**Task name**: KubernetesManifestV0

**Description**: Task packaging was missing `typed-rest-client` node module

**Documentation changes required:** N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) (DTS)
**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by ammohant — APPROVED** [review]

**Comment by josuedallagnese** [comment]
Thanks !!!

**Comment by skmaingi** [comment]
This issue is still unresolved 
[https://developercommunity.visualstudio.com/content/problem/1187566/errorunhandled-cannot-find-module-typed-rest-clien.html?inRegister=true](url)

**Comment by skmaingi** [comment]
This issue is still unresolved 
[https://developercommunity.visualstudio.com/content/problem/1187566/errorunhandled-cannot-find-module-typed-rest-clien.html?inRegister=true](url)

**Comment by skmaingi** [comment]
This issue is still unresolved 
[https://developercommunity.visualstudio.com/content/problem/1187566/errorunhandled-cannot-find-module-typed-rest-clien.html?inRegister=true](url)

**Comment by skmaingi** [comment]
This issue is still unresolved 
[https://developercommunity.visualstudio.com/content/problem/1187566/errorunhandled-cannot-find-module-typed-rest-clien.html?inRegister=true](url)

**Comment by skmaingi** [comment]
This issue is still unresolved

**Comment by skmaingi** [comment]
This issue is still unresolved

**Comment by ds-ms** [comment]
We work out of IST Time Zone. This will be resolved by the end of day today. 😃

**Pull request merged**
