### PR TITLE
Bump mocha version to 6.2.3

### PR DESCRIPTION
**Pull request by kirill-ivlev**
**Description**: Bump mocha version to 6.2.3 to fix the security vulnerability 

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** Y
 https://githubhot.com/repo/SonyaMoisset/js-dev-env-starter-kit/issues/124)
**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by anatolybolshakov** [comment]
@kirill-ivlev looks good, thanks!
Could you please test locally with 'node make.js test'? Seems like there is some error at the moment:
image

**Comment by kirill-ivlev** [comment]
@anatolybolshakov thanks for noticing that, resolved

**Comment by kirill-ivlev** [comment]
@mmrazik could you please review this PR

**Review by anatolybolshakov — APPROVED** [review]

**Review by mmrazik — APPROVED** [review]

**Comment by BravermanMillimanCRS** [comment]
This change occurred during the time window where all of our file transforms stopped working. See https://developercommunity.visualstudio.com/t/FileTransform-pipeline-step-fails-with-/10054809

I'll take a look at the code in this commit to see what might have killed our pipelines, but at the moment, this is the only thing that changed between our pipelines working and not working, and it's exactly in the right time window.

**Pull request merged**
