### PR TITLE
Add braces to '-and' in if statements, for the correct function handling

### PR DESCRIPTION
**Pull request by kuleshovilya**
**Description**: Add braces to '-and' in if statements, for the correct function handling
**Attached related issue:** DTS 1887373
**Documentation changes required:** N
**Added unit tests:** N

Checklist:

- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by v-jkarri — CHANGES_REQUESTED** [review]
Can you please undo version changes for AzureCloudPowerShellDeployment and
SqlAzureDacpacDeployment tasks. As the method Disconnect-AzureAndClearContext in Tasks/Common/VstsAzureHelpers_/Utility.ps1 is used only in AzureFileCopy and AzurePowerShell tasks.

**Comment by marcelovital** [comment]
Does this do the same as #15402 ?

**Comment by marcelovital** [comment]
Can you please finish this PR? It's stopped for a long time, and also seems similar to my #15402

**Comment by DiederickA** [comment]
@chshrikh @nadesu @microsoft/akvelon-build-task-team: can you review this PR so it will continue?

**Comment by nadesu** [comment]
@PhilipsonJoseph @v-saikumart @v-ibshaik - Pls review the PR

**Comment by jberezanski** [comment]
Could this please be merged? The deluge of these warnings in our pipelines makes it much more difficult to recognize actual problems.

**Comment by v-lomer** [comment]
I agree that this issue is only impacting all versions (1 thru 5) of `AzureFileCopy` and all versions (2 thru 5) of `AzurePowerShell` through their usage of `function Disconnect-AzureAndClearContext` (`Tasks\Common\VstsAzureHelpers_\Utility.ps1`).

The two impacted functions (`function Disconnect-UsingAzModule` and `function Disconnect-UsingARMModule`) are only used by  `function Disconnect-AzureAndClearContext` (`Tasks\Common\VstsAzureHelpers_\Utility.ps1`)

- Please undo version changes for `AzureCloudPowerShellDeployment` and `SqlAzureDacpacDeployment` tasks
- [#15402](https://github.com/microsoft/azure-pipelines-tasks/pull/15402) does correct the `-and` issue with the two functions in question. While including more style-cop formatting issues and removes the usage of Aliases
- Separate issue should be opened to focus on **15402's** style-cop formatting issues and possible a 2nd issue for removing Aliases (these would focus on the whole codebase in team defined units)

**Comment by v-lomer** [comment]
@PhilipsonJoseph This PR appears to have lost attention, is there anyone this can be escalated to for completion?

**Comment by v-lomer** [comment]
@v-ibshaik This PR appears to have lost attention, is there anyone this can be escalated to for completion?

**Comment by DiederickA** [comment]
Could this be given some attention?
@kuleshovilya @v-ibshaik @PhilipsonJoseph

**Comment by kuleshovilya** [comment]
@DiederickA As @v-lomer pointed out there's already a similar PR that fixes exact same issue, I suggest just closing this one.

**Comment by DiederickA** [comment]
I do not mind which one is resolved... That similar PR does not have a better track record.

**Comment by v-lomer** [comment]
This PR follows `One Definition Rule (ODR)` so I would suggest finishing this PR over the other linked PR

**Comment by kuleshovilya** [comment]
I'm not working on a related project anymore and not in the context of the changes currently, so  I think either closing it or asking somebody whos more in the flow than me to finish it. Sorry for the inconvinience.

**Comment by DaniilShmelev** [comment]
@rvairavelu Judging by the codeowners file, this is your task. Could you please take a look?

**Review by PhilipsonJoseph — APPROVED** [review]

**Review by v-lomer — APPROVED** [review]

**Pull request merged**
