### PR TITLE
[ios-signing-common] Created 2.0.0-preview version

### PR DESCRIPTION
**Pull request by egor-bryzgalov**
**Task name**: ios-signing-common

**Description**: Created 2.0.0-preview version of ios-signing-common to make it compatible with node 14 and azure-pipelines-task-lib 3 preview.

**Documentation changes required:** No

**Added unit tests:** No

**Attached related issue:** Parent issue - [#299](https://github.com/microsoft/build-task-team/issues/299)

**Checklist**:
- [x] Package version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by DaniilShmelev — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]
LGTM, thanks!

**Review by damccorm — APPROVED** [review]

**Review by alexander-smolyakov — APPROVED** [review]

**Comment by damccorm** [comment]
Published!

**Comment by egor-bryzgalov** [comment]
> Published!

@damccorm Thank you! Could you please also take a look at the securefiles-common package updated previously with [this commit](https://github.com/microsoft/azure-pipelines-tasks/commit/72f7490e74844bcb422ea10f19b274e95a51ad79)?

**Comment by damccorm** [comment]
Yep, published that one as well - thanks @egor-bryzgalov

**Pull request merged**
