### PR TITLE
Fixed vulnerabilities (npm audit fix) - for az-blobstorage-provider-v2

### PR DESCRIPTION
**Pull request by anatolybolshakov**
**Task name**: N/A (az-blobstorage-provider-v2 common package)

**Description**: fixed vulnerabilities with 'npm audit fix'

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it - bumped package version
- [ ] Checked that applied changes work as expected - tested with JavaToolInstallerV0 (sanity tests, but need to test with JDK from blob storage). For other tasks depending on it (AzureVmssDeploymentV0) - checked that package updates won't be picked up automatically

### CODE REVIEW

**Review by max-zaytsev — APPROVED** [review]

**Review by KonstantinTyukalov — APPROVED** [review]

**Review by AndreyIvanov42 — APPROVED** [review]

**Comment by KonstantinTyukalov** [comment]
@anatolybolshakov  could you sign CLA?

**Review by mmrazik — APPROVED** [review]

**Pull request merged**
