### PR TITLE
Update codecoverage-tools package version in tasks that use it

### PR DESCRIPTION
**Pull request by golubev-ivan**
**Task name**: `ANTV1`, `GradleV2`, `GradleV3`, `MavenV2`, `MavenV3`, `PublishCodeCoverageResultsV1`

**Description**: Updated codecoverage-tools package version in tasks that use it.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped
- [x] Checked that applied changes work as expected

Test results (using canary tests):
- ANTV1 [results](https://dev.azure.com/v-igolubev/Test/_build/results?buildId=11&view=results)
- MavenV2-V3 [results](https://dev.azure.com/v-igolubev/Test/_build/results?buildId=12&view=results)
- GradleV2-V3 [results](https://dev.azure.com/v-igolubev/Test/_build/results?buildId=9&view=results)
- PublishCodeCoverageResultsV1 [results](https://dev.azure.com/v-igolubev/Test/_build/results?buildId=10&view=results)

### CODE REVIEW

**Review by EzzhevNikita — APPROVED** [review]

**Comment by EzzhevNikita** [comment]
@golubev-ivanHave you tested these tasks after updating them? Could you please share tests cases that you have checked and test results?

**Comment by anatolybolshakov** [comment]
@golubev-ivan LGTM, but as Nikita said - please make sure that we've properly tested these tasks and described checked cases. You can also use scenarios covered in e2e tests for these tasks.

**Comment by golubev-ivan** [comment]
I've tested the tasks after the update using the standard L0 and canary tests. I've shared test results in the description of this PR. Also, I've tried to manually test some tasks, but I couldn't to test them all.

**Review by anatolybolshakov — APPROVED** [review]
LGTM, thanks!

**Comment by golubev-ivan** [comment]
cc @geekzter for visibility

**Pull request merged**
