### PR TITLE
Remove outdated tests

### PR DESCRIPTION
**Pull request by LeftTwixWand**
**Task name**:

- AzureFileCopyV1
- AzureFileCopyV2
- AzureFileCopyV3
- AzureFileCopyV4
- AzureFileCopyV5
- WindowsMachineFileCopyV1
- WindowsMachineFileCopyV2

**Description**:
Remove unnecessary tests and references.

**Documentation changes required:** N

**Added unit tests:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by merlynomsft — APPROVED** [review]
:shipit:

**Review by LeftTwixWand — COMMENTED** [review]
I checked all 100 files and everything looks fine

**Pull request merged**
