### PR TITLE
Vulnerability fix for DownloadPackageV0 and NpmV1

### PR DESCRIPTION
**Pull request by v-mohithgc**
**Task name**:  DownloadPackageV0 and NpmV1

**Description**:  Fixed latest vulnerability 

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1936446/
https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1936445/

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected
- [x] node make.js build --task
- [x] node make.js test --task

### CODE REVIEW

**Comment by v-mohithgc** [comment]
@tintse-thxsky-MSFT @phil-hodgson @aasim can you please review and test this PR.
Thanks

**Comment by tintse-thxsky-MSFT** [comment]
looks good to me

**Review by tintse-thxsky-MSFT — APPROVED** [review]

**Review by tintse-thxsky-MSFT — COMMENTED** [review]
looks good to me, i will  do some final test then I will approve.

**Review by tintse-thxsky-MSFT — APPROVED** [review]
tested NpmV1 in a pipeline and it works as expected.

**Pull request merged**
