### PR TITLE
CG fix for AzureRmWebAppDeploymentV4

### PR DESCRIPTION
**Pull request by v-mohithgc**
**Task name**: AzureRmWebAppDeploymentV4

**Description**: <Describe your changes here>

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] node make.js build --task AzureRmWebAppDeploymentV4
- [x]  node make.js test --task AzureRmWebAppDeploymentV4
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by rvairavelu — APPROVED** [review]

**Review by rvairavelu — APPROVED** [review]

**Comment by ozanaydinMSFT** [comment]
#18361 just for referencing, I'm adding here.

**Pull request merged**
