### PR TITLE
SSH + Windows Agents issues - ##[error]bash: ./sshscript: No such file or directory

### PR DESCRIPTION
**Pull request by LuizMacedo**
**Task name**: SshV0 - https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/SshV0

**Description**: Bug fix.
Removing line endings using:
const removeLineEndingsCmd = `tr -d \'\\015\' <${remoteScriptPath}> ${windowsEncodedRemoteScriptPath}`;

Is generating errors as example:
##[error]bash: ./sshscript_4324: No such file or directory

Refactoring to:
`tr -d \'\\015\' <${remoteScriptPath}> ${windowsEncodedRemoteScriptPath}`;

It was tested and resolved the issue. 

**Documentation changes required:** No

**Added unit tests:** No

**Attached related issue:** No

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Comment by Ol-Father** [comment]
This has broken our release pipelines when our agents auto-updated to 2.175.2

Please get this fix out ASAP

**Comment by travispalmer** [comment]
We are also affected by this issue. Thanks to LuizMacedo for already submitting a fix!

**Comment by icloudmegam** [comment]
Any updates on this issue, we are facing the same issue when i run ssh in inline script mode i am getting error no such file or directory. I am using windows agent with version 2.170.1

**Comment by dglambert** [comment]
Same Here. 
See: 
Issue: https://github.com/microsoft/azure-pipelines-tasks/issues/13661
UserVoice: https://developercommunity.visualstudio.com/content/problem/1209307/ssh-run-shell-inline-script-on-remote-machine.html

**Comment by LuizMacedo** [comment]
Hello everyone. Please, check the new PG for the issue: https://github.com/microsoft/azure-pipelines-tasks/pull/13663

**Pull request closed without merging**
