### PR TITLE
Node6hotfixes/azure function app

### PR DESCRIPTION
**Pull request by agrataru**
**Task name**: AzureFunctionAppV1
**Description**: Adding changes for node 10 changes
* Updating the package version for node 10
* Updating the code path to include new path for azurermdeploycommon

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by AmrutaKawade — APPROVED** [review]

**Comment by ITSTord** [comment]
We see a behavior that this task ignores slotName: "value" and deploy it straight to production slot. This worked fine on friday. So our existing pipeline end up with deploy to prod and swap latest code into stage slot... not optimal :)

**Comment by ITSTord** [comment]
https://github.com/microsoft/azure-pipelines-tasks/commit/2f764c075f4dff0b163fd16fd6bf88581c6f2a76#diff-639c038189c01445c7a666c289f267ec6a6c77f7d90046ca6844965ff3bba6eb -> "azure-pipelines-tasks-azurermdeploycommon": "^2.0.3",

**Comment by AmrutaKawade** [comment]
> 2f764c0#diff-639c038189c01445c7a666c289f267ec6a6c77f7d90046ca6844965ff3bba6eb

Can you raise issue with logs? This diff is already part of "azure-pipelines-tasks-azurermdeploycommon": "^2.0.3" package

**Comment by ITSTord** [comment]
https://github.com/microsoft/azure-pipelines-tasks/issues/14639 problem were not related to the links above

**Pull request merged**
