### PR TITLE
[Node 10] Migrated AppCenterDistribute tasks

### PR DESCRIPTION
**Pull request by anatolybolshakov**
**Task name**: AppCenterDistributeV1-V3

**Description**: migrated AppCenterDistributeV1-V3 tasks to Node 10.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected - tested tasks with scenarios:
       - Simple app upload
       - Upload with 'Require users to update to this release' enabled
       - Upload with changed release notes

### CODE REVIEW

**Comment by anatolybolshakov** [comment]
cc @geekzter for visibility

**Review by EzzhevNikita — APPROVED** [review]

**Review by tatyana-kostromskaya — APPROVED** [review]

**Review by max-zaytsev — APPROVED** [review]

**Comment by ondrej-merkun-ms** [comment]
@anatolybolshakov Could you please resolve the failing tests? 🙂

**Comment by mpodriezov** [comment]
I am assigning this one to myself. I will try to figure out why the checks are failing.

**Review by ondrej-merkun-ms — APPROVED** [review]

**Review by vahalik — APPROVED** [review]

**Review by vahalik — CHANGES_REQUESTED** [review]
The task (v3) in current state does not work. It needs to be fixed.

**Review by vahalik — APPROVED** [review]

**Pull request merged**
