### PR TITLE
Removing validation check from AzurePowerShellV4

### PR DESCRIPTION
**Pull request by 20shivangi**

### CODE REVIEW

**Comment by andydkelly-ig** [comment]
This task has stopped working after this update. It was working fine for us until today - now we are receiving the error that this PR was meant to eradicate.

**Comment by Ajay-MS** [comment]
@andydkelly-ig 

These changes has not been yet deployed so this should not be ideally cause of the failure. Can you please share debug logs.

**Comment by andydkelly-ig** [comment]
ah - in that case we are now seeing the error this should resolve :) I worked around by changing Powershell V4 Task from "latest version" to 1.0.0

**Comment by JoeBrooker** [comment]
> ah - in that case we are now seeing the error this should resolve :) I worked around by changing Powershell V4 Task from "latest version" to 1.0.0

Fantastic @andydkelly-ig  - that has solved the problem for me!

**Pull request merged**
