### PR TITLE
Migrate DownloadFileshareArtifactsV0 task to Node10

### PR DESCRIPTION
**Pull request by golubev-ivan**
**Task name**: DownloadFileshareArtifactsV0

**Description**: Migrated DownloadFileshareArtifactsV0 task to Node10
- Execution handler is updated
- Typings are deleted

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped
- [x] Checked that applied changes work as expected

Test results:
- Local shared folder - [results](https://dev.azure.com/v-igolubev/Test/_build/results?buildId=20&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=a2d2fb52-f033-5f8e-5a30-3cd7959ea7c5)
- Not local shared folder - [results](https://dev.azure.com/v-igolubev/Test/_build/results?buildId=21&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=a2d2fb52-f033-5f8e-5a30-3cd7959ea7c5)

### CODE REVIEW

**Review by anatolybolshakov — APPROVED** [review]

**Review by v-nmursapall — APPROVED** [review]

**Review by EzzhevNikita — APPROVED** [review]

**Review by harshiniks — APPROVED** [review]

**Comment by harshiniks** [comment]
should I merge this?

**Comment by anatolybolshakov** [comment]
@harshiniks would it be possible for you to test these changes also - to make sure that it's all fine? We've tested it for some simple scenarios, but it would be great to check on some more complex cases.

**Comment by harshiniks** [comment]
> @harshiniks would it be possible for you to test these changes also - to make sure that it's all fine? We've tested it for some simple scenarios, but it would be great to check on some more complex cases.

@v-nmursapall  please do this and confirm when I should merge

**Comment by golubev-ivan** [comment]
cc @geekzter for visibility

**Comment by v-nmursapall** [comment]
Did a round of testing, looks good to me.

**Pull request merged**
