### PR TITLE
Deploy Connection Strings using Azure App Service Deploy

### LINKED ISSUE #9017: Deploy Connection Strings using Azure App Service Deploy
## Environment
- Server - Azure Pipelines   
- Agent - Hosted
    - Hosted VS2017
- Task - Azure App Service Deploy (Preview)
   - Version 4.* (preview)

## Issue Description

I am attempting to deploy connection strings to an Azure Function App. I am able to specify app settings, but cannot figure out how to make my connection string show up in the connection string settings. 

I would specify it manually through the Azure portal, but each new deployment wipes out the connection string, which would cause a manual step, which could be easily missed.

Is there a method of specifying a connection string for the connection strings settings?

### PR DESCRIPTION
**Pull request by mguirao**
Fixes #9017

### CODE REVIEW

**Comment by mguirao** [comment]
Do you have any script to bump the version of all related Tasks when modifying something common ?
Or should i do the bump manually ?

**Comment by mguirao** [comment]
I didn't create new tests for this feature, should i ?

**Comment by vincentdass** [comment]
@mguirao , thanks for your contribution 👍 
Can you please make the following changes in the PR?
We are planning to support the JSON format instead of PowerShell Argument for connection strings.
image

1)Ensure that the user have provided a valid JSON format that has name, value, type and slotSetting
2)Update the feature in four tasks (AzureWebAppV1, AzureFunctionAppV1, AzureWebAppContainerV1, AzureFunctionAppContainerV1) and not in AzureRmWerbAppDeploymentV4

**Comment by mguirao** [comment]
@vincentdass This is clearly a big change that you are asking, but i'm willing to have a look.
Also today i use the task AzureRmWerbAppDeploymentV4 in my release pipeline, do you mean that this task is deprecated and i should use AzureWebAppV1?

Is there any Task with a JSON format input that i could copy the logic ?

**Comment by vincentdass** [comment]
@eaarora-ms , Can you please take forward this feature request and make the relevant changes?

**Comment by RoshanKumarMicrosoft** [comment]
Already raised PR with this changes also [Link](https://github.com/microsoft/azure-pipelines-tasks/pull/11020)

**Pull request closed without merging**
