### PR TITLE
Escape dollar sign characters that may be in the arguments before calling iex

### PR DESCRIPTION
**Pull request by jsblock78**
**Task name**: Common\RemoteDeployer

**Description**: Escape dollar sign '$' characters that may exist in the arguments before calling Invoke-Expression

**Documentation changes required:** No

**Added unit tests:** No

**Attached related issue:** Yes - https://github.com/microsoft/azure-pipelines-tasks/issues/15560

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Comment by jsblock78** [comment]
Would System.Management.Automation.WildcardPattern.Escape be better? There are other cases where users could run into problems here, this fix only solved my specific issue.

**Review by v-ibshaik — APPROVED** [review]
Approved

**Pull request merged**
