### PR TITLE
Common Library Cumulative Update

### PR DESCRIPTION
**Pull request by ozanovus**
**Task name**: 
AzureAppServiceManageV0
AzureFileCopyV2
AzureFileCopyV3
AzureFileCopyV4
AzureFileCopyV5
AzureKeyVaultV1
AzureKeyVaultV2
AzureMysqlDeploymentV1
AzurePowerShellV4
AzurePowerShellV5
AzureResourceGroupDeploymentV2
AzureResourceManagerTemplateDeploymentV3
AzureRmWebAppDeploymentV3
AzureRmWebAppDeploymentV4
AzureSpringCloudV0
AzureVmssDeploymentV0
HelmDeployV0
JavaToolInstallerV0
JenkinsDownloadArtifactsV1
PackerBuildV0
SqlAzureDacpacDeploymentV1

**Description**: Cumulative version update for "azure-pipelines-tasks-azure-arm-rest-v2"

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

**Test results:** 
[Is L0 passed?] [Is manual end-to-end test passed?] TaskName

- [:white_check_mark:] [:white_check_mark:]  AzureAppServiceManageV0
image

- [:white_check_mark:][:white_check_mark:] AzureFileCopyV2
image

- [:white_check_mark:][:white_check_mark:] AzureFileCopyV3
image

- [:white_check_mark:][:white_check_mark:] AzureFileCopyV4
image

- [:white_check_mark:][:white_check_mark:] AzureFileCopyV5
image

- [:white_check_mark:][:white_check_mark:] AzureKeyVaultV1
image

- [:white_check_mark:][:white_check_mark:] AzureKeyVaultV2
image

- [:white_check_mark:][:white_check_mark:] AzureMysqlDeploymentV1
image

- [:white_check_mark:][:white_check_mark:] AzurePowerShellV4
image

- [:white_check_mark:][:white_check_mark:] AzurePowerShellV5
image

- [:white_check_mark:][:white_check_mark:] AzureResourceGroupDeploymentV2
image

- [:white_check_mark:][:white_check_mark:] AzureResourceManagerTemplateDeploymentV3
image

- [:white_check_mark:][:white_check_mark:] AzureRmWebAppDeploymentV3
image
Repeated test after Node16 revert: 
image

- [:white_check_mark:][:white_check_mark:] AzureRmWebAppDeploymentV4
image
Repeated test after Node16 upgrade:
image
 
- [:white_check_mark:][:white_check_mark:] AzureSpringCloudV0
image

- [:white_check_mark:] [:white_check_mark:] AzureVmssDeploymentV0
image

- [:white_check_mark:][:white_check_mark:] HelmDeployV0
image

- [:white_check_mark:][:white_check_mark:] JavaToolInstallerV0
image

- [:white_check_mark:][ ] JenkinsDownloadArtifactsV1
- [:white_check_mark:][:white_check_mark:] PackerBuildV0
image

- [:white_check_mark:][:white_check_mark:] SqlAzureDacpacDeploymentV1
image

### CODE REVIEW

**Comment by ozanovus** [comment]
DO NOT MERGE yet, Tests are in progress.

**Comment by onetocny** [comment]
I have just tested following tasks (G2). I can confirm that all of them works as expected.

- AzureMysqlDeploymentV1
- AzurePowerShellV4
- AzurePowerShellV5
- AzureResourceGroupDeploymentV2

**Comment by onetocny** [comment]
AzureVmssDeploymentV0 is failing when using MSAL ([see attached log](https://github.com/microsoft/azure-pipelines-tasks/files/10337344/ReleaseLogs_196.zip)). Task works as expected with `USE_MSAL=false`. I guess there is some discrepancy in API when using MSAL. The "No VMSS found with name onetocny-vmss001" message comes from [here](https://github.com/microsoft/azure-pipelines-tasks/blob/c378ae8a9afb87493a81fd68c16bdd3f65a68169/Tasks/AzureVmssDeploymentV0/operations/VirtualMachineScaleSet.ts#L27). Thus I believe that `ComputeManagementClient` does not handle MSAL requests properly.

**Comment by ozanovus** [comment]
> **AzureVmssDeploymentV0** is failing when using MSAL ([see attached log](https://github.com/microsoft/azure-pipelines-tasks/files/10337344/ReleaseLogs_196.zip)). Task works as expected with `USE_MSAL=false`. I guess there is some discrepancy in API when using MSAL. The "No VMSS found with name onetocny-vmss001" message comes from [here](https://github.com/microsoft/azure-pipelines-tasks/blob/c378ae8a9afb87493a81fd68c16bdd3f65a68169/Tasks/AzureVmssDeploymentV0/operations/VirtualMachineScaleSet.ts#L27). Thus I believe that `ComputeManagementClient` does not handle MSAL requests properly.

I've uploaded it with fresh environment (cleaning `node_modules` etc.)

It worked for both USE_MSAL scenarios.
Attempt 1:
image
image
image

Attempt 2:
image
image
image

**Review by manolerazvan — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Review by max-zaytsev — APPROVED** [review]

**Comment by ozanovus** [comment]
#17502 is causing failure, I'm waiting for it

**Pull request merged**
