### PR TITLE
Update link to IoT Edge docs in readme

### PR DESCRIPTION
**Pull request by kgremban**
**Task name**: AzureIoTEdgeV2

**Description**: Fixed broken link in the task readme

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by marianan — APPROVED** [review]
:shipit:

**Comment by kgremban** [comment]
@marianan @tameraw Do either of you have write access to this repository to merge this pull request?

**Comment by marianan** [comment]
@Jyotsna ***@***.***> - can you or someone on your team help merge this change? Tamer and I have no write access.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by kgremban** [comment]
@Josh-01 This is my first PR in this repo. Is there some step I'm missing to get the build pipelines to run? Or since this is just a readme file change, can it be merged without all the checks? Thank you.

**Comment by rajnish-byte** [comment]
@kgremban All required checks need to pass before we can complete the merge.

**Comment by marianan** [comment]
> @kgremban All required checks need to pass before we can complete the merge.

@rajnish-byte thanks for following up. The pipelines seem stuck, could you please retrigger them? This is a readme change so generally low risk. We would like to get it in sooner rather than later as users are getting confused because of the wrong links. Thanks for helping us with this.

**Comment by rajnish-byte** [comment]
@kgremban I guess there is a conflict, can you please check once. To be specific I see the changes added here at line 9 is already there in master.

**Comment by kgremban** [comment]
@rajnish-byte I'm not seeing a merge conflict. I did just update the branch against master. 

I did not make a change to line 9. I see this happen often on the last line of files; I believe it's if one editor handles end-of-file characters differently than another. The only change is to the URL in line 5, which is currently broken the way it is.

As Mariana mentioned, the pipelines aren't running. This pull request has been open for over a month and they've never completed, either successfully or unsuccessfully. I'm not sure if there's a step I've missed, or if it's because there are no code changes. If you would rather open your own pull request and just update the documentation URL, that would be fine with me.

**Review by rajnish-byte — APPROVED** [review]

**Comment by rajnish-byte** [comment]
Created new PR with these changes https://github.com/microsoft/azure-pipelines-tasks/pull/15354
@marianan Please approve this new PR.

**Pull request closed without merging**
