### PR TITLE
Vulnerability fix for AzureKeyVaultV2

### PR DESCRIPTION
**Pull request by Pranshu-Negi**
**Task name**: AzureKeyVaultV2

**Description**: 

**Documentation changes required:** (Y/N)

**Added unit tests:** (Y/N)

**Attached related issue:** (Y/N) https://dev.azure.com/mseng/PipelineTools/_componentGovernance/184/alert/79428?typeId=12858

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected
- [x] node make.js build --task AzureKeyVaultV2
- [x] node make.js test --task AzureKeyVaultV2

### CODE REVIEW

**Review by v-mohithgc — APPROVED** [review]
Tested and validated

**Review by v-nagarajku — APPROVED** [review]

**Pull request merged**
