### PR TITLE
Remove appcenter-cli from dependencies to solve security issues

### PR DESCRIPTION
**Pull request by alexey-chernikov**
**Task name**: AppCenterTestV1

**Description**: Update appcenter-cli dependency version
**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N
**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by alexey-chernikov** [comment]
Manually tested on private organization - the behavior didn't change

**Review by sergei-fedorov — APPROVED** [review]

**Review by andrii-z4i — APPROVED** [review]

**Comment by TheresasAccount** [comment]
@alexey-chernikov This seems to have caused app center test to start failing, can you investigate and/or roll back this change?

https://github.com/microsoft/azure-pipelines-tasks/issues/16484

**Pull request merged**
