### PR TITLE
Updated docs to reflect new vocabulary

### PR DESCRIPTION
**Pull request by PhilPeters304**
#10080 Simple change to the vocabulary used to avoid confusion

### CODE REVIEW

**Comment by SumiranAgg** [comment]
We might want to change it to pre-defined variables.
@vincentdass what is your thought on this?

**Comment by SumiranAgg** [comment]
@N-Usha Looping in to make suggestion.

**Comment by PhilPeters304** [comment]
From what I’ve seen, pre-defined variables are supported. I’ve used these successfully. It’s the variables set during the pipelines execution which are unsupported

**Comment by N-Usha** [comment]
Variable substitution is done only for those variables that are set in the pipeline definition or at queue time. As Sumiran suggested "predefined variables" are not supported during variable substitution.  https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
And "Pipeline variables" are those pre-defined variables which are specific to pipelines (just like build/release variables): https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#pipeline-variables
@PhilPeters304 - Could you please provide more details on how you have used the pre-defined variables for substitution?

**Comment by PhilPeters304** [comment]
Sorry yeah I got myself confused. I used a variable group to map for the predefined. Happy to close the pr with no action, I just felt it wasn’t clear but it’s fine either way!

**Pull request closed without merging**
