### PR TITLE
Migrate PipAuthenticateV0 and PipAuthenticateV1 to node10

### PR DESCRIPTION
**Pull request by denis-tikhomirov**
**Task name**: PipAuthenticateV0 and PipAuthenticateV1

**Description**: this pull request provides updating the PipAuthenticateV0 and PipAuthenticateV1 tasks and their migration to Node 10

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by denis-tikhomirov** [comment]
Changes in the PR are prepared to migrate tasks PipAuthenticateV0 and PipAuthenticateV1 to Node10.
@phil-hodgson, @aasim, @satbai, could you please help with testing of the changes? I see in code owners list that you are owners of the task.

**Comment by denis-tikhomirov** [comment]
@mmrazik, please take a look at the PR.

**Review by anatolybolshakov — APPROVED** [review]

**Review by mmrazik — APPROVED** [review]
Please bump the version to 205 before merging.

**Review by mpodriezov — APPROVED** [review]

**Pull request merged**
