### PR TITLE
Adding `kubernetes rollout status` command to be able to read a rollo…

### PR DESCRIPTION
**Pull request by omg-a-bear**
Adding `kubernetes rollout status` command to be able to read a rollout, or track a rollout using `--watch`. This enables blue/green deploy workflows more easily.

### CODE REVIEW

**Comment by omg-a-bear** [comment]
@Anumita

**Comment by omg-a-bear** [comment]
The last commit adds rollout undo to commands in KubernetesV1 task.

It might be of use when wanting to rollback a deployment during a failed build. [kubectl reference](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-undo-em-)

**Comment by bansalaseem** [comment]
can you please resolve the conflicts?

**Comment by omg-a-bear** [comment]
Conflicts resolved, @bansalaseem .

**Comment by vithati** [comment]
@omg-a-bear , 'Command' input is editable, you can type any command. Command arguments you can give in 'Arguments' inputs like shown in screen shot. if command not supports '-o' flag, keep 'Output format' blank like shown in screen shot.

image

**Pull request closed without merging**
