### PR TITLE
Upgrade DownloadGitHubNugetPackageV1 to NodeJS16

### PR DESCRIPTION
**Pull request by Roman-Shchukin**
**Task name**: DownloadGitHubNugetPackageV1

**Description**: Task upgraded to node16

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** https://github.com/microsoft/build-task-team/issues/3722

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by v-mohithgc — APPROVED** [review]
Tested, @Roman-Shchukin  plz bump the task minor version to 217

**Review by KonstantinTyukalov — APPROVED** [review]

**Review by DmitriiBobreshev — APPROVED** [review]

**Comment by vmapetr** [comment]
Hi @v-mohithgc, we updated the common-package versions used in this task and planning to merge this PR in this sprint, so could you please test it again, since we don't have proper use cases?

**Review by kirill-ivlev — APPROVED** [review]

**Review by tkasparek — APPROVED** [review]

**Review by tkasparek — APPROVED** [review]

**Comment by vmapetr** [comment]
Hi @v-mohithgc, do you had a chance to validate the changes, so we can merge this PR?

**Comment by vmapetr** [comment]
Closing this PR since the changes were merged here - https://github.com/microsoft/azure-pipelines-tasks/pull/18396

**Pull request closed without merging**
