### PR TITLE
Ability to run scripts in PowerShell Core if present

### PR DESCRIPTION
**Pull request by senthilkungumaraj**
Azure Powershell v4 does not support PowerShell Core in windows Agents. I've modified the task to use PowerShell Core if present and then fall back to PowerShell if PowerShell Core is not present.

### CODE REVIEW

**Comment by senthilkungumaraj** [comment]
Unable to add reviewers to this PR. Can you please help me add a reviewer? This PR is related to the open issue below:

https://github.com/microsoft/azure-pipelines-tasks/issues/10328

**Comment by senthilkungumaraj** [comment]
I'm reviewing the failed test cases. Will get back after fixing the failed test cases.

**Comment by RoshanKumarMicrosoft** [comment]
Adding @20shivangi for approval

**Comment by RoshanKumarMicrosoft** [comment]
Some action item is pending on PR.

**Comment by SumiranAgg** [comment]
This will break existing windows powershell scenarios. We have taken your feedback and are working on adding this feature to the task. Closing this PR.

**Pull request closed without merging**
