### PR TITLE
Fixed latest Vulnerabilities related to Babel/traverse

### PR DESCRIPTION
**Pull request by v-mohithgc**
**Task name**: DownloadFileshareArtifacts, DownloadBuildArtifacts, AzureVmssDeployment, JenkinsDownloadArtifacts

**Description**: Bumped root dependency "Artifact-Engine" which fixed latest Vulnerabilities related to Babel/traverse

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** WI 2115038, 2115020

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by PhilipsonJoseph** [comment]
@v-mohithgc for the task DownloadBuildArticatsV0 i could see the package.json file is missing on this commit ? Is it already merged with some other PR ?

**Comment by v-mohithgc** [comment]
> @v-mohithgc for the task DownloadBuildArticatsV0 i could see the package.json file is missing on this commit ? Is it already merged with some other PR ?

yes, it's been merged with previous PR, https://github.com/microsoft/azure-pipelines-tasks/pull/19266

**Review by manolerazvan — APPROVED** [review]

**Pull request closed without merging**
