### PR TITLE
Avoid generating 'base' configs when not needed; MavenV3 Node20 added

### PR DESCRIPTION
**Pull request by merlynomsft**
Previously, when a Node20 build config the following would be generated:

_generated/XamariniOSV2\**
_generated/XamariniOSV2_Node20\**

With these changes, only the following is generated:

_generated/XamariniOSV2_Node20\**

### CODE REVIEW

**Review by tkasparek — APPROVED** [review]

**Comment by qianz2** [comment]
Should we revert this PR?

**Pull request merged**
