### PR TITLE
Reverted OSS dependencies update for DownloadBuildArtifactsV0 task due to breaking change in decompress-zip

### PR DESCRIPTION
**Pull request by anatolybolshakov**
**Task name**: DownloadBuildArtifactsV0

**Description**: Reverted changes of [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/14703) due to regression related to DownloadBuildArtifactsV0 update. There is some breaking change in decompress-zip patch update (v0.3.0 -> v0.3.3) causing the issue - we need to investigate it further.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by DaniilShmelev — APPROVED** [review]

**Review by EzzhevNikita — COMMENTED** [review]
Are we going to revert both DownloadBuildArtifactsV0 and JavaToolInstallerV0 tasks?

**Comment by anatolybolshakov** [comment]
> Are we going to revert both DownloadBuildArtifactsV0 and JavaToolInstallerV0 tasks?

No, there is only an issue with decompress-zip relevant to DownloadBuildArtifacts tasks - I updated description a little bit.

**Comment by EzzhevNikita** [comment]
> > Are we going to revert both DownloadBuildArtifactsV0 and JavaToolInstallerV0 tasks?
> 
> No, there is only an issue with decompress-zip relevant to DownloadBuildArtifacts tasks - I updated description a little bit.

In this way, it makes sense to remove changes for JavaToolInstallerV0 from this PR

**Comment by anatolybolshakov** [comment]
> > > Are we going to revert both DownloadBuildArtifactsV0 and JavaToolInstallerV0 tasks?
> > 
> > 
> > No, there is only an issue with decompress-zip relevant to DownloadBuildArtifacts tasks - I updated description a little bit.
> 
> In this way, it makes sense to remove changes for JavaToolInstallerV0 from this PR

I see thanks! Fixed it

**Review by EzzhevNikita — APPROVED** [review]

**Review by alexander-smolyakov — APPROVED** [review]

**Pull request merged**
