### PR TITLE
Vulnerability fix for utility-common and utility-common-v2

### PR DESCRIPTION
**Pull request by v-mohithgc**
**Task name**: utility-common

**Description**: Fixed latest vulnerability 

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) https://dev.azure.com/mseng/PipelineTools/_componentGovernance/184/alert/68445?typeId=12858

**Checklist**:
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by rajnish-byte — APPROVED** [review]

**Review by mpodriezov — APPROVED** [review]

**Comment by v-nagarajku** [comment]
plz do /azp run

**Pull request closed without merging**
