### PR TITLE
Revert "Added Microsoft Go tool support (#19000)"

### PR DESCRIPTION
**Pull request by dagood**
This reverts commit 3d8da0034dda3f76465e7931438363f120a4e3d6 (PR https://github.com/microsoft/azure-pipelines-tasks/pull/19000)

**Task name**: GoToolV0

**Description**: The effort is appreciated, but the microsoft/go team has concerns about using a dropdown--see https://github.com/microsoft/azure-pipelines-tasks/pull/19000#pullrequestreview-1638445480.

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

/cc @ozanaydinMSFT @shueybubbles @v-mohithgc @rvairavelu @manolerazvan @LeftTwixWand

### CODE REVIEW

**Comment by dagood** [comment]
I think after merging this, https://github.com/microsoft/azure-pipelines-tasks/pull/18681 could be reopened? I'm not sure if it was considered ready to go or still needed some work.

**Comment by v-mohithgc** [comment]
@dagood please bump the minor version to 229 and patch to 1 (ie 0.229.1), will proceed to merge.
Thanks

**Comment by shueybubbles** [comment]
@v-mohithgc if you can revive #18681 it should achieve the goal. thx!

**Comment by dagood** [comment]
@v-mohithgc I've added the version bump, thanks.

**Comment by v-mohithgc** [comment]
> @v-mohithgc I've added the version bump, thanks.

Thanks, can you please bump the version (0.229.1) in task-loc.json as well.

**Review by rvairavelu — APPROVED** [review]

**Review by v-mohithgc — APPROVED** [review]

**Pull request merged**
