### PR TITLE
AzureFunctionApp@2: Better alias for Service Connection

### PR DESCRIPTION
**Pull request by nis-spiir**
**Task name**: AzureFunctionApp@2

**Description**: "Azure Subscription" is a terrible variable name for something that is not an Azure Subscription.

**Documentation changes required:** Y  (adds alias, so auto-generated docs needs to be updated)

**Added unit tests:** N

**Attached related issue:** Y https://github.com/MicrosoftDocs/azure-devops-docs/issues/13281

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by FinVamp1 — COMMENTED** [review]
Hello, 

I'm the owner of the Azure Functions deployment tasks. 
Was there something that prompted this change?

This syntax is common to a lot of other tasks and changing the parameter in such a manner has a level of risk in relation to breaking existing pipelines, samples, templates etc?

For these reasons I would prefer not to make such a change.

Thanks, 

Finbar

**Comment by nis-spiir** [comment]
Hey @FinVamp1 

What prompted this PR is https://github.com/MicrosoftDocs/azure-devops-docs/issues/13281

I'm seeing a lot of developers being confused about "service connections" especially when connecting to Azure where "azureSubscription" should not be the name of an Azure Subscription 🙃 

It seems like "azureSubscription" is a legacy name? I see that even in this task you directly map the public `azureSubscription` input to `connectedServiceName` so clearly "azureSubscription" is not a logical name for that parameter (see https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureFunctionAppV2/taskparameters.ts#LL21C17-L21C17 )


> This syntax is common to a lot of other tasks

Actually not, I just checked (`find Tasks/ -iname task.json | xargs cat | jq '.inputs | .[] | select(.name == "azureSubscription", .name == "connectedServiceName", .name == "connectedServiceNameARM") | .name'`) and these are the stats:

There are 5 tasks with `azureSubscription` being the primary variable name (i.e. this task one of them)

There are 7 tasks with `connectedServiceName` being the primary variable name

There are 9 tasks with `connectedServiceNameARM` being the primary variable name


> changing the parameter in such a manner has a level of risk in relation to breaking existing pipelines, samples, templates etc?

I can't find anywhere that documents this will break stuff? Adding a new alias should be backwards compatible, but the script generating docs will now list (a better) variable name.

**Comment by v-nagarajku** [comment]
@nis-spiir  Please rebuild the task and run the test cases again and check if any of the test cases failing in the repo.

**Comment by v-nagarajku** [comment]
@nis-spiir Can you please bump the version of the task. I could see the current version of the task is same as the one in PR.

**Comment by FinVamp1** [comment]
azp /run

**Comment by nis-spiir** [comment]
Do I need to do anything more to get this merged?
The error [1] seems to indicate that build fails due to a pipeline problem (and not this PR)?

[1] `Cannot access to https://feeds.dev.azure.com/mseng/PipelineTools/_apis/packaging/Feeds/DistributedTasks/packages?api-version=7.0&includeAllVersions=true due to error Error: Failed request: (401)`

**Comment by v-nagarajku** [comment]
@nis-spiir I have cloned the same file changes from this PR and created a new PR https://github.com/microsoft/azure-pipelines-tasks/pull/18522 from my local system and checks are getting succeeded. Feel free to review PR changes.

cc: @FinVamp1

**Comment by v-nagarajku** [comment]
Before:
image

After:
image

Here the only change is from **Azure subscription** to **Azure Resource Manager connection** is it right?

cc: @nis-spiir @FinVamp1

**Comment by v-nagarajku** [comment]
Closed this PR as clone of this has been merged. https://github.com/microsoft/azure-pipelines-tasks/pull/18522

**Pull request closed without merging**
