### PR TITLE
Upgrade DotNetCoreInstallerV0 to NodeJS16

### PR DESCRIPTION
**Pull request by Pranshu-Negi**
**Task name**: DotNetCoreInstallerV0

**Description**: <Describe your changes here>
- Upgraded @types/node, azure-pipelines-task-lib and azure-pipelines-tool-lib 
- bumped task version
- Added node16 execution handler

**Documentation changes required:** N

**Added unit tests:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by v-schhabra — COMMENTED** [review]
Tested and approved.

**Review by PhilipsonJoseph — APPROVED** [review]

**Pull request merged**
