### PR TITLE
Support Auto Generate HTML for Cobertura

### PR DESCRIPTION
**Pull request by nigurr**

### CODE REVIEW

**Comment by IOrlandoni** [comment]
If `autogenerateHtmlReport` is set to false (`codeCoverageTool === 'cobertura'`, for example, or any other), `tempFolder` stays undefined, and passed to 'ccPublisher.publish()', instead of actually resolving the `reportDirectory` and using it. Is this intentional? This is, I believe, the cause for #10094

**Comment by nigurr** [comment]
> If `autogenerateHtmlReport` is set to false (`codeCoverageTool` set to `'cobertura'`, for example, or any other), `tempFolder` stays undefined, and passed to `ccPublisher.publish()`, instead of actually resolving the `reportDirectory` and using it. Is this intentional? This is, I believe, the cause for #10094

Fixing here
https://github.com/Microsoft/azure-pipelines-tasks/issues/10094

**Comment by VijayManchi** [comment]
I am running into an issue where the PublishCodeCoverageResults task fails saying this "##[warning]Please install dotnet core to enable automatic generation of Html report.". 

What I have in my .yml file is this
  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    displayName: Publish Code Coverage
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/coverage.xml'
      failIfCoverageEmpty: true

Where should I install dotnet core to take advantage of this automation html coverage generation?

**Comment by acesiddhu** [comment]
@VijayManchi do you have your own private agents for running builds? if yes you need to install .net core on that machine.

**Pull request merged**
