### PR TITLE
Bumped lodash dev in common-npm-packages/AzureRmDeploy-common-v3/Tests

### PR DESCRIPTION
**Pull request by sbalia**
**Task name**: common-npm-packages/AzureRmDeploy-common-v3/Tests

**Description**: 
Versions of lodash before 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep allows a malicious user to modify the prototype of Object via {constructor: {prototype: {...}}} causing the addition or modification of an existing property that will exist on all objects.

**Documentation changes required:** N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by PavloAndriiesh — CHANGES_REQUESTED** [review]
Please bump the task version according to the [instruction](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/taskversionbumping.md)

**Review by PavloAndriiesh — CHANGES_REQUESTED** [review]
There is some inconsistency here. You bumped versions in Tasks/Common/AzureRmDeploy-common task but didn't update anything there. You only updated dependency to the common-npm-packages/AzureRmDeploy-common-v3 task. It should be consistent.

**Review by PavloAndriiesh — CHANGES_REQUESTED** [review]
Please do not update root package.json for the task if you only updated Tests folder.

**Review by TomasHubelbauer — APPROVED** [review]

**Comment by sbalia** [comment]
solved in https://github.com/microsoft/azure-pipelines-tasks/pull/16395

**Pull request closed without merging**
