### PR TITLE
Made "LatestVersion" the default version for Azure PowerShell tasks.

### PR DESCRIPTION
**Pull request by JohnMcGlynnMSFT**
This change eliminates extra manual steps when creating a new task for the average case. It is helpful for experimenting, testing, changing versions of the task, and well-known release environments.

### CODE REVIEW

**Comment by SumiranAgg** [comment]
@JohnMcGlynnMSFT We cannot change default value for a  task input since it breaks existing pipelines. To change default behavior of a task we need to release a new major version.

**Comment by 20shivangi** [comment]
@JohnMcGlynnMSFT Should we close it ?

**Comment by 20shivangi** [comment]
@JohnMcGlynnMSFT Any update ?

**Comment by 20shivangi** [comment]
closing the PR

**Pull request closed without merging**
