### PR TITLE
Deprecate tasks [part 2]

### PR DESCRIPTION
**Pull request by aleksandrlevochkin**
**Task names**: 

- AzureCloudPowerShellDeployment@1	
- AzureCloudPowerShellDeployment@2
- AzureFileCopy@1	
- AzureFileCopy@2
- AzureFileCopy@3
- AzureFunctionOnKubernetes@0	
- AzureKeyVault@1	
- AzureNLBManagement@1	
- AzurePowerShell@2	
- AzurePowerShell@3
- Docker@0
- DuffleInstaller@0	
- FileTransform@1
- GitHubRelease@0
- HelmInstaller@0

**Description**: Marked the tasks as deprecated

**Documentation changes required:** Docs should update automatically

**Attached related issue:** [AB#2149149](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2149149)

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by manolerazvan — APPROVED** [review]

**Review by DergachevE — APPROVED** [review]

**Review by vmapetr — APPROVED** [review]

**Comment by Penguinwizzard** [comment]
My team has encountered some of these messages, and were interested in knowing more about the deprecations:
* Why are the old tasks deprecated?
* What benefits can we expect with the new tasks?
* Have our runs using the old task versions accrued some particular risk before doing the update?
* What's the timeline for disablement for the old tasks?

Is there any chance that the deprecation messages can be updated with some of this info, or a link to a place to find this info?

**Comment by aleksandrlevochkin** [comment]
Hi @Penguinwizzard!

**1** - Usually, a task is deprecated when a newer major version is available, or it is used for an obsolete service
**2 and 3** - I think it depends on the task, which ones in particular do you have in mind? 
**4** - The deprecated tasks will be retired later, once their usage decreases. The removal date will be announced in advance

**Comment by Penguinwizzard** [comment]
The one from this particular change that came up with my team was the AzureKeyVault@1 deprecation in favor of AzureKeyVault@2. The message we got, as defined in this PR, was

> The AzureKeyVault@1 task is deprecated, please use the latest version of the AzureKeyVault task

I think that a better message would be something along the lines of

> The AzureKeyVault@1 task is deprecated, due to an issue with handling encodings as detailed in https://github.com/microsoft/azure-pipelines-tasks/pull/14259. Please migrate to AzureKeyVault@2 or later for continued support.

This way we get a bit of an idea about the proximate motivation for the change, an impression of the rough scale of work needed to evaluate the change (basically just validating that our secrets still decode as expected), and an indication that the benefit is not only continued support but also better handling of some edge cases.

**Comment by topcat9131** [comment]
The `AzureKeyVault@1 task is deprecated, please use the latest version of the AzureKeyVault task` warning is displayed when using variable group connected to a key vault.

image

**Pull request merged**
