### PR TITLE
Drop gulp build, it's stale and currently we use make.js

### PR DESCRIPTION
**Pull request by pablonete**
I've reviewed our build steps and didn't see any usage of gulp.
https://dev.azure.com/mseng/PipelineTools/_build?definitionId=7634&_a=summary

I want this removal to be double-checked before merging, @bryanmacfarlane @moswald @austin-jensen 
If this goes in, we can abandon [PR #8886](https://github.com/Microsoft/azure-pipelines-tasks/pull/8886)

### CODE REVIEW

**Comment by pablonete** [comment]
I've run full build locally successfully. This is ready to merge.

**Comment by damccorm** [comment]
Queued a [manual build](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=8710090) to verify this for all tasks, but I don't see any way this would cause issues. Assuming the build is successful I think we should take this.

**Comment by stephenmichaelf** [comment]
Agreed. Once a full build passes I am OK with merging.

**Comment by damccorm** [comment]
The [build](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=8710090) was successful, I'll go ahead and merge!

**Pull request merged**
