### PR TITLE
Add data_api_location as input to AzureStaticWebAppV0 task

### PR DESCRIPTION
**Pull request by joslinmicrosoft**
**Task name**: StaticWebAppsV0<Name of changed or new pipeline task>

**Description**: Added input for data api location <Describe your changes here>

**Documentation changes required:** (Y/N) Y <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) N <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) N <Please add link to related issue here>

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by mishapos — APPROVED** [review]

**Review by mishapos — APPROVED** [review]

**Comment by mmrazik** [comment]
Can you also bump the version of the task?
Thanks!

**Comment by joslinmicrosoft** [comment]
> Can you also bump the version of the task? Thanks!

@mmrazik done!

**Review by mishapos — APPROVED** [review]

**Review by mmrazik — APPROVED** [review]

**Pull request merged**
