### PR TITLE
Go down to one definition. Use new syntax.

### PR DESCRIPTION
**Pull request by stephenmichaelf**
Trying to combine down to one definition and use new syntax.

### CODE REVIEW

**Comment by ericsciple** [comment]
looks good

**Comment by ericsciple** [comment]
Let's follow up and fix build single (needed before we branch for 143).

We don't need a separate job anymore (collapsed to one def). Publishing steps should produce the hotfix package (might be different steps).

**Comment by stephenmichaelf** [comment]
I am going to leave this for now and start a new PR, we are going to keep 3 definitions for the moment.

**Comment by stephenmichaelf** [comment]
Resolved in different PR.

**Pull request closed without merging**
