### PR TITLE
[SSHV0] Fix bash: No such file or directory issue

### PR DESCRIPTION
**Pull request by alexander-smolyakov**
**Task name**:  SSHV0

**Description**: 
This PR fixes `bash: No such file or directory` problem when ssh task running on windows agent.

_Changes:_
- Fixed problem with the naming of script file on remote host.
- All logic for remove Windows CR LF from the script file was extracted to separate function
- Updated comments for source code
- Removed extra variables

**Documentation changes required:** No

**Added unit tests:** No

**Attached related issue:** 
- https://github.com/microsoft/build-task-team/issues/286
- https://github.com/microsoft/azure-pipelines-tasks/issues/13661

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by sdobrodeev — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Review by egor-bryzgalov — APPROVED** [review]

**Comment by gamullen** [comment]
When will this be GA for customers? One of my customers is hitting this, and it's a showstopper for them.

**Comment by anatolybolshakov** [comment]
Hi @gamullen we are going to roll out the fix here soon, approximately today or tomorrow

**Comment by dglambert** [comment]
:pray:

**Comment by dglambert** [comment]
Is there another place where we can monitor the progress of this deployment?

**Comment by JaredMacDonald** [comment]
This issue is currently blocking one of my clients pipeline as well.  Is there some way to check whether this fix has been deployed or not?

**Comment by alexander-smolyakov** [comment]
@JaredMacDonald we are already rolled out a fix, could you please verify with a customer that the issue resolved now?

**Comment by gamullen** [comment]
My customer sent me an email this morning indicating that it works now. Thanks for the quick turnaround and transparency on timelines!

**Comment by DD202** [comment]
It appears that this is a breaking change. When using 'script file' from a windows machine, the copy and translate adds the ._unix suffix but the script execution is done against the original named file.

2020-10-07T20:47:12.4253710Z ==============================================================================
2020-10-07T20:47:12.4254232Z Task         : SSH
2020-10-07T20:47:12.4254644Z Description  : Run shell commands or a script on a remote machine using SSH
2020-10-07T20:47:12.4255853Z Version      : 0.176.1
2020-10-07T20:47:12.4256205Z Author       : Microsoft Corporation
2020-10-07T20:47:12.4256645Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh
2020-10-07T20:47:12.4257245Z ==============================================================================
2020-10-07T20:47:13.7780316Z Trying to establish an SSH connection to ***@XXXXXXXX:50000
2020-10-07T20:47:15.5265595Z Successfully connected.
2020-10-07T20:47:19.7455791Z tr -d '\015' <./xxxx-xxxx_xxxx.sh> ./xxxx-xxxx_xxxx.sh._unix
2020-10-07T20:47:20.1804069Z ##[error]bash: ./xxxx-xxxx_xxxx**.sh**: No such file or directory


**In the prior version it did the following:**
2020-10-06T19:45:29.4908565Z Task         : SSH
2020-10-06T19:45:29.4908928Z Description  : Run shell commands or a script on a remote machine using SSH
2020-10-06T19:45:29.4909256Z Version      : 0.175.0
2020-10-06T19:45:29.4909553Z Author       : Microsoft Corporation
2020-10-06T19:45:29.4909956Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh
2020-10-06T19:45:29.4910388Z ==============================================================================
2020-10-06T19:45:29.9348162Z Trying to establish an SSH connection to ***@XXXXXXXXX:50000
2020-10-06T19:45:31.3996584Z Successfully connected.
2020-10-06T19:45:35.1297514Z tr -d '\015' <"./XXX_XXX-XXX.sh"> "./XXX_XXX-XXX.sh._unix"
2020-10-06T19:45:35.4913788Z chmod +x "./XXX_XXX-XXX.sh._unix"
2020-10-06T19:45:35.8528401Z "./XXX_XXX-XXX.**sh._unix"**

**Comment by ronniemacapobre** [comment]
We are also encountering the same issue described by @DD202

**Comment by JaredMacDonald** [comment]
> @JaredMacDonald we are already rolled out a fix, could you please verify with a customer that the issue resolved now?

Yes, this is fixed for my customer. Thanks!

**Comment by anatolybolshakov** [comment]
Hi @ronniemacapobre, we still have some issues with rolling out these changes for all customer, we are currently working on this and let you know once we complete it - sorry for inconvenience here

**Comment by ronniemacapobre** [comment]
> Hi @ronniemacapobre, we still have some issues with rolling out these changes for all customer, we are currently working on this and let you know once we complete it - sorry for inconvenience here

Thanks for the update @anatolybolshakov. Should we update the build agent to pull the fix once the roll out is complete?

**Comment by devnetkc** [comment]
This has caused new troubles

List of runs yesterday when it failed. This pipeline runs every 4hrs to fetch changes. Nothing changed on our end on either side -- remote or local.

Screen Shot 2020-10-08 at 10 10 36 AM

Last successful run time

Screen Shot 2020-10-08 at 10 51 04 AM

Screen Shot 2020-10-08 at 10 16 45 AM

First failed run time

Screen Shot 2020-10-08 at 10 19 50 AM

Screen Shot 2020-10-08 at 10 16 32 AM


## Actual log output:

````bash
Starting: pullChanges
==============================================================================
Task         : SSH
Description  : Run shell commands or a script on a remote machine using SSH
Version      : 0.176.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh
==============================================================================
Trying to establish an SSH connection to ***@**
Successfully connected.
tr -d '\015' <./wp-git-sync.sh> ./wp-git-sync.sh._unix
##[error]bash: ./wp-git-sync.sh: No such file or directory

##[error]Command failed with errors on remote machine.
Finishing: pullChanges
````

````bash
Last completed successful log

Starting: pullChanges
==============================================================================
Task         : SSH
Description  : Run shell commands or a script on a remote machine using SSH
Version      : 0.175.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh
==============================================================================
Trying to establish an SSH connection to ***@**
Successfully connected.
tr -d '\015' <"./wp-git-sync.sh"> "./wp-git-sync.sh._unix"
chmod +x "./wp-git-sync.sh._unix"
"./wp-git-sync.sh._unix" -fo "https://***:***@***rc" -pd "/home/***/public_html/rc" -fe
Remote DevOps not found

Fetching devops
````

**Comment by alexander-smolyakov** [comment]
> Hi @ronniemacapobre, we still have some issues with rolling out these changes for all customer, we are currently working on this and let you know once we complete it - sorry for inconvenience here

The fix should be available for all Azure DevOps users now, please verify that the issue is resolved now and let us know if there are still any issues.

**Pull request merged**
