### PR TITLE
Migrate NuGetToolInstallerV1 task to Node10

### PR DESCRIPTION
**Pull request by mr-dokara**
**Task name**: NuGetToolInstallerV1

**Description**: Migrated task to Node10

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by anatolybolshakov — APPROVED** [review]

**Review by EzzhevNikita — APPROVED** [review]

**Comment by golubev-ivan** [comment]
cc @geekzter for visibility

**Comment by golubev-ivan** [comment]
Hi @aasim, @phil-hodgson, Could you please take a look at this PR?

**Review by vmapetr — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Pull request merged**
