### PR TITLE
[DownloadPipelineArtifactV2] Add minimumBuildStatus property

### PR DESCRIPTION
**Pull request by Thilas**
@jahsu-MSFT, @johnterickson, as discussed in #11556, here are my changes that add a `minimumBuildStatus` property to the DownloadPipelineArtifactV2 task.

### CODE REVIEW

**Comment by Thilas** [comment]
Related changes: https://github.com/microsoft/azure-pipelines-agent/pull/2560

**Comment by Thilas** [comment]
@jahsu-MSFT, do you mean in the `task.json` file? I thought this part was automatic.

**Comment by jahsu-MSFT** [comment]
Yes in the task.json file. This will need to be updated manually. 
image

**Comment by Thilas** [comment]
@jahsu-MSFT, done.

**Comment by jahsu-MSFT** [comment]
Since the DPA V2 version got updated in master. (It's 2.1.0 now) You will need to update to 2.2.0 so the task will get updated after the code is merged. Thanks.

**Comment by Thilas** [comment]
@jahsu-MSFT, it is done.

**Comment by johnterickson** [comment]
@Thilas thanks for the contribution! 🙌

**Comment by jahsu-MSFT** [comment]
@Thilas the new agent version should be released next week and the deployment process should be able to complete by next Friday. We will fix the conflicts, update the min-agent version and then merge the task PR by then. :) Thanks again for contributing.

**Comment by Thilas** [comment]
@jahsu-MSFT, that's great news! Let me know if you want me to do any of these actions, I really don't mind. And thank you for your support on this PR.

**Comment by jahsu-MSFT** [comment]
@Thilas Sure. By we I mean you and us. Can you please sync with master again, bump the task version one more time if needed, and update the min-agent version to 2.161.0? 
Thanks,

**Comment by Thilas** [comment]
@jahsu-MSFT, it's done. FYI I didn't need to bump the version since it was 2.1.2 (formerly 2.1.0) and we already set it to 2.2.0. I'll let you do the final magic 😉

**Comment by jahsu-MSFT** [comment]
Looks good to me. Thanks again for contributing @Thilas  
I'm going to merge the PR. Since we won't be deploying on the Thanksgiving week, the code should be deployed on the first week of December. :)

**Comment by Thilas** [comment]
Thanks again for your support @jahsu-MSFT.

**Comment by StefanSchoof** [comment]
This PR has broken our Pipeline. The Agent Version in the hosted image in west Europe is 2.160.1 and ad this set the required Version to 2.161.

**Comment by jahsu-MSFT** [comment]
@StefanSchoof Thanks for reporting. Yes, there was a glitch of the timing when agent was released and when this task was released. Sorry for the inconvenience. I believe this issue has been resolved now. Please let us know if you're still seeing any issues.

**Comment by StefanSchoof** [comment]
@jahsu-MSFT Thanks, now the Agent is on 2.163.1 and everything is working.

**Pull request merged**
