### PR TITLE
Use latest azure-pipelines-tasks-webdeployment-common for pipeline tasks

### PR DESCRIPTION
**Pull request by nagarajku**
**Task names**: 

- AzureFunctionAppContainer@1
- AzureFunctionApp@1
- AzureFunctionApp@2
- AzureMysqlDeployment@1
- AzureWebAppContainer@1
- AzureWebApp@1
- FileTransform@1
- FileTransform@2
- MysqlDeploymentOnMachineGroup@1

**Description**: Bump the webdeployment-common package version to fix the "Malicious entry" issue

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** https://github.com/microsoft/azure-pipelines-tasks/issues/20168

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by aleksandrlevochkin — CHANGES_REQUESTED** [review]
Please, bump the task version in task/task.loc files for AzureFunctionAppV2

**Review by aleksandrlevochkin — COMMENTED** [review]
I see AzureSpringCloudV0 also uses webdeployment-common v4.242.0. Could we update the package for that task as well?

**Review by aleksandrlevochkin — COMMENTED** [review]
Tasks for sprint 243 have already been released: https://github.com/microsoft/azure-pipelines-tasks/releases/tag/v243, I think we should bump the versions to 244

**Comment by nagarajku** [comment]
> Tasks for sprint 243 have already been released: https://github.com/microsoft/azure-pipelines-tasks/releases/tag/v243, I think we should bump the versions to 244

@aleksandrlevochkin tried to bump the version to 244, but after doing build tasks were automatically bumping to 243 and latest patch version.

**Comment by aleksandrlevochkin** [comment]
@nagarajku As a workaround you can manually set the 244 version in the `_generated/{Task_Name}.versionmap.txt` file and then run the build command

**Comment by nagarajku** [comment]
> @nagarajku As a workaround you can manually set the 244 version in the `_generated/{Task_Name}.versionmap.txt` file and then run the build command

@aleksandrlevochkin made the changes and did a commit

**Comment by nagarajku** [comment]
> Please, bump the task version in task/task.loc files for AzureFunctionAppV2

I have bumped the version in the recent commits

**Review by manolerazvan — APPROVED** [review]

**Review by aleksandrlevochkin — APPROVED** [review]

**Review by aleksandrlevochkin — APPROVED** [review]

**Pull request merged**
