### PR TITLE
Clone to PR18229 - AzureFunctionApp@2: Better alias for Service Connection

### PR DESCRIPTION
**Pull request by v-nagarajku**
**Task name**: AzureFunctionApp@2

**Description**: "Azure Subscription" is a terrible variable name for something that is not an Azure Subscription.

**Documentation changes required:** Y

**Added unit tests:** N

**Attached related issue:** https://github.com/MicrosoftDocs/azure-devops-docs/issues/13281

**Checklist**:
- [X ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ X] Checked that applied changes work as expected

### CODE REVIEW

**Review by nis-spiir — APPROVED** [review]

**Review by FinVamp1 — COMMENTED** [review]
Looks good

**Review by FinVamp1 — APPROVED** [review]
Approved

**Comment by v-nagarajku** [comment]
This was the original PR - https://github.com/microsoft/azure-pipelines-tasks/pull/18229 created for the fix and this PR is based on that.

**Review by geekzter — APPROVED** [review]

**Pull request merged**
