### PR TITLE
Fix to ignore "Resource file has already set to" warning message in KubernetesV1

### PR DESCRIPTION
**Pull request by EshitaD**
**Task name**:  KubernetesV1

**Description**:  This code change will ignore 'Resource file has already set to' warning message in KubernetesV1

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:**[DTS TASK 2191553](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/2191553)

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by manolerazvan — APPROVED** [review]

**Comment by adamshawvipps** [comment]
Hi we are seeing warnings still. Is there anything I need to do to receive the update?


`2024-07-18T08:07:52.5644883Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/Kubernetes_cbc316a2-586f-4def-be79-488a1f503564/1.241.5/node_modules/azure-pipelines-tasks-azure-arm-rest/module.json
`

**Comment by EshitaD** [comment]
Hi @adamshawvipps, by end of the week changes will be deployed to every ring. Can you please provide your org name.

**Comment by adamshawvipps** [comment]
Thanks @EshitaD.
The org is `Vipps` or `Vipps AS`. We are running out of West Europe I believe

**Comment by EshitaD** [comment]
@adamshawvipps For your org the changes will be rolled out by Monday

**Pull request merged**
