### PR TITLE
Updated lodash and lodash.merge dependencies to the latest version in Tasks/AppCenterTestV1

### PR DESCRIPTION
**Pull request by sbalia**
Versions of lodash before 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep allows a malicious user to modify the prototype of Object via {constructor: {prototype: {...}}} causing the addition or modification of an existing property that will exist on all objects.

### CODE REVIEW

**Review by nikita-potashev — APPROVED** [review]

**Review by andrii-z4i — APPROVED** [review]

**Review by lucen-ms — APPROVED** [review]

**Comment by sbalia** [comment]
updated to 1.205.0 version in task.json and task.loc.json as suggested by @KonstantinTyukalov

**Comment by sbalia** [comment]
@andrii-z4i , @KonstantinTyukalov , can somebody merge it? As I don't have enough permissions to do it (I don't have write access to this repo).

**Pull request merged**
