### PR TITLE
fix wrong osTypeMap (kind) value for Windows container

### PR DESCRIPTION
**Pull request by eriawan**
This PR is to fix incorrect `osTypeMap` (web app container `kind`) value for Windows container in `Tasks/AzureWebAppContainerV1/taskparameters.ts` code file. It should be `app,container,xenon` instead of `app,conatiner,xenon`.

This is a sample properties of web app container on my Azure account:

image

So now the `private static async getWebAppKind` function will return correct map (web app container service **_kind_**).

### CODE REVIEW

**Comment by SumiranAgg** [comment]
@eriawan Thanks for contributing. Can you bump up the task patch version int his file azure-pipelines-tasks/Tasks/AzureWebAppContainerV1/task.json.
Build the task once and update PR. You can find complete details for contributing  here https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/contribute.md

**Comment by eriawan** [comment]
@SumiranAgg 
thanks! I'm going to update (increase) the patch version now.

**Comment by eriawan** [comment]
@SumiranAgg 

I have bumped the version patch number. Please review, thanks in advance! 🙂

**Comment by SumiranAgg** [comment]
You also need to build and test the task changes. For now I have done that and updated the PR. Thank you for the contribution.

**Comment by eriawan** [comment]
@SumiranAgg 
aha, I understand now! Thanks for your guidance! 
So not just `task.json`, but also `task.loc.json` has to be updated.

**Comment by SumiranAgg** [comment]
Yes. Its an auto-generated file when we build the task. Making direct change to that file is not advisable.

**Comment by eriawan** [comment]
@SumiranAgg 
is there anything I should do next on my side? Do I have to run the test and check in too?

Also I wonder why the Azure Pipelines CI builds are all waiting (not running at all).

**Comment by SumiranAgg** [comment]
The jobs were not getting picked. We are fixing the issue right now. It took time but all checks were cleared. I have merged the PR.

**Comment by eriawan** [comment]
Many thanks for your guidance and patience, @SumiranAgg ! 🙂 👍

**Pull request merged**
