### PR TITLE
Changed github releases hostname (#14309)

### PR DESCRIPTION
**Pull request by JakubWojtowicz-TomTom**
Signed-off-by: Jakub Wojtowicz <jakub.wojtowicz@tomtom.com>

**Task name**:  

**Description**: Changed host ignored for authorization header modification.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** https://github.com/microsoft/azure-pipelines-tasks/issues/14309

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by ED220Webfactory** [comment]
Would this code be more robust to potential future changes on GHs side, by just switching the host-predicate?
EG using auth header for api.github.com, and stripping it for everything else (download)?

**Comment by JakubWojtowicz-TomTom** [comment]
> Would this code be more robust to potential future changes on GHs side, by just inverting the host-predicate?
> Eg using auth header for api.github.com, and stripping it for everything else (download)?

Nice catch.
Applied suggested change.

**Review by martinkocjan-tomtom — APPROVED** [review]

**Comment by JakubWojtowicz-TomTom** [comment]
Closing PR since issue was solved in another PR.

**Comment by narula0781** [comment]
Thanks @JakubWojtowicz-TomTom

**Pull request closed without merging**
