### PR TITLE
Fix GithubRelease error when detecting endpoint token

### PR DESCRIPTION
**Pull request by ljvmiranda921**
Reference: #11558 

The endpoint object scheme being detected when service connection is made from the UI is `Token`, not `PersonalAccessToken`. I added the `Token` scheme so that this type gets passed.

**In the meantime, I wrote a workaround here:** https://ljvmiranda921.github.io/notebook/2019/12/28/workaround-azure-github-pat/ (in case this link hasn't been merged yet)

cc @romil07 @Lovakumar

### CODE REVIEW

**Comment by hecflores** [comment]
Is this still waiting for approvers... I ran into this issue today and was wondering when can I expect to see this fix in the live site. Region Central US

**Comment by ljvmiranda921** [comment]
Yup @hecflores , still waiting for reviewers. For the meantime, I wrote a workaround here: https://ljvmiranda921.github.io/notebook/2019/12/28/workaround-azure-github-pat/

**Comment by jakeholland** [comment]
I also ran into this issue today. Very frustrating that this has not been looked at.

**Comment by RTodorov** [comment]
Hello folks,

Any idea when this fix will be merged and released? It's basically blocking the usage of the extension unless we do OAuth, which is not ideal for a lot of people.

@JSalazar88 @jakeholland 

Thank you

**Comment by guthriec** [comment]
I also would like this to get merged please!

**Comment by RTodorov** [comment]
@jalajmsft @bishal-pdMSFT sorry for tagging you here but this seems like an easy merge that would help a lot of people.

Thank you!

**Comment by bishal-pdMSFT** [comment]
@RaghuJ80 and @romil07 please take a look

**Comment by RTodorov** [comment]
@RaghuJ80 @romil07 any news on this one?

**Comment by romil07** [comment]
@ljvmiranda921 I missed this.
And about this issue, what you have done is correct but I am looking at a way to avoid this altogether.
I will come back with an update.

**Comment by romil07** [comment]
@ljvmiranda921 
I have merger your commit to master.
This will be available to you with next sprint deployment. I am not going to hotfix this since you already have a work around for now.

**Comment by ljvmiranda921** [comment]
Thank you so much @romil07 !!

**Review by akankshakothari — COMMENTED** [review]
good

**Pull request merged**
