### PR TITLE
[DotNetCoreCLIV2] Fix #12562 by adding support to --skip-duplicate as a task input parameter

### LINKED ISSUE #12562: dotnet nuget push "SkipDuplicate" option for org feed
## Required Information
**Type**: Feature
**Enter Task Name**: DotNetCoreCLI

## Issue Description
When using the DotNetCoreCLI task, command "nuget push", it is not possible to specify "SkipDuplicates". This option does seem to exist on the cli itself and in the Nuget task.

dotnetcorecli

nuget

In YAML terms:
```yaml
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push
    packagesToPush: '$(System.DefaultWorkingDirectory)/_testpackage/drop/**/*.nupkg'
    publishVstsFeed: 'testfeedguid'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'testfeedguid'
    allowPackageConflicts: true
```

### PR DESCRIPTION
**Pull request by RTodorov**
This PR resolves #12562 by adding support to the `--skip-duplicate` parameter when calling the `dotnet` cli for pushing NuGet packages.

### CODE REVIEW

**Comment by RTodorov** [comment]
According to the contribution guidelines, I should kindly ask the relevant people for review.

@damccorm 
@bishal-pdMSFT 
@vineetmimrot 
@pulkitaggarwl

**Comment by RTodorov** [comment]
Hi @damccorm ! Do you know what's the process to get a review for this PR? Thank you.

**Comment by damccorm** [comment]
@bishal-pdMSFT could you or someone on your team take a look at this?

**Comment by bishal-pdMSFT** [comment]
Sorry for the delay, it went under the radar. And thanks @RTodorov for raising the PR.

One thought I have here is whether it would be better to introduce a more generic "arguments" input rather than a very specific one just for skip-duplicate. The generic arguments input can potentially be used for other [options](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push#options) as well.

@phil-hodgson @satbai what do you think as this change is related to nuget push.
@tejasd1990 please review.

**Comment by RTodorov** [comment]
Any decision here?

**Comment by satbai** [comment]
@bishal-pdMSFT had a good point, an 'arguments' input would be a better option here because it will cover skip-duplicate along with other arguments. That will also align with the other dotnet commands, for example the [dotnet restore](https://github.com/microsoft/azure-pipelines-tasks/blob/6fa7a77bf9c6ddaef03f8f1f08f2703e1c0ba02c/Tasks/DotNetCoreCLIV2/restorecommand.ts#L135) command allows arguments.

**Comment by michael-hawker** [comment]
We have a need for this, would have been great to see this PR have gotten in to make it easier to unblock our current problem.

A new issue/PR can always be filed in the future for a more general solution, don't see why that should stop this current fix.

**Comment by davrob01** [comment]
I have been waiting on this as well. I have a solution with multiple projects and one pipeline that should only push the projects that have new version numbers.

I can't achieve this easily without the skip duplicates argument.

**Comment by satbai** [comment]
Thank you for preparing the PR, we appreciate the initiative. However, I have discussed this with the team and we have decided not to accept this PR. Instead of using these "bulkier" tasks we now recommend using the [NuGet Authenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) task to authenticate to Azure DevOps Artifacts feeds and to use a script task with nuget/dotnet to use the parameters you need. 

```
- task: NuGetAuthenticate@0
- task: UseDotNet@2 # Optional if the .NET Core SDK is already installed
- script: dotnet restore
# ...
- script: dotnet nuget push --api-key AzureArtifacts --skip-duplicate --source https://pkgs.dev.azure.com/{organization}/{project?}/_packaging/{feed1}/nuget/v3/index.json MyProject.*.nupkg 
```

The reason for this is that the NuGet/Dotnet clients are actively being developed and new parameters and functionality are being added often. To keep up with all of the updates causes a lot of extra support for these bulky tasks. Please use example above to set up your pipeline with the '--skip-duplicate' parameter. Thank you for understanding.

**Comment by tilicon** [comment]
Talk about being bulky!

So instead of actually honoring the arguments section where I could put --skip-duplicate or any other parameter you are now forcing me to instead use a a NuGet task and a script(!?) - utterly useless.

**Pull request closed without merging**
