### PR TITLE
fix no wait result bug

### PR DESCRIPTION
**Pull request by RuoyuWang-MS**
**Task name**: AzureSpringCloudV0

**Description**: Fix deployment no wait bug

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N)  https://msazure.visualstudio.com/AzureDMSS/_workitems/edit/13118175/

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by EzzhevNikita — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Comment by RuoyuWang-MS** [comment]
Hi @anatolybolshakov @EzzhevNikita @mmrazik . Thanks for your review. I have a small question. Will you help merge this PR and when is next release( or when will the changes take effect on customers)? 😀

**Review by mmrazik — APPROVED** [review]

**Pull request merged**
