### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by viralpandya**
**Task name**: PublishSymbolsV2

**Description**: Readme file changes for CI integration

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) NA

**Attached related issue:** (Y/N) NA

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by viralpandya** [comment]
Here is the CI check validation for PR [CI check](https://dev.azure.com/canarytest/PipelineTasks/_build/results?buildId=112497&view=results)

**Review by fadnavistanmay — APPROVED** [review]
Viral is going to create a wiki for dev testing and remove them from the README file.

**Comment by viralpandya** [comment]
Created wiki already

**Comment by viralpandya** [comment]
> Viral is going to create a wiki for dev testing and remove them from the README file.
Created wiki already

**Pull request merged**
