### PR TITLE
Fixes Issue #6245 - Merge PR from ryant/master/issue6245 into master

### PR DESCRIPTION
**Pull request by RyanThomas73**
**Issue #6245**
Updated the `AppCenterDistribute` task's `resolvePath(..)` logic to support absolute paths. The function will call `tl.exists(...)` to determine if it is an absolute path to a file that exists before attempting to resolve it as a relative path using `tl.findMatch(..)`.

### CODE REVIEW

**Comment by scottdensmore** [comment]
Sorry for the late response. @RyanThomas73 can you resolve conflicts and we will get this merged.

**Comment by RyanThomas73** [comment]
@scottdensmore Updated

**Comment by stephenmichaelf** [comment]
@scottdensmore Should this be merged?

**Comment by RyanThomas73** [comment]
This PR I created a while back is really stale. Anyone know if it is no longer needed / I should abandon it?

**Comment by stephenmichaelf** [comment]
Closing due to age, please reopen if needed.

**Pull request closed without merging**
