### PR TITLE
Add minimumAgentVersion to migrateNode10.md

### PR DESCRIPTION
**Pull request by bryceitoc9**
**Task name**: Node10 migration documentation

**Description**: Self experimentation showed that bumping the minimumAgentVersion automatically updated self hosted agents on an Azure DevOps Server instance. Version `2.144.0` is required for `Node10` execution targets.

**Documentation changes required:** (Y/N) N; change _is_ a documentation change

**Added unit tests:** (Y/N) N; not needed for documentation

**Attached related issue:** (Y/N) Y; https://github.com/microsoft/azure-pipelines-tasks/issues/15606

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by alexander-smolyakov — APPROVED** [review]

**Review by anatolybolshakov — APPROVED** [review]

**Comment by anatolybolshakov** [comment]
Thanks for contribution!

**Comment by alexander-smolyakov** [comment]
@bryceitoc9 could you please sign the CLA so we can merge this?

**Comment by bryceitoc9** [comment]
@alexander-smolyakov Can do...how do I do that?

**Pull request merged**
