### PR TITLE
cg fix for PackerBuildV0

### PR DESCRIPTION
**Pull request by EshitaD**
**Task name**: PackerBuildV0

**Description**: cg fix

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by EshitaD** [comment]
@microsoft-github-policy-service agree [company="Mindtree"]

**Comment by EshitaD** [comment]
@microsoft-github-policy-service agree company="Mindtree"

**Review by v-mohithgc — APPROVED** [review]

**Review by rvairavelu — APPROVED** [review]

**Pull request merged**
