### PR TITLE
Fix typo objcet -> object

### PR DESCRIPTION
**Pull request by MattJeanes**
**Task name**: KubernetesManifestV0

**Description**: Fix typo in debug log

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N/A

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by MattJeanes** [comment]
Still valid

**Comment by MattJeanes** [comment]
Still valid!

**Comment by kirill-ivlev** [comment]
@MattJeanes  could you please [bump task version](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) to the current sprint?

**Comment by MattJeanes** [comment]
Hi @kirill-ivlev - I have now done this and rebased into a single commit to clean up

**Pull request closed without merging**
