### PR TITLE
Removing the deprecation tag for PCCRV1

### PR DESCRIPTION
**Pull request by vinayakmsft**
**Task name**:  PublishCodeCoverageV1

**Description**:  We want to remove the deprecation tag for now, since the major updates for the PCCRV2 are in progress and we dont want the customers to move to V2 until all the features parities are addressed. That is why we are removing this deprecation tag. We will be adding all the missing features in the PublishCodeCoverageV2 and once the new version is completely shipped then we will add back this deprecation tag to the V1 task. 

**Documentation changes required:** (Y/N) Y

Output:

image

Before (deprecation message for PCCRV1)

image

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by skmanoj** [comment]
Can you have a screenshot on how it looks now, with the deprecation message

**Review by skmanoj — APPROVED** [review]

**Review by skmanoj — APPROVED** [review]

**Review by triptijain2112 — APPROVED** [review]

**Comment by triptijain2112** [comment]
Approved based on previous approvals

**Comment by nickperkins** [comment]
@vinayakmsft  Just noting that the warning still shows when the task is downloaded during job initialisation
image
image

**Comment by pinkfloydx33** [comment]
Any way to suppress the warning emitted during task download?

**Pull request merged**
