### PR TITLE
Add 'allowCanceledBuilds' input for DownloadPipelineArtifactV2

### PR DESCRIPTION
**Pull request by 50Wliu**
**Task name**: DownloadPipelineArtifactV2

**Description**: DownloadPipelineArtifactV2 is missing the `allowCanceledBuilds` input, added in microsoft/azure-pipelines-agent#3254.

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) Y
microsoft/azure-pipelines-agent#3254
Reference: https://github.com/microsoft/azure-pipelines-agent/blob/6b5814a51706cd0988eec0fb9ed0b7dc311912d8/src/Agent.Plugins/PipelineArtifact/PipelineArtifactPluginV2.cs#L89

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
  - I don't think I need to do this? It's adding an input that already exists.
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by 50Wliu** [comment]
Nope, definitely not stale :).

**Comment by b-barthel** [comment]
This needs a version bump so existing pipelines/tasks know to upgrade.  Otherwise looks fine.

**Comment by 50Wliu** [comment]
Done!

**Review by b-barthel — APPROVED** [review]

**Review by fadnavistanmay — APPROVED** [review]

**Comment by 50Wliu** [comment]
Still relevant...could I please get this merged?

**Comment by 50Wliu** [comment]
I was on vacation so couldn't respond in time...this is still an issue.

**Pull request closed without merging**
