### PR TITLE
Change Obsolete Attribute to Log Message

### PR DESCRIPTION
**Pull request by ozanovus**
**Task name**: 
AzureFileCopyV2
AzureFileCopyV3
AzureFileCopyV4
AzureFileCopyV5
SqlAzureDacpacDeploymentV1

**Description**: Obsolete attribute warning messages are changed to log message.

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [X] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [X] Checked that applied changes work as expected

### CODE REVIEW

**Comment by kingk5** [comment]
To Bump these versions do we have change the version on our pipeline task or will there be just internal code change.

**Comment by kingk5** [comment]
@ozanovus @PavloAndriiesh 
To Bump these versions do we have change the version on our pipeline task or will there be just internal code change.

**Review by manolerazvan — APPROVED** [review]

**Comment by ozanovus** [comment]
> @ozanovus @PavloAndriiesh To Bump these versions do we have change the version on our pipeline task or will there be just internal code change.

Hi @kingk5 ; I'm not sure if I understand your question correctly but we're regularly updating tasks according to needing. These tasks will be automatically delivered to your organization (you don't need to change pipeline) with a deployment calendar (e.g. currently x.218.y versions are being deployed).  
It is hard to say from now but 219 versions probably will be delivered end of this month or within next month.

**Pull request merged**
