### PR TITLE
vulnerabilities fixes for DownloadGitHubReleaseV0

### PR DESCRIPTION
**Pull request by v-bsanthanak**
**Task name**: DownloadGitHubReleaseV0
**Description**: 

**Documentation changes required:** (Y/N) 

**Added unit tests:** (Y/N) 

**Attached related issue:** (Y/N)  https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/2029522/?view=edit
**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected
- [x] node make.js build --task DownloadGitHubReleaseV0
- [x] node make.js test --task DownloadGitHubReleaseV0

### CODE REVIEW

**Review by rvairavelu — APPROVED** [review]

**Comment by v-mohithgc** [comment]
Duplicate of https://github.com/microsoft/azure-pipelines-tasks/pull/18130.
Please close this PR

**Pull request closed without merging**
