### PR TITLE
[NotationV0] feat: azure-kv plugin workload identity support

### PR DESCRIPTION
**Pull request by JeyJeyGao**
**Task name**: NotationV0

**Description**: 
Feat: 
- added workload identity support for azure-kv plugin

Fix:
- automatically override the AKV plugin version if the current version does not match the user-defined version.

Test:
- akv plugin v1.0.1 with service principle and workload id
- akv plugin v1.1.0 with service prinfiple and workload id
- upgrade akv plugin from v1.0.1 to v1.1.0

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by JeyJeyGao** [comment]
Test issue is not related to this PR and will be solved later.

**Review by shizhMSFT — APPROVED** [review]
LGTM but IANAM

**Comment by shizhMSFT** [comment]
@JeyJeyGao can you fix the check?

**Comment by JeyJeyGao** [comment]
> @JeyJeyGao can you fix the check?

Passed now.

**Review by DmitriiBobreshev — APPROVED** [review]

**Pull request merged**
