### PR TITLE
Removal date for deprecated tasks

### PR DESCRIPTION
**Pull request by DenisRumyantsev**
***List of tasks:***
* AppCenterDistributeV1
* AppCenterDistributeV2
* AzureMonitorV0
* ChefKnifeV1
* ChefV1
* CondaEnvironmentV1
* DeployVisualStudioTestAgentV2
* DotNetCoreInstallerV1
* DownloadPackageV0
* DownloadPipelineArtifactV0
* DownloadPipelineArtifactV1
* IISWebAppDeployment
* NuGetAuthenticateV0
* NuGetInstallerV0
* NuGetPackagerV0
* NuGetPublisherV0
* NuGetRestoreV1
* NuGetV0
* PublishPipelineArtifactV0
* QuickPerfTestV1
* RunJMeterLoadTestV1
* RunLoadTestV1
* SqlServerDacpacDeployment
* XamarinTestCloudV1

***Description:*** Add removal date for deprecated tasks.

***Documentation changes required:*** No

***Added unit tests:*** No

***Checklist:***
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by jmyersmsft** [comment]
Just for general knowledge, what does this property do in terms of agent and UI behavior?

**Review by vmapetr — APPROVED** [review]

**Comment by DenisRumyantsev** [comment]
Hi @jmyersmsft

We will implement a warning in the `Initialize job` step for deprecated tasks used in the pipeline.
The removal date will be displayed in this warning.

Here is the related PR in the agent —
https://github.com/microsoft/azure-pipelines-agent/pull/4458

**Comment by fadnavistanmay** [comment]
> Hi @jmyersmsft
> 
> We will implement a warning in the `Initialize job` step for deprecated tasks used in the pipeline. The removal date will be displayed in this warning.
> 
> Here is the related PR in the agent — [microsoft/azure-pipelines-agent#4458](https://github.com/microsoft/azure-pipelines-agent/pull/4458)

Will the builds fail, if folks don't upgrade to the later task version?

**Comment by DenisRumyantsev** [comment]
Hi @fadnavistanmay
No, with these changes, builds will run successfully as normal, until we remove deprecated tasks from ADO.
The only purpose of these changes is to inform customers about the removal of deprecated tasks in the future.

**Review by manolerazvan — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Comment by zhenghao104** [comment]
> Hi @jmyersmsft
> 
> We will implement a warning in the `Initialize job` step for deprecated tasks used in the pipeline. The removal date will be displayed in this warning.
> 
> Here is the related PR in the agent — [microsoft/azure-pipelines-agent#4458](https://github.com/microsoft/azure-pipelines-agent/pull/4458)

@DenisRumyantsev Are these changes live and tested in production already? Our team was planning to deprecate the tasks earlier than these dates, some time next month, will it be a problem to shift the date of some of the tasks to November 2023?

**Comment by DenisRumyantsev** [comment]
Hi @zhenghao104. Can you confirm the dates you wanted to change have been changed?

**Pull request merged**
