### PR TITLE
Updates PublishTestResults task version

### PR DESCRIPTION
**Pull request by v-padiseshu**
**Task name**: PublishTestResultsV2

**Description**: Updating task version

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by navin22 — APPROVED** [review]

**Comment by Arwinder4** [comment]
azp run

**Pull request merged**
