### PR TITLE
DownloadBuildArtifactsV0

### PR DESCRIPTION
**Pull request by ivanduplenskikh**
**Task name**: DownloadBuildArtifactsV0

**Description**:
- Upgraded @types/node and azure-pipelines-task-lib
- Added node16 execution handler

**Documentation changes required:** N

**Added unit tests:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by vmapetr — APPROVED** [review]

**Review by Roman-Shchukin — APPROVED** [review]

**Review by wojgasior — APPROVED** [review]

**Comment by ivanduplenskikh** [comment]
@narula0781, could you please check this PR?

**Review by v-nmursapall — APPROVED** [review]

**Review by v-msafiya — COMMENTED** [review]
Upgrade the minor version and task lib version

**Review by v-msafiya — APPROVED** [review]

**Review by kirill-ivlev — APPROVED** [review]

**Comment by lorengordon** [comment]
Appears 0.216.0 was released within the last day, and jobs are now failing to actually download artifacts. Same jobs worked fine using 0.212.0 yesterday... Example of failing job: https://dev.azure.com/plus3it/watchmaker/_build/results?buildId=5482&view=logs&j=d4aecca3-a437-5e55-8920-532a8eb17862

**Pull request merged**
