### PR TITLE
Migrate DownloadGitHubNpmPackageV1 task to Node10

### PR DESCRIPTION
**Pull request by golubev-ivan**
**Task name**: DownloadGitHubNpmPackageV1

**Description**: Migrated DownloadGitHubNpmPackageV1 task to Node10.

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Comment by golubev-ivan** [comment]
Testednmanually, everything works fine

**Comment by golubev-ivan** [comment]
Hi @harshiniks, Could you please take a look at this PR?

**Review by denis-tikhomirov — APPROVED** [review]

**Review by alexander-smolyakov — APPROVED** [review]

**Comment by mpodriezov** [comment]
-  Merged conflicts with master
- removed request library as it is not used, this fixed all CG bugs
- bumped the version in task.json

**Review by v-nmursapall — APPROVED** [review]
works fine.

**Pull request merged**
