### PR TITLE
Surround docker-common labels with qoutes

### PR DESCRIPTION
**Pull request by abij**
Hi,

I'm trying to use the Docker@2 task, which automatically adds labels.
The feature also adds: `requestedfor`-label this adds my Firstname [space] Lastname and the build fails, because of the space.

Hereby I suggest a simple, yet effective solution to surround the label values with qoutes.

### CODE REVIEW

**Comment by ajinkya599** [comment]
Hey @abij. I tried this out on both Ubuntu and Windows agents, and the build is succeeding for me.

Which agent are you using ?
What is the agent version ?
Can you share the logs for the failing build ?

**Comment by abij** [comment]
Good question, we are using the pool of: Hosted Ubuntu 1604.
This is the log:
```
##[section]Starting: Build docker image
==============================================================================
Task         : Docker
Description  : Build or push Docker images, login or logout, or run a Docker command. Task can be used with Docker registry.
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=848006)
==============================================================================
[command]/usr/bin/docker build -f /home/vsts/work/1/s/jupyterhub/Dockerfile --label com.visualstudio.********.image.system.teamfoundationcollectionuri=https://********.visualstudio.com/ --label com.visualstudio.********.image.system.teamproject=SomeProject --label com.visualstudio.********.image.build.repository.name=aws-jupyterhub --label com.visualstudio.********.image.build.repository.uri=https://********.visualstudio.com/SomeProject/_git/aws-jupyterhub --label com.visualstudio.********.image.build.sourcebranchname=show_version_nr --label com.visualstudio.********.image.build.sourceversion=e9255dd2f2c725c98b7a66b843fdfa2699b8a9e9 --label com.visualstudio.********.image.build.definitionname=aws-jupyterhub --label com.visualstudio.********.image.build.buildnumber=20190514.6 --label com.visualstudio.********.image.build.builduri=vstfs:///Build/Build/18546 --label com.visualstudio.********.image.build.requestedfor=Alexander Bij BUILD_DEFINITION=aws-jupyterhub_show_version_nr#20190514.6 -t ***.azurecr.io/***.azurecr.io/SomeProject/jupyterhub:latest /home/vsts/work/1/s/jupyterhub
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
##[error]"docker build" requires exactly 1 argument.
##[error]See 'docker build --help'.
##[error]Usage:  docker build [OPTIONS] PATH | URL | -
##[error]Build an image from a Dockerfile
##[error]/usr/bin/docker failed with return code: 1
##[section]Finishing: Build docker image
```

**Comment by abij** [comment]
Another note: the problems occurs when you set: `addDefaultLabels: true` otherwise these labels are not included. Looks like the default is `true` though..

**Comment by ajinkya599** [comment]
Hey @abij. It looks like the problem is because of this argument in the command: `BUILD_DEFINITION=aws-jupyterhub_show_version_nr#20190514.6`
It seems this is given in the `arguments` input of the task. Please remove this and try out the build (or if you want to add it as a label, prepend the `arguments` input with `--label`).

**Comment by abij** [comment]
You are right, this `BUILD_DEFINITION=aws-jupyterhub#20190514.6` should be prepended with `--build-arg`. Removing it makes the build fail with the same reason, expected 1 argument. 

Check the docker spec about [LABEL](https://docs.docker.com/v17.09/engine/reference/builder/#label)

**Comment by leantk** [comment]
This PR is stale because it has been open for a year with no activity. Remove the stale label or comment on the PR otherwise this will be closed in 5 days

**Pull request closed without merging**
