### PR TITLE
The VALUE for WEBSITE_RUN_FROM_PACKAGE must be 1

### PR DESCRIPTION
**Pull request by rikat-ms**
The value for WEBSITE_RUN_FROM_PACKAGE must be 1. If the value is 'true', it will be ignored at deployment and cause the deployment to fail from the pipeline.

**Task name**: AzureFunctionApp@1

**Description**: The value for 'WEBSITE_RUN_FROM_PACKAGE' is set to 'true' in the current source code of this task but it must be 1. If 'true' is set to this app setting, the deployment may fail with "An unknown error has occurred. Check the diagnostic log for details." and you can find "Deployment lock failure" in a trace file for App Service. This can happen especially with Functions on Linux. And if the value is set to "true", the zip file is deployed to the file server for App Service and extracted to /home/site/wwwroot but not mounted. So, /home/site/wwwroot is not set to ReadOnly. This happens because 'true' is not an expected value for 'WEBSITE_RUN_FROM_PACKAGE' and it's ignored. If the value is set to 1, the zip file is mounted and  /home/site/wwwroot is set to ReadOnly.

**Documentation changes required:** (Y/N) N

**Added unit tests:** (Y/N) N

**Attached related issue:** (Y/N) N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Review by mmrazik — APPROVED** [review]

**Comment by mmrazik** [comment]
@rikat-ms can you please bump the task version as per the PR checklist?

**Review by mmrazik — CHANGES_REQUESTED** [review]
We need to bump the task version.

**Comment by rikat-ms** [comment]
@mmrazik would you please check again? I bumped the task version more than two weeks ago and it seems some approvals are required,

**Comment by rikat-ms** [comment]
Hey @mmrazik , master branch was updated while this PR is waiting for review and it caused conflict in version in task.json. What should I do for it?

**Comment by mmrazik** [comment]
Sorry, I completely missed this :(
However, the fix is already in via another PR https://github.com/microsoft/azure-pipelines-tasks/blob/25a06112941d4c8c8db673000fab53ef03aac1f5/Tasks/AzureFunctionAppV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts#L12 
It is pending deployment to production, though.

**Pull request closed without merging**
