### PR TITLE
JavaToolInstallerV0 - fixed artifact-engine vulnerabilities

### PR DESCRIPTION
**Pull request by anatolybolshakov**
**Task name**: JavaToolInstallerV0

**Description**: bumped azp-tasks-az-blobstorage-provider-v2 dependency to 1.1.0 - fixed artifact-engine vulnerabilities

**Documentation changes required:** N

**Added unit tests:** N

**Attached related issue:** N

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected - tested locally with azp-tasks-az-blobstorage-provider-v2 manually updated

### CODE REVIEW

**Comment by anatolybolshakov** [comment]
Waiting for https://github.com/microsoft/azure-pipelines-tasks/pull/16322 to be merged

**Review by kirill-ivlev — APPROVED** [review]

**Review by KonstantinTyukalov — APPROVED** [review]
LGTM, thanks! Coudld you bump the task version?

**Comment by anatolybolshakov** [comment]
TBD - need to update package-lock as well once changes for azp-tasks-az-blobstorage-provider-v2 package are published

**Comment by KonstantinTyukalov** [comment]
It seems the related changes was done on other PRs. Closing this

**Pull request closed without merging**
