### PR TITLE
fix vm2 dep

### PR DESCRIPTION
**Pull request by PavloAndriiesh**
**Task name**: AppCenterDistributeV3, AppCenterTestV1

**Description**: https://dev.azure.com/mseng/PipelineTools/_componentGovernance/184/alert/106670?action=ContributedHub&controller=Apps&typeId=91140

**Documentation changes required:** (Y/N) <Please mark if documentation changes are required>

**Added unit tests:** (Y/N) <Please mark if unit tests were added or updated according changes>

**Attached related issue:** (Y/N) <Please add link to related issue here>

**Checklist**:
- [ ] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [ ] Checked that applied changes work as expected

### CODE REVIEW

**Comment by lucen-ms** [comment]
@Oleg-Karoza and @alexey-chernikov please update this PR with updated file-upload library which has fixed vm2 dependency.

**Comment by sergei-fedorov** [comment]
@lucen-ms there is no need to bump `appcenter-file-upload-client-node`, the latest version is used now 1.2.10. The reason is its version was not bumped in https://github.com/microsoft/appcenter-cli/pull/2323. So vm2 is updated to 3.9.19 in AppCenterTestV1.

**Comment by sergei-fedorov** [comment]
My bad, fixed here https://github.com/microsoft/azure-pipelines-tasks/pull/18451

**Pull request merged**
