### PR TITLE
Fixed matching files to search files inside directory

### PR DESCRIPTION
**Pull request by alexander-prozorov**
**Task name**: ExtractFilesV1

**Description**: Changed the way of matching files using a pattern. 

Array allFiles [here](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ExtractFilesV1/extractfilestask.ts#L84) contains all the files inside the target directory found recursively. So call

`minimatch.match(allFiles, *.zip, matchOptions);`

returns all files that match the pattern ignoring the folder structure. Updated call

`minimatch.match(allFiles, directore/*.zip, matchOptions);`

returns files from the correct directory.

**Documentation changes required:** No

**Added unit tests:** No

**Attached related issue:** 

- https://github.com/microsoft/azure-pipelines-tasks/issues/13434

**Checklist**:
- [x] Task version was bumped - please check [instruction](https://github.com/microsoft/azure-pipelines-tasks/tree/master/docs/taskversionbumping.md) how to do it
- [x] Checked that applied changes work as expected

### CODE REVIEW

**Review by egor-bryzgalov — APPROVED** [review]

**Comment by damccorm** [comment]
Could we add a test for this? Otherwise LGTM

**Comment by alexander-prozorov** [comment]
> Could we add a test for this? Otherwise LGTM

Yes, we added tests:

- https://github.com/microsoft/azure-pipelines-canary/pull/368

**Comment by AndrewGretton** [comment]
I believe this change may have caused problems for our build. Prior to this change, a V1 Extract Files task was able to find a zipfile in a nested directory (i.e. not in the root), and after we updated our agents , it was not. We needed to make the following change to a task group to get it working again. 

globchange

**Comment by aaronentwistle** [comment]
> I believe this change may have caused problems for our build. Prior to this change, a V1 Extract Files task was able to find a zipfile in a nested directory (i.e. not in the root), and after we updated our agents , it was not. We needed to make the following change to a task group to get it working again.
> 
> globchange

We're experiencing this issue too, I've opened issue #13576 for this.

**Comment by kauemendes** [comment]
This change has caused several problems with my Releases. A suggestion that could be in some way notified in a better way the next time. Thanks!

**Comment by devel112** [comment]
Broke our pipeline too, silently - this pipeline task i mismanaged - time to use powershell...

**Pull request merged**
