### PR TITLE
Added write and delete permisions to outgoing SAStoken

### PR DESCRIPTION
**Pull request by Geronius**

### CODE REVIEW

**Comment by RoopeshNair** [comment]
@Geronius  - can you please share the scenario for enabling write/delete permissions by default? I'm missing the context

**Comment by Geronius** [comment]
> @Geronius - can you please share the scenario for enabling write/delete permissions by default? I'm missing the context

I use this function uploading ARM files for deployment within AzureDevOps. After the deployment is complete I want to remove the files with the same sas-token.

**Comment by Geronius** [comment]
@rajatagrawal-dev i've made the requested changes in my repository. Can I updated this pull-request some way or do I have to create a new one?

**Comment by rajatagrawal-dev** [comment]
> > > @rajatagrawal-dev i've made the requested changes in my repository. Can I updated this pull-request some way or do I have to create a new one?
> > 
> > 
> > @Geronius I still see changes in Azure File Copy V2 in the PR. Can you please sync your branch with the latest master from Microsoft/azure-pipelines-tasks? Make sure that only 3 files are changed in the PR - AzureFileCopyV3/AzureFileCopy.ps1, AzureFileCopyV3/task.json and AzureFileCopyV3/task.loc.json
> > After the above changes, this same PR should be fine.
> 
> I never updated a pr before. Now I understand I just create a new pr and the existing is updated.
> Can you see the changes now?
> I do not know ho to revert the changes of V2. I did revert my changes by I still see some changes

I think merging the master branch of Microsoft/azure-pipelines-tasks into your own branch will fix the PR.

**Comment by Geronius** [comment]
> > > > @rajatagrawal-dev i've made the requested changes in my repository. Can I updated this pull-request some way or do I have to create a new one?
> > > 
> > > 
> > > @Geronius I still see changes in Azure File Copy V2 in the PR. Can you please sync your branch with the latest master from Microsoft/azure-pipelines-tasks? Make sure that only 3 files are changed in the PR - AzureFileCopyV3/AzureFileCopy.ps1, AzureFileCopyV3/task.json and AzureFileCopyV3/task.loc.json
> > > After the above changes, this same PR should be fine.
> > 
> > 
> > I never updated a pr before. Now I understand I just create a new pr and the existing is updated.
> > Can you see the changes now?
> > I do not know ho to revert the changes of V2. I did revert my changes by I still see some changes
> 
> I think merging the master branch of Microsoft/azure-pipelines-tasks into your own branch will fix the PR.

I already did that

**Comment by rajatagrawal-dev** [comment]
@Geronius Any update on this? Were you able to revert the bad commit?

**Pull request closed without merging**
